import type { AppLocale } from "@/i18n/config"
import type { PlatformPageCopy } from "./types"

export function getPlatformPageCopy(locale: AppLocale, app: PlatformPageCopyApp): PlatformPageCopy {
  const appName = app

  if (locale === "fr") {
    return {
      landing: {
        home: "Accueil",
        datingPhotos: "Photos de rencontre",
        createPhotos: "Créer mes photos " + appName,
        seeExamples: "Voir des exemples",
        sampleCaption: "Exemples de photos de rencontre générées avec UnrealShot",
        profileProblem: "Le problème du profil",
        profileProblemHeading: "Pourquoi une pellicule pleine de photos peut laisser ton profil " + appName + " incomplet",
        solution: "La solution UnrealShot",
        solutionHeading: "De quelques selfies récents à une vraie sélection de photos de rencontre",
        deliveryEyebrow: "Comment ta livraison est créée",
        deliveryHeading: "Des idées de séances différentes. Une seule personne reconnaissable.",
        builtFor: "Pensé pour les profils " + appName,
        builtHeading: "Comment UnrealShot transforme quelques selfies en un profil " + appName + " plus complet",
        examplesHeading: "Découvrir d'autres exemples de photos de rencontre UnrealShot",
        examplesDescription: "Ces exemples ne montrent qu'une petite partie des directions créatives possibles. Ta livraison contient 15 idées de séances créées à partir de tes selfies récents et de tes réponses.",
        generatedLabel: "Généré avec UnrealShot",
        exploreExample: "Voir cet exemple →",
        requirementsHeading: "Règles photo actuelles de " + appName,
        primarySources: "Sources officielles",
        sourcesChecked: "Vérifiées le",
        faqHeading: "Questions sur UnrealShot pour " + appName,
        ctaEyebrow: "39 $ une seule fois · sans abonnement",
        ctaHeading: "Reçois 15 séances complètes en une livraison",
        ctaDescription: "Envoie 4 à 6 selfies récents et reçois 60 photos de rencontre sous 30 minutes. Tes références guident la ressemblance et 15 reprises photo individuelles sont incluses.",
      },
      guide: {
        home: "Accueil",
        guides: "Guides",
        writtenReviewed: "Rédigé et relu par",
        atAGlance: "en bref",
        inThisGuide: "Dans ce guide",
        productDetails: "Voir les détails du produit →",
        checklistHeading: "Checklist finale pour tes photos " + appName,
        faqHeading: "Questions fréquentes",
        officialSources: "Sources officielles",
        sourceDescription: "Les règles des plateformes évoluent. Ces sources officielles ont été vérifiées le",
        ctaHeading: "Il te manque les rôles photo décrits dans ce guide ?",
        ctaDescription: "UnrealShot crée 15 séances cohérentes et 60 photos à partir de 4 à 6 selfies, avec 15 reprises photo individuelles et une livraison sous 30 minutes.",
      },
    }
  }

  if (locale === "es") {
    return {
      landing: {
        home: "Inicio",
        datingPhotos: "Fotos para citas",
        createPhotos: "Crear mis fotos para " + appName,
        seeExamples: "Ver ejemplos",
        sampleCaption: "Ejemplos de fotos para citas generadas con UnrealShot",
        profileProblem: "El problema del perfil",
        profileProblemHeading: "Por qué tener el carrete lleno de fotos puede dejar incompleto tu perfil de " + appName,
        solution: "La solución de UnrealShot",
        solutionHeading: "De unos pocos selfies actuales a una selección completa de fotos para citas",
        deliveryEyebrow: "Cómo se crea tu entrega",
        deliveryHeading: "Ideas de sesiones distintas. Una sola versión reconocible de ti.",
        builtFor: "Creado para perfiles de " + appName,
        builtHeading: "Cómo UnrealShot convierte unos pocos selfies en un perfil de " + appName + " más completo",
        examplesHeading: "Mira más ejemplos de fotos para citas de UnrealShot",
        examplesDescription: "Estos ejemplos muestran solo una pequeña parte de las direcciones creativas posibles. Tu entrega incluye 15 ideas de sesiones creadas a partir de tus selfies actuales y tus respuestas.",
        generatedLabel: "Generado con UnrealShot",
        exploreExample: "Explorar este ejemplo →",
        requirementsHeading: "Requisitos actuales de fotos en " + appName,
        primarySources: "Fuentes oficiales",
        sourcesChecked: "Comprobadas el",
        faqHeading: "Preguntas sobre UnrealShot para " + appName,
        ctaEyebrow: "39 $ una sola vez · sin suscripción",
        ctaHeading: "Recibe 15 sesiones completas en una entrega",
        ctaDescription: "Sube 4–6 selfies actuales y recibe 60 fotos para citas en menos de 30 minutos. Tus referencias guían el parecido e incluye 15 repeticiones individuales.",
      },
      guide: {
        home: "Inicio",
        guides: "Guías",
        writtenReviewed: "Escrito y revisado por",
        atAGlance: "en resumen",
        inThisGuide: "En esta guía",
        productDetails: "Ver detalles del producto →",
        checklistHeading: "Checklist final para tus fotos de " + appName,
        faqHeading: "Preguntas frecuentes",
        officialSources: "Fuentes oficiales",
        sourceDescription: "Las reglas de las plataformas cambian. Estas fuentes oficiales se comprobaron el",
        ctaHeading: "¿Te faltan los papeles que describe esta guía?",
        ctaDescription: "UnrealShot crea 15 sesiones coherentes y 60 fotos a partir de 4–6 selfies, con 15 repeticiones individuales y entrega en menos de 30 minutos.",
      },
    }
  }

  if (locale === "de") {
    return {
      landing: {
        home: "Startseite",
        datingPhotos: "Dating-Fotos",
        createPhotos: "Meine " + appName + "-Fotos erstellen",
        seeExamples: "Beispiele ansehen",
        sampleCaption: "Mit UnrealShot erstellte Beispiel-Datingfotos",
        profileProblem: "Das Profilproblem",
        profileProblemHeading: "Warum eine volle Fotogalerie dein " + appName + "-Profil trotzdem unfertig lassen kann",
        solution: "Die UnrealShot-Lösung",
        solutionHeading: "Von wenigen aktuellen Selfies zu einer vollständigen Dating-Fotoauswahl",
        deliveryEyebrow: "So entsteht deine Lieferung",
        deliveryHeading: "Verschiedene Shooting-Ideen. Eine erkennbare Version von dir.",
        builtFor: "Für " + appName + "-Profile entwickelt",
        builtHeading: "Wie UnrealShot aus wenigen Selfies ein vollständigeres " + appName + "-Profil macht",
        examplesHeading: "Weitere UnrealShot-Beispiele für Datingfotos",
        examplesDescription: "Diese Beispiele zeigen nur einen kleinen Ausschnitt der möglichen kreativen Richtungen. Deine Lieferung enthält 15 Shooting-Ideen aus deinen aktuellen Selfies und Antworten.",
        generatedLabel: "Mit UnrealShot erstellt",
        exploreExample: "Beispiel ansehen →",
        requirementsHeading: "Aktuelle Fotoregeln für " + appName,
        primarySources: "Offizielle Quellen",
        sourcesChecked: "Geprüft am",
        faqHeading: "Fragen zu UnrealShot für " + appName,
        ctaEyebrow: "39 $ einmalig · kein Abo",
        ctaHeading: "Erhalte 15 vollständige Shootings in einer Lieferung",
        ctaDescription: "Lade 4–6 aktuelle Selfies hoch und erhalte innerhalb von 30 Minuten 60 Datingfotos. Deine Referenzen steuern die Ähnlichkeit; 15 einzelne Neuanfertigungen sind enthalten.",
      },
      guide: {
        home: "Startseite",
        guides: "Guides",
        writtenReviewed: "Geschrieben und geprüft von",
        atAGlance: "auf einen Blick",
        inThisGuide: "In diesem Guide",
        productDetails: "Produktdetails ansehen →",
        checklistHeading: "Die finale " + appName + "-Foto-Checkliste",
        faqHeading: "Häufige Fragen",
        officialSources: "Offizielle Quellen",
        sourceDescription: "Plattformregeln ändern sich. Diese offiziellen Quellen wurden am",
        ctaHeading: "Fehlen dir die im Guide beschriebenen Fotomotive?",
        ctaDescription: "UnrealShot erstellt aus 4–6 Selfies 15 stimmige Shootings und 60 Fotos – inklusive 15 einzelner Neuanfertigungen und Lieferung innerhalb von 30 Minuten.",
      },
    }
  }

  if (locale === "pt-BR") {
    return {
      landing: {
        home: "Início",
        datingPhotos: "Fotos para namoro",
        createPhotos: "Criar minhas fotos para " + appName,
        seeExamples: "Ver exemplos",
        sampleCaption: "Exemplos de fotos para namoro geradas com a UnrealShot",
        profileProblem: "O problema do perfil",
        profileProblemHeading: "Por que um rolo cheio de fotos ainda pode deixar seu perfil do " + appName + " incompleto",
        solution: "A solução da UnrealShot",
        solutionHeading: "De alguns selfies atuais a uma seleção completa de fotos para namoro",
        deliveryEyebrow: "Como sua entrega é criada",
        deliveryHeading: "Ideias de ensaio diferentes. Uma única versão reconhecível de você.",
        builtFor: "Feito para perfis do " + appName,
        builtHeading: "Como a UnrealShot transforma poucos selfies em um perfil do " + appName + " mais completo",
        examplesHeading: "Veja mais exemplos de fotos para namoro da UnrealShot",
        examplesDescription: "Estes exemplos mostram apenas uma pequena parte das direções criativas possíveis. Sua entrega inclui 15 ideias de ensaio criadas a partir dos seus selfies atuais e das suas respostas.",
        generatedLabel: "Gerado com a UnrealShot",
        exploreExample: "Explorar este exemplo →",
        requirementsHeading: "Requisitos atuais de fotos do " + appName,
        primarySources: "Fontes oficiais",
        sourcesChecked: "Conferidas em",
        faqHeading: "Perguntas sobre a UnrealShot para " + appName,
        ctaEyebrow: "US$ 39 uma única vez · sem assinatura",
        ctaHeading: "Receba 15 ensaios completos em uma entrega",
        ctaDescription: "Envie 4–6 selfies atuais e receba 60 fotos para namoro em até 30 minutos. Suas referências orientam a semelhança e você recebe 15 refações individuais.",
      },
      guide: {
        home: "Início",
        guides: "Guias",
        writtenReviewed: "Escrito e revisado por",
        atAGlance: "visão rápida",
        inThisGuide: "Neste guia",
        productDetails: "Ver detalhes do produto →",
        checklistHeading: "Checklist final das suas fotos do " + appName,
        faqHeading: "Perguntas frequentes",
        officialSources: "Fontes oficiais",
        sourceDescription: "As regras dos aplicativos mudam. Estas fontes oficiais foram conferidas em",
        ctaHeading: "Faltam as funções de foto descritas neste guia?",
        ctaDescription: "A UnrealShot cria 15 ensaios coerentes e 60 fotos a partir de 4–6 selfies, com 15 refações individuais e entrega em até 30 minutos.",
      },
    }
  }

  return {
    landing: {
      home: "Home",
      datingPhotos: "Dating Photos",
      createPhotos: "Create my " + appName + " photos",
      seeExamples: "See example results",
      sampleCaption: "Sample AI dating photos generated with UnrealShot",
      profileProblem: "The profile problem",
      profileProblemHeading: "Why a camera roll full of photos can still leave your " + appName + " profile unfinished",
      solution: "The UnrealShot solution",
      solutionHeading: "From a few current selfies to a complete set of dating photos",
      deliveryEyebrow: "How your delivery is created",
      deliveryHeading: "Different photoshoot ideas. One recognizable you.",
      builtFor: "Built for " + appName + " profiles",
      builtHeading: "How UnrealShot turns limited selfies into a fuller dating profile",
      examplesHeading: "See more UnrealShot dating photo examples",
      examplesDescription: "These examples show only a small sample of possible creative directions. Your delivery contains 15 photoshoot ideas created from your current selfies and intake.",
      generatedLabel: "AI-generated with UnrealShot",
      exploreExample: "Explore this example →",
      requirementsHeading: "Current " + appName + " photo requirements",
      primarySources: "Primary sources",
      sourcesChecked: "Checked on",
      faqHeading: "Questions about UnrealShot for " + appName,
      ctaEyebrow: "$39 once · no subscription",
      ctaHeading: "Get 15 complete photoshoots in one delivery",
      ctaDescription: "Upload 4–6 current selfies and receive 60 dating photos within 30 minutes. Your references guide likeness across the delivery, and 15 individual Photo Retakes are included.",
    },
    guide: {
      home: "Home",
      guides: "Guides",
      writtenReviewed: "Written and reviewed by",
      atAGlance: "at a glance",
      inThisGuide: "In this guide",
      productDetails: "See product details →",
      checklistHeading: "Final " + appName + " photo checklist",
      faqHeading: "Frequently asked questions",
      officialSources: "Official sources",
      sourceDescription: "Platform guidance changes. These first-party sources were checked on",
      ctaHeading: "Missing the photo roles this guide describes?",
      ctaDescription: "UnrealShot creates 15 coherent shoots and 60 photos from 4–6 selfies, with 15 individual Photo Retakes and delivery within 30 minutes.",
    },
  }
}

export type PlatformPageCopyApp = "Tinder" | "Hinge" | "Bumble"
