import type { PlatformGuideContent, PlatformLandingContent } from "./types"

const hingeSources = [
  { label: "Hinge: How to edit your profile", href: "https://help.hinge.co/hc/en-us/articles/360011053094-How-do-I-edit-my-profile" },
  { label: "Hinge: Adding and editing photos", href: "https://help.hinge.co/hc/en-us/articles/36311675387155-Adding-and-Editing-Photos" },
  { label: "Hinge: Prohibited Content & Behavior", href: "https://help.hinge.co/hc/en-us/articles/42464295207187-Prohibited-Content-Behavior" },
]

export const hingeLanding: PlatformLandingContent = {
  app: "Hinge",
  path: "/dating-photos/hinge",
  eyebrow: "AI Hinge photo product for men",
  title: "AI Hinge photos that give your prompts a believable visual story",
  description: "Create 60 realistic AI Hinge photos across 15 coherent photoshoots from 4–6 selfies. Includes 15 Photo Retakes and delivery within 30 minutes for $39.",
  answer: "UnrealShot creates 15 coherent four-photo shoots for men who want a more complete Hinge profile. Your 4–6 current selfies guide likeness while three intake answers help shape varied creative directions. Each generated idea becomes four connected photos, giving you 60 results plus 15 individual Photo Retakes within 30 minutes for $39 once.",
  reviewed: "August 31, 2026",
  heroBullets: ["15 varied ideas with four related frames each", "Truthful intake guides the creative direction", "60 photos plus 15 Photo Retakes", "Delivered within 30 minutes · $39 once"],
  problemIntro: "Hinge places photos and written prompts inside the same profile, so the images need to feel like they belong to the person behind the answers. Repeated selfies, outdated photos and disconnected AI images leave the profile with little visual personality or continuity.",
  problems: [
    { title: "Your photos add little to your prompts", body: "When every image is another close portrait, the visual side of the profile cannot support the personality, routine and interests described in your written answers." },
    { title: "The available photos come from different versions of you", body: "Changes in age, hair, facial hair, body and image quality can make a real camera roll feel inconsistent. Current references give the new delivery one recognizable starting point." },
    { title: "Separate AI images do not feel like one person’s life", body: "Unrelated one-off generations can shift identity and visual style from image to image. UnrealShot creates complete four-photo shoots and carries your reference likeness across the full delivery." },
  ],
  solutionIntro: "UnrealShot turns a small set of current selfies into a broad pool of Hinge-ready dating photos. Your delivery includes 15 different photoshoot ideas with visual variety, while four connected photos from every idea keep each setting believable and give you natural alternatives from the same moment.",
  differentiators: [
    { title: "Your real interests can shape many directions", body: "Truthful intake answers give the generation meaningful context. A genuine interest can inspire different settings, actions, clothing and moods instead of being tied to one predetermined image." },
    { title: "One photoshoot becomes four connected photos", body: "The environment, clothing and light stay consistent within a generated idea while changes in framing, posture and expression create natural alternatives from the same moment." },
    { title: "Fifteen ideas give the profile visual breadth", body: "The delivery can move across everyday, active, relaxed and more polished visual directions without being limited to the examples currently shown on the site." },
    { title: "Individual Photo Retakes are built in", body: "Your package includes 15 Photo Retakes for photos where the central idea works but you want another version of the likeness, expression or composition." },
  ],
  deliveryPoints: [
    { title: "15 photoshoot ideas created for your delivery", body: "Your delivery explores different environments, styling, activity, light and mood. The possible creative direction extends beyond the example concepts displayed on the site." },
    { title: "Four connected photos from every idea", body: "Each photoshoot creates four variations of one visual moment. Consistent surroundings and styling make the photos feel naturally related while composition and expression change." },
    { title: "Current likeness across all 60 photos", body: "Your recent selfies guide the full generation, helping different photoshoot ideas retain the recognizable appearance needed for one coherent Hinge profile." },
  ],
  sections: [
    { heading: "Photos that give your Hinge prompts more to work with", paragraphs: ["A useful Hinge photo can carry one truthful detail about your personality, routine or interests. Your intake gives UnrealShot context for generating varied ideas that feel connected to the person described in your prompts.", "One genuine interest can inspire many possible environments, actions, clothing choices, moods and camera treatments, allowing the creative direction to stay personal without becoming repetitive."] },
    { heading: "Four connected photos make each idea feel complete", paragraphs: ["Every generated idea is developed as a short photoshoot rather than a single isolated image. The surroundings, styling and light stay consistent, while the four photos capture useful differences in composition, posture and expression.", "That coherence is visible before you compare the idea with the rest of your delivery. You receive a group of photos that belong together, plus enough different ideas to build variety across the complete profile."] },
    { heading: "Keep every generated photo grounded in you", paragraphs: ["Your current selfies guide recognizable likeness while truthful intake answers influence the creative direction. Across 15 generated ideas, UnrealShot varies environment, styling, action, composition and expression while keeping you at the center of the delivery.", "The included Photo Retakes give you another version of an otherwise strong photo when an important detail, expression or composition needs another pass."] },
    { heading: "The complete UnrealShot delivery", paragraphs: ["Upload 4–6 current solo selfies and answer three short questions about the look and real interests that fit you. Those references and answers guide the likeness and creative direction across 15 different photoshoot ideas.", "Within 30 minutes, you receive 60 photos—four connected results from every idea—plus 15 individual Photo Retakes. The price is $39 once with no subscription."], bullets: ["4–6 current references", "15 generated photoshoots", "Four connected photos per shoot", "Intake-guided creative direction", "15 individual Photo Retakes", "$39 one-time payment"] },
  ],
  exampleSlugs: ["home-cooking", "outdoor-coffee", "coastal-travel", "dinner"],
  policy: [
    "Hinge says members need between four and six photos depending on local requirements, together with three prompt answers.",
    "Hinge’s prohibited-content guidance bars misrepresentation, including posting another person’s photo or likeness, and prohibits AI-generated content used to deceive or mislead.",
    "Use generated frames only when they accurately represent your current appearance and real interests, consistent with Hinge’s rules against deceptive or misleading content.",
  ],
  sources: hingeSources,
  faqs: [
    { question: "What are AI Hinge photos?", answer: "They are generated dating photos based on your current reference selfies and intake. UnrealShot creates them as complete four-photo shoots, giving your Hinge profile varied moments that still look connected to the same person." },
    { question: "How are my Hinge photoshoot ideas created?", answer: "Your current selfies and three intake answers guide the delivery. UnrealShot creates 15 different photoshoot ideas from that context, and the examples on this site show previous outputs rather than the limits of what can be generated." },
    { question: "How many photos does a Hinge profile require?", answer: "Hinge’s current help material says members need between four and six photos depending on local requirements, along with three prompt answers. Check the app and official help center for your region." },
    { question: "How can UnrealShot photos work with my Hinge prompts?", answer: "Truthful interests and style information in your intake can influence the generated environments and activities. The resulting photos can give your prompts visual context while still representing details that genuinely fit your life." },
    { question: "How does UnrealShot create enough variety for a Hinge profile?", answer: "The delivery contains 15 generated ideas with four related frames from each. Settings, wardrobe, activity, composition and expression vary across the delivery while each individual shoot stays visually coherent." },
    { question: "Are AI photos allowed on Hinge?", answer: "Hinge prohibits AI-generated content used to deceive or mislead. Use only accurate images, represent your interests truthfully and review Hinge’s current rules before publishing." },
    { question: "Can I improve an individual Hinge photo?", answer: "Yes. The package includes 15 individual Photo Retakes for photos where you want another version of the likeness, expression or composition." },
  ],
  guidePath: "/guides/hinge-photos",
  guideLabel: "Read the complete Hinge photo guide",
}

export const hingeGuide: PlatformGuideContent = {
  app: "Hinge",
  path: "/guides/hinge-photos",
  eyebrow: "Hinge photo guide for men",
  title: "Hinge photos for men: build a profile people can respond to",
  description: "A detailed Hinge photo guide covering four-to-six-photo lineups, prompt alignment, photo roles, captions, AI-image boundaries and current Hinge rules.",
  answer: "Build a Hinge lineup by giving each available photo a different job: identify you clearly, show your full appearance, reveal a real interest, add a relaxed expression and provide another believable part of your life. Written prompts should add context to those images rather than contradict them. Hinge currently requires four to six photos depending on local requirements, so repeated portraits waste meaningful space.",
  reviewed: "August 31, 2026",
  quickFacts: [["Current requirement", "4–6 photos by region"], ["Written profile", "3 prompt answers"], ["Strongest connection", "Real activity + truthful prompt"], ["AI boundary", "Never deceptive or misleading"]],
  sections: [
    { heading: "Treat the Hinge profile as one connected story", paragraphs: ["Hinge places photos among written details and prompts, so viewers do not experience the images as a separate gallery. A photo can make a prompt more specific, while a prompt can explain why an ordinary-looking moment matters.", "Start by listing the facts your profile already communicates: work, neighborhood, intentions, routines and real interests. Your images should broaden that picture, not stage a second identity. If the writing says quiet Sundays and the gallery shows only nightlife, the profile creates avoidable uncertainty." ] },
    { heading: "What the first Hinge photo should establish", paragraphs: ["The opener should make you easy to recognize: solo, recent, well lit and close enough for the face to remain clear on a phone. Avoid sunglasses, an aggressive crop or a distant full-body frame as the first point of identification.", "Personality can appear through expression and clothing without loading the opener with props. Save detailed activity scenes for later positions, where the viewer has enough context to understand what they reveal." ] },
    { heading: "How to use four to six photo slots", paragraphs: ["Hinge says members are required to use between four and six photos depending on local requirements. Build a four-photo core first: clear opener, full-length context, genuine activity and relaxed or dressed-up contrast. If five or six slots are available, add a different real-life setting and a current camera-roll anchor.", "Do not fill an extra slot simply because it exists. Two coffee portraits in the same clothes still perform one job. Choose the version with the clearer face or expression and use the remaining space for new information."], bullets: ["1. Solo opener", "2. Full-length everyday image", "3. Real-interest activity", "4. Relaxed expression or social context", "5. Different wardrobe or setting", "6. Recent real-life anchor"] },
    { heading: "Connect activity photos to prompts without repeating yourself", paragraphs: ["A kitchen image plus a prompt that only says ‘I love cooking’ repeats one fact. A stronger pairing lets the image establish cooking and uses the prompt for a specific detail: the dish you are learning, a family recipe or your harmless kitchen controversy.", "The same principle works for running, books, art, photography or travel. Let the image prove the broad category and let the writing provide the response hook. Both must remain true." ] },
    { heading: "Photo prompts and captions need specificity", paragraphs: ["If your version of Hinge offers a photo prompt or caption, use it only when it adds information the frame cannot show. Naming a real place, explaining the moment or inviting a narrow response can help; generic labels such as ‘adventure time’ add little.", "Never use a caption to repair an implausible image. If the photo needs text to explain why your hand, face or environment looks strange, remove it." ] },
    { heading: "Choose candid images that remain readable", paragraphs: ["Candid does not mean blurry, distant or unaware of composition. A useful candid frame has a clear expression and an action that makes sense in the setting. Looking slightly away from the lens can feel relaxed, but the face should remain visible somewhere else in the lineup.", "Balance candids with one direct, straightforward portrait. A profile made entirely of looking-away images can hide the very information the opener needs to establish." ] },
    { heading: "Using AI Hinge photos responsibly", paragraphs: ["AI photos should fill a genuine camera-roll gap, not create a more impressive fictional person. Use recent selfies as references, select only real interests and reject changes to face, age, body, hair or identity-defining details.", "Hinge explicitly prohibits AI-generated content used to deceive or mislead. Keep recent real photos in the profile, avoid false locations or activities and do not assume any generated frame will pass moderation or verification." ] },
    { heading: "Common Hinge photo problems", paragraphs: ["Repeated headshots are the obvious issue, but contradiction is equally damaging: radically different facial hair across adjacent photos, prompts unsupported by the gallery, several old appearances or every image looking like professional branding.", "Audit by role and truth. Write one sentence describing what each photo contributes. If the sentence is the same twice, remove one. Then ask whether every visible interest and setting could be discussed honestly."], bullets: ["No current solo opener", "Prompt and activity contradictions", "Several portraits with the same crop", "No full-length photo", "Old or inconsistent appearance", "Invented lifestyle scenes", "Every image over-polished"] },
    { heading: "Check facial and wardrobe continuity across the whole profile", paragraphs: ["People change hair, facial hair and clothing over time, so perfect sameness is neither possible nor desirable. The set should still read as one current person. Compare jaw shape, hairline, eye spacing, facial-hair pattern, age and body proportions across adjacent photos rather than reviewing each frame alone.", "Wardrobe needs variety without becoming costume changes. One casual layer, one active outfit and one smart-casual look can show range. Several luxury outfits or radically different personal styles may communicate a persona your prompts and real camera-roll photos do not support."] },
    { heading: "Retake the frame or replace the role?", paragraphs: ["Use a retake when the role and scene are right but one controllable detail is wrong: likeness, expression, hand position or crop. Replace the entire role when the underlying idea is false, repetitive or irrelevant to your profile. Retaking an invented hobby more cleanly does not make it a truthful choice.", "Keep a simple selection note for each slot: the job, the real fact it shows and the reason it belongs next to the surrounding prompt. This prevents visual polish from overruling accuracy during the final review."] },
    { heading: "Final profile review", paragraphs: ["Preview the profile in its actual sequence, including prompts. Check whether the first two items establish appearance and tone, whether the middle creates conversation material and whether the final items add something new.", "Ask one trusted person a narrow question: ‘Which photo looks least like me today?’ That is more useful than asking which image is best. Remove inaccurate frames even when they are flattering." ] },
  ],
  checklist: ["My opener is solo, recent and recognizable", "My available slots perform different roles", "I include a clear full-length image", "An activity connects to a real prompt or detail", "My prompts add context instead of repeating captions", "No scene invents a hobby, trip or lifestyle", "Facial hair, age and build remain consistent", "At least one current camera-roll photo anchors the set", "Every image remains readable at phone size", "I reviewed Hinge’s current content rules"],
  sources: hingeSources,
  faqs: [
    { question: "How many photos do you need on Hinge?", answer: "Hinge currently says members need between four and six photos depending on local requirements, together with three prompt answers." },
    { question: "What should the first Hinge photo be?", answer: "Use a recent solo close or chest-up image with visible eyes, natural light and a recognizable current appearance." },
    { question: "Should Hinge photos match your prompts?", answer: "They should support the same truthful profile, but they do not need to repeat each other. Let an activity image establish the broad fact and use the prompt to add a specific story or response hook." },
    { question: "Can you use AI photos on Hinge?", answer: "Hinge prohibits AI-generated content used to deceive or mislead. Use only accurate frames, keep real recent photos and consult Hinge’s current rules." },
    { question: "Are professional-looking photos bad for Hinge?", answer: "One polished photo can add range. A complete profile made only of studio-like portraits can feel less informative than a mix of ordinary, active and candid settings." },
  ],
  productPath: "/dating-photos/hinge",
  productLabel: "Create coherent AI Hinge photo shoots",
}
