import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, ShieldCheck } from "lucide-react"
import { datingShoots, type DatingShoot } from "@/lib/dating-shoot-content"
import type { ShootLandingCopy, ShootLandingFaq } from "@/lib/dating-shoot-landing-content"

export const commonShootFaqs: ShootLandingFaq[] = [
  { question: "Can I select this exact scene for my order?", answer: "No. This page demonstrates one possible creative direction and the four-frame structure. It is not a selectable preset or guaranteed result. Your $39 delivery contains 15 varied shoots and 60 photos generated from your references and intake." },
  { question: "What if one photo does not look enough like me?", answer: "Reference-guided generation can miss an individual likeness or composition. The package includes 15 individual Photo Retakes so you can retry specific weak frames." },
  { question: "How quickly are the dating photos delivered?", answer: "The complete package is delivered within 30 minutes after you finish the reference upload and intake process." },
]

export default function ShootConversionSections({ shoot, copy }: { shoot: DatingShoot; copy: ShootLandingCopy }) {
  const related = datingShoots.filter((item) => item.slug !== shoot.slug).slice(0, 3)
  const faqs = [...copy.faqs, ...commonShootFaqs]

  return (
    <>
      <section className="bg-[#111111] py-20 text-white sm:py-24">
        <div className="mx-auto max-w-7xl px-5">
          <div className="grid gap-8 rounded-3xl border-2 border-dashed border-zinc-800 bg-[#161616] p-3 lg:grid-cols-2">
            <div className="rounded-2xl border border-dashed border-zinc-700/70 bg-[#1c1c1c] p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">Designed as one believable scene</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">The details stay related while the camera position changes</h2><p className="mt-5 text-lg leading-8 text-zinc-300">Four frames should feel like one short session. UnrealShot preserves the visual story instead of changing the setting, wardrobe and light every time.</p><dl className="mt-8 grid gap-4 sm:grid-cols-2">{[["Setting", shoot.location], ["Clothing", shoot.clothing], ["Light", shoot.lighting], ["Natural action", shoot.action]].map(([label, value]) => <div key={label} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><dt className="text-xs font-black uppercase tracking-wide text-[#ff6f00]">{label}</dt><dd className="mt-2 text-sm leading-6 text-zinc-300">{value}</dd></div>)}</dl></div>
            <div className="flex flex-col justify-between rounded-2xl border border-dashed border-zinc-800 bg-black p-7 sm:p-10"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">Use generated results honestly</p><h3 className="mt-3 text-3xl font-black">Keep only ideas that belong in your life</h3><p className="mt-5 text-lg leading-8 text-zinc-300">{copy.selectionNote}</p><div className="mt-7 space-y-3">{["Use recent solo selfies as references", "Answer the intake with truthful interests and preferences", "Reject frames that change your current appearance", "Mix selected AI photos with recent camera-roll photos"].map((item) => <div key={item} className="flex gap-3 text-sm text-zinc-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#ff6f00]" />{item}</div>)}</div></div><Link href="/realistic-ai-dating-photos" className="mt-8 inline-flex items-center gap-2 font-bold text-[#ff6f00]">How UnrealShot approaches realism <ArrowRight className="h-4 w-4" /></Link></div>
          </div>
        </div>
      </section>

      <section className="bg-white py-20 sm:py-24">
        <div className="mx-auto max-w-7xl px-5"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">From selfies to finished photos</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">No photographer, scheduling or location setup</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-zinc-600">Complete one short intake from home. UnrealShot uses your references and real-interest choices to build a varied dating-photo delivery.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[
          { number: "01", title: "Upload 4–6 current selfies", body: "Use clear solo photos from different angles so your current face, hair and facial hair are visible." },
          { number: "02", title: "Tell us what genuinely fits your life", body: "Your answers guide the creative direction. UnrealShot generates the final shoot ideas rather than asking you to select exact scenes by name." },
          { number: "03", title: "Receive your complete lineup", body: "Get 15 different shoots, 60 photos and 15 individual Photo Retakes within 30 minutes." },
        ].map((step) => <article key={step.number} className="rounded-3xl border border-zinc-200 bg-[#f7f5f3] p-7"><span className="font-mono text-sm font-black text-[#ff6f00]">{step.number}</span><h3 className="mt-4 text-xl font-black">{step.title}</h3><p className="mt-3 leading-7 text-zinc-600">{step.body}</p></article>)}</div></div>
      </section>

      <section className="bg-[#111111] px-5 py-20 text-white sm:py-24">
        <div className="mx-auto max-w-6xl rounded-3xl border-2 border-dashed border-zinc-800 bg-[#161616] p-3 shadow-2xl"><div className="grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-dashed border-zinc-700/70 bg-[#1c1c1c] p-7 sm:p-10"><span className="rounded-full bg-[#ff6f00]/15 px-3 py-1 text-xs font-black uppercase tracking-wide text-[#ff6f00]">Complete dating photo package</span><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">This scene shows how one part of a varied delivery works</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-300">You do not purchase one scene in isolation. Scenes like this can appear when they match your intake, alongside different indoor, outdoor, activity, casual and dressed-up options for a complete profile.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{["15 different photo shoots", "Four related frames per shoot", "60 photos in total", "15 individual Photo Retakes", "Delivered within 30 minutes", "No subscription"].map((item) => <div key={item} className="flex gap-3 text-sm font-semibold text-zinc-200"><Check className="h-4 w-4 shrink-0 text-[#ff6f00]" />{item}</div>)}</div></div><div className="flex flex-col justify-between rounded-2xl border border-dashed border-zinc-800 bg-black p-7 text-center sm:p-10"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">One-time payment</p><p className="mt-4 text-6xl font-black tracking-tighter">$39</p><p className="mt-2 text-zinc-400">Complete package · no recurring charge</p><div className="mx-auto my-7 grid max-w-sm grid-cols-4 gap-2">{shoot.frames.map((frame) => <div key={frame.role} className="relative aspect-[3/4] overflow-hidden rounded-lg border border-zinc-700"><Image src={frame.src} alt="" fill sizes="80px" className="object-cover" /></div>)}</div></div><div><Link href="/dashboard" className="flex w-full items-center justify-center gap-2 rounded-md bg-[#ff6f00] px-6 py-4 font-bold text-white transition hover:bg-[#e96500]">Start my dating shoot <ArrowRight className="h-4 w-4" /></Link><p className="mt-5 flex items-center justify-center gap-2 text-xs text-zinc-500"><ShieldCheck className="h-4 w-4 text-[#ff6f00]" />Secure checkout · delivery within 30 minutes</p></div></div></div></div>
      </section>

      <section className="bg-[#f7f5f3] py-20 sm:py-24">
        <div className="mx-auto max-w-7xl px-5"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">More illustrative outputs</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">See other possible creative directions</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-zinc-600">These examples demonstrate range; they are not a menu of scenes included by name or available for exact selection.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{related.map((item) => <Link key={item.slug} href={`/dating-photos/shoots/${item.slug}`} className="group overflow-hidden rounded-3xl border border-zinc-200 bg-white"><div className="relative aspect-[4/3]"><Image src={item.frames[0].src} alt={item.frames[0].alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-300 group-hover:scale-[1.02]" /></div><div className="p-6"><p className="text-xs font-black uppercase tracking-wide text-[#ff6f00]">Illustrative AI-generated output</p><h3 className="mt-2 text-2xl font-black">{item.name} example</h3><p className="mt-3 line-clamp-3 leading-7 text-zinc-600">{item.answer}</p><span className="mt-5 inline-flex items-center gap-2 font-bold text-[#ff6f00]">Explore this example <ArrowRight className="h-4 w-4" /></span></div></Link>)}</div><div className="mt-8 text-center"><Link href="/dating-photos/examples" className="font-bold text-[#ff6f00] underline decoration-2 underline-offset-4">See all illustrative results →</Link></div></div>
      </section>

      <section className="bg-white py-20 sm:py-24">
        <div className="mx-auto max-w-4xl px-5"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">Questions before you start</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">{shoot.name} photo questions</h2></div><div className="mt-10 divide-y divide-zinc-200 border-y border-zinc-200">{faqs.map((faq) => <article key={faq.question} className="py-7"><h3 className="text-xl font-black">{faq.question}</h3><p className="mt-3 leading-7 text-zinc-600">{faq.answer}</p></article>)}</div></div>
      </section>

      <section className="bg-[#111111] px-5 py-20 text-center text-white"><div className="mx-auto max-w-5xl rounded-3xl border-2 border-dashed border-zinc-800 bg-[#161616] p-8 sm:p-14"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff6f00]">Fill the gaps in your camera roll</p><h2 className="mx-auto mt-3 max-w-4xl text-3xl font-black tracking-tight sm:text-6xl">Create a complete dating-photo lineup</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-zinc-300">15 different shoots · 60 photos · 15 Photo Retakes · delivered within 30 minutes · $39 once.</p><Link href="/dashboard" className="mt-8 inline-flex items-center gap-2 rounded-md bg-[#ff6f00] px-8 py-4 font-bold text-white">Create my dating photos <ArrowRight className="h-4 w-4" /></Link></div></section>
    </>
  )
}
