export const COUPLE_REFERENCE_PROMPTS = {
    FLASH: [
        "photo of us standing on a concrete sidewalk at night against a brick wall. harsh direct on-camera flash lighting creates a hard shadow outline right behind us. background is pitch black except for one distant street lamp bokeh. We are subtly laughing head thrown back slightly hair messy and wild frozen in mid-motion by the flash. skin appears very little shiny/oily from the flash reflection especially on forehead and cheekbones. Both are wearing a black leather jacket, woman over a slip dress, and and man over a t-shirt. strap of a crossbody bag cutting across her chest. photo has high contrast \"disposable camera\" aesthetic slight very low opacity red-eye effect vignette and cool tone. Keep our faces and body type exactly consistent from reference photos of us.",
        "raw flash photograph of a couple sitting closely together on a dark wooden park bench at night. They are both looking down at a smartphone he is holding between them. The cool blue light from the phone screen illuminates their faces from below, clashing with the harsh white direct camera flash from the front. This mixed lighting highlights the natural textures of their skin and the reflection in their eyes. She (keep her facial identity exactly consistent from reference photos) is smiling softly at the screen, her shoulder touching his. He (keep his facial identity exactly consistent from reference photos) is holding the phone, grinning. The background is pitch black park darkness with vague tree shapes.",
        "Vertical snapshot taken under a glass bus stop shelter at night. It is cold outside. He (keep his facial identity exactly consistent from reference photos) has his arm around her, pulling her close for warmth. He is looking at the camera with a tired, gentle smile. She (keep her facial identity exactly consistent from reference photos) has her head resting on his shoulder, eyes half-closed, looking sleepy and content. The direct camera flash reflects slightly off the glass behind them and highlights their naturally flushed cheeks from the cold air. Skin texture is raw and unretouched. They are both wearing thick winter jackets. Background is the dark street and rain-streaked glass.",
        "A raw, direct flash photograph taken inside a parked car at night, viewing them from the front windshield. They are eating burgers from a drive-thru. Half body shot. She (keep her facial identity exactly consistent from reference photos) is holding a burger with both hands, taking a bite, looking at him with a playful side-eye. She is wearing a vintage white band t-shirt with a red flannel shirt unbuttoned over it. He (keep his facial identity exactly consistent from reference photos) is sitting in the driver's seat, wiping his mouth with a napkin, laughing at her. The car's interior dome light is on, mixing with the camera flash to create sharp shadows and highlighting the oily sheen on their faces from the food. Background is the dark car interior and blurred streetlights outside.",
        "a couple standing on a windy rooftop overlook at night. She (keep her facial identity exactly consistent from reference photos) is leaning against the railing, hair blowing wildly across her face, smiling broadly at the camera. She is wearing a fitted black turtleneck tucked into high-waisted jeans. He (keep his facial identity exactly consistent from reference photos) is standing behind her, wrapping his arms around her waist, resting his chin on her shoulder, looking at the camera with a calm smile. The direct flash freezes the motion of her hair and illuminates their faces against a pitch-black sky with distant city bokeh. Skin texture is detailed, showing windburn and natural pores. He is wearing a beige knit sweater.",
        "snapshot-style flash photo of a couple walking out of a late-night cinema. Half body shot. She (keep her facial identity exactly consistent from reference photos) is laughing, covering her face with a popcorn bucket, peeking out from behind it. She is wearing a silk slip dress with a heavy leather biker jacket draped over her shoulders. He (keep his facial identity exactly consistent from reference photos) is walking next to her, looking at her with an amused expression, hands in his pockets. The flash is harsh, reflecting off the leather jacket and creating a \"red-eye\" aesthetic. Background is the bright neon marquee lights of the cinema and the dark sidewalk. Skin texture is shiny and realistic. He is wearing a simple white t-shirt and dark jeans."
    ],

    GOLDEN: [
        "Golden hour couple portrait walking hand-in-hand through a sunflower field. The warm backlight creates rim lighting around both their silhouettes. She's looking up at him smiling, he's looking down at her. Dreamy, romantic, sun-drenched.",
        "Candid couple shot at an outdoor cafe during sunset. Sitting across from each other, holding coffee cups, deep in conversation. Dappled golden light through the trees creates patterns on their faces. Natural and intimate.",
        "Beach sunset portrait of a couple sitting on the sand, watching the waves. She's leaning on his shoulder, both in profile. The golden sun creates long shadows and warm skin tones. Hair blowing in the ocean breeze.",
        "Vertical candid shot taken from the back seat of a convertible car driving on a highway during the day. She (keep her facial identity exactly consistent from reference photos) is in the passenger seat, turning around to smile at the camera, hair messy from the wind. She wears sunglasses on her head and a white ribbed tank top. He (keep his facial identity exactly consistent from reference photos) is driving, one hand on the wheel, wearing a grey t-shirt, looking at the road but smiling. Sunlight hits them hard from above, showing skin pores, natural flush, and windburn. Background is blurred highway and blue sky.",
        "A nostalgic, sun-drenched shot of a couple sitting on the hood of a car at golden hour. She (keep her facial identity exactly consistent from reference photos) is sitting cross-legged, holding a glass bottle of soda, squinting into the sun with a grin. She wears high-waisted denim shorts and a vintage tee. He (keep his facial identity exactly consistent from reference photos) is leaning back on his hands next to her, laughing, wearing sunglasses and a white shirt. The image has warm tones, fine grain, and a slightly soft focus typical of analog photography. Shot on 35mm film stock Kodak Portra 400"
    ],

    GRITTY: [
        "A hyper-realistic action shot of a couple running across a street crosswalk in bright afternoon sunlight. They are holding hands, mid-stride, laughing. She (keep her facial identity exactly consistent from reference photos) is looking back at him, hair flying in the air. She wears a white summer dress and sneakers. He (keep his facial identity exactly consistent from reference photos) is pulling her gently forward, smiling, wearing a beige linen shirt and shorts. The lighting is high-contrast, casting sharp shadows on the asphalt. Skin texture is razor sharp, showing sweat and movement. Shot on Canon EOS R5, 50mm lens, shutter speed 1/1000 to freeze motion perfectly.",
        "Black and white candid of a couple at a dive bar. Sitting at the counter, beers in hand, looking at each other with knowing smiles. Harsh overhead light, visible grain, authentic urban atmosphere.",
        "Documentary-style shot of a couple waiting at a bus stop in the rain. She's in his arms trying to stay warm. Cold breath visible, wet hair, real emotion on their faces. Raw, unposed.",
        "Late night metro station couple shot. Standing on the platform, his forehead against hers, intimate moment in public space. Fluorescent lighting, high contrast, urban grit.",
        "Street flash portrait of a couple outside a music venue. Ears still ringing, concert wristbands visible. Sweaty, happy, leaning on each other. Raw flash against dark street background."
    ],

    CINE: [
        "A raw, eye-level shot of a couple lying on the grass in a park on a sunny afternoon. She (keep her facial identity exactly consistent from reference photos) is lying on her back, shielding her eyes from the sun with one hand, laughing. She wears a casual pastel yellow t-shirt and denim shorts. He (keep his facial identity exactly consistent from reference photos) is leaning over her slightly, propped up on one elbow, looking down at her. Dappled sunlight filters through tree leaves, creating complex light patterns on their faces. Skin texture is natural and unretouched. Background is green grass and scattered daisy flowers.",
        "Rainy window reflection shot of a couple in a high-rise apartment. Both silhouettes visible against city lights, his arm around her waist. Moody, atmospheric, intimate.",
        "Neon-lit couple portrait in a Tokyo alleyway. Pink and blue lights reflecting off wet pavement. She's pulling him by the hand, looking back with a smile. Cinematic color grading.",
        "Vertical romantic portrait of a couple standing in an alleyway with soft, diffused daylight bouncing off brick walls. He (keep his facial identity exactly consistent from reference photos) has his back against the wall, looking down at her with a soft smile. She (keep her facial identity exactly consistent from reference photos) is standing close, facing him, looking up into his eyes. Her skin texture is extremely detailed, showing individual pores and eyelashes. No makeup. She wears a simple grey tank top. He wears a black t-shirt. The background is creamy and blurred due to depth of field. Shot on Sony A7R IV, 85mm GM lens, f/1.8 for shallow depth of field.",
        "candid street photography shot of a couple leaning against a railing overlooking a city river. It is a cloudy, bright day. She (keep her facial identity exactly consistent from reference photos) is pointing at something in the distance, mouth open in excitement. She wears a trench coat over a dress. He (keep his facial identity exactly consistent from reference photos) is looking at her face instead of the view, smiling affectionately. The lighting is flat and realistic, highlighting natural skin tones without harsh shadows. Shot on Fujifilm X-T4, 35mm lens, f/2.8, Classic Chrome simulation"
    ],

  PROFESSIONAL: [
        "Highly detailed photo of us standing in a modern office environment next to a glass conference table. Natural daylight from a large window mixes with soft overhead fluorescent lighting, creating realistic, unretouched skin textures with visible pores and a slight natural shine on the forehead. We are standing side-by-side with a comfortable, professional distance between us, not touching. Both are wearing sharp, gender-neutral business casual attire, like blazers over crisp shirts. We are looking directly at the lens with confident, approachable smiles. The background is a slightly blurred, clean corporate workspace. The photo has a high-end digital camera aesthetic with perfect edge sharpness. Keep our faces and body types exactly consistent from reference photos of us. Strictly professional, no romantic tension.",
        "Candid street-style photograph of us walking down a busy financial district sidewalk during overcast daylight. We are walking side-by-side, maintaining a clear platonic space between us, deep in a collaborative conversation. The flat, overcast natural light provides even illumination, highlighting raw, realistic facial features, subtle fine lines, and natural skin tones without harsh shadows. Both are wearing tailored wool winter coats over office wear. One of us is gesturing mid-sentence, while the other is looking at them, listening actively. The camera uses a medium telephoto lens to compress the background, showing softly blurred city architecture. Keep our faces and body types exactly consistent from reference photos of us. Dynamic, professional business partner energy.",
        "High-end studio portrait of us standing against a seamless neutral grey paper backdrop. We are positioned shoulder-to-shoulder but not touching, angled slightly toward the center. The lighting is a classic clam-shell setup with a prominent catchlight in our eyes, revealing hyper-realistic skin details, subtle fine lines, and natural blemishes, completely avoiding any smoothed or filtered look. Both are dressed in minimalist dark blazers over plain t-shirts. We wear warm, professional smiles directed at the camera. The image has a crisp, medium-format digital camera aesthetic with perfect edge sharpness and a very subtle film grain. Keep our faces and body types exactly consistent from reference photos of us.",
        "Eye-level environmental portrait of us sitting at a minimalist wooden desk in a bright co-working space. We are seated in separate ergonomic office chairs, looking together at a single open laptop angled between us. Soft, directional window light spills from the left, casting natural, soft-edged shadows across our faces and emphasizing the realistic texture of our skin and clothing. Both wear smart-casual tech-industry attire. One of us has a hand on the keyboard, the other is holding a coffee mug, leaning in slightly to view the screen but strictly maintaining personal space. The background features out-of-focus indoor plants and acoustic panels. Keep our faces and body types exactly consistent from reference photos of us.",
        "Architectural lifestyle photograph of us sitting on wide concrete city steps during golden hour. We are sitting a foot apart on the same step, casually reviewing a printed document together. The low-angle sunlight hits us from the side, creating dynamic, long shadows and highlighting the raw, unretouched texture of our faces and the heavy fabric of our coats. We are sharing a lighthearted, platonic laugh over a work detail. The camera angle is slightly below eye level, giving an authoritative yet approachable presence. Background is composed of crisp, structural concrete lines and glass building facades out of focus. Keep our faces and body types exactly consistent from reference photos of us."
    ]
};
