import { buildLocalizedShootCopy, registerShootLocalePack, type ShootCopyVoice, type ShootLocalePack, type ShootPageUiCopy, type ShootTopic } from "./dating-shoot-localized"

const ptBrUi: ShootPageUiCopy = {
  heroBullets: ["15 ideias originais de ensaio", "Quatro fotos conectadas por ideia", "Entrega em até 30 minutos", "$39 uma vez · sem assinatura"],
  createPhotos: "Criar minhas fotos para namoro", seeExamples: "Ver exemplos", heroPanelLabel: "Fotos para namoro criadas com UnrealShot", heroPanelDescription: (name) => `${name} mostra apenas uma parte do que a sua entrega completa pode cobrir.`,
  profileProblem: "O problema do perfil", whatChanges: "O que muda com a UnrealShot", changesHeading: "A sua galeria não decide mais sozinha o que o seu perfil pode mostrar", changeBullets: ["4 a 6 selfies atuais orientam a sua aparência", "As suas respostas acrescentam interesses e preferências reais", "A UnrealShot cria 15 ideias de ensaio variadas", "Cada ideia inclui quatro fotos conectadas"],
  examplesEyebrow: "Exemplos de fotos para namoro com IA", createdLabel: "Criado com UnrealShot", deliveryNoteTitle: "A sua entrega vai muito além das fotos mostradas aqui.", deliveryNoteBody: "A UnrealShot cria 15 ideias originais a partir das suas selfies atuais e das suas respostas, com quatro fotos conectadas para cada ideia.",
  solvesEyebrow: "O que isso resolve", solvesDescription: "A proposta não é acrescentar fotos genéricas. É preencher uma parte fraca ou ausente da sua galeria com uma imagem que revele algo útil sobre você.",
  storyEyebrow: "Uma ideia, quatro fotos conectadas", storyHeading: "A primeira foto apresenta o momento. As três seguintes dão continuidade.", storyDescription: "Cada ideia da UnrealShot desenvolve uma mesma história visual: distância, ação e expressão mudam sem parecer quatro gerações sem relação.", storyFacts: [["Cenário", "O local continua coerente em toda a ideia"], ["Roupa", "O visual permanece conectado"], ["Luz", "O horário e a iluminação continuam naturais"], ["Variedade", "Enquadramento, ação e expressão dão opções"]],
  detailsEyebrow: "Criado a partir de detalhes sobre você", detailsHeading: "Os seus interesses dão um ponto de partida diferente a cada entrega", detailsDescription: "Conte à UnrealShot o que realmente faz parte da sua vida. Isso pode orientar as ideias criadas para o seu pedido.", detailsBullets: ["4 a 6 selfies atuais orientam a sua aparência", "Os seus interesses reais guiam a direção criativa", "As suas preferências acrescentam contexto", "15 ideias variadas criam amplitude no pedido"], detailsLink: "Ver como os interesses influenciam as suas fotos",
  processEyebrow: "Das selfies às fotos prontas", processHeading: "Sem fotógrafo, agenda ou preparação de local", processDescription: "Preencha um questionário curto de casa. A UnrealShot usa as suas referências e os seus interesses reais para criar uma entrega variada.", processSteps: [["Envie 4 a 6 selfies atuais", "Escolha fotos individuais nítidas, feitas de ângulos diferentes, com rosto e cabelo visíveis."], ["Conte o que combina com a sua vida", "Os seus interesses e preferências dão ao sistema contexto para criar ideias pessoais, não genéricas."], ["Receba a sua seleção completa", "Você recebe 15 ensaios, 60 fotos e 15 refações individuais em até 30 minutos."]],
  packageBadge: "Pacote completo de fotos para namoro", packageHeading: "Um pedido entrega uma seleção completa, não uma imagem isolada", packageDescription: "A UnrealShot cria variedade suficiente para mostrar mais de um lado da sua vida: ambientes internos e externos, atividades, momentos casuais, looks arrumados e cenas espontâneas.", packageBullets: ["15 ideias originais de ensaio", "Quatro fotos conectadas por ideia", "60 fotos no total", "15 refações individuais", "Entrega em até 30 minutos", "Sem assinatura"],
  paymentEyebrow: "Pagamento único", paymentPrice: "US$ 39", paymentSubtext: "Pacote completo · sem cobrança recorrente", startCta: "Começar meu ensaio", secureText: "Checkout seguro · entrega em até 30 minutos",
  moreEyebrow: "Outros problemas da galeria que a UnrealShot resolve", moreHeading: "Veja outras formas de criar variedade", moreDescription: "Cada página aborda uma lacuna diferente que muitos homens têm nas próprias fotos. Juntas, elas mostram apenas uma parte do que 15 ideias originais podem cobrir.", relatedLabel: "Fotos para namoro criadas com UnrealShot", exploreRelated: "Explorar este resultado", moreLink: "Ver mais exemplos de fotos para namoro →",
  faqEyebrow: "Dúvidas antes de começar", faqTitle: (name) => `Dúvidas sobre fotos de ${name.toLowerCase()}`, finalEyebrow: "Preencha as lacunas da sua galeria", finalHeading: "Crie uma seleção completa para o seu perfil", finalDescription: "15 ensaios diferentes · 60 fotos · 15 refações · em até 30 minutos · $39 uma vez.", finalCta: "Criar minhas fotos para namoro",
}

const topics: Record<string, ShootTopic> = {
  "gym-training": { name: "Treino na academia", keyword: "academia", interest: "a sua rotina de treino", scene: "um momento entre as séries", action: "recuperando o fôlego e ajustando um aparelho", clothing: "uma roupa esportiva simples", problem: "a selfie no espelho esconde o seu rosto", payoff: "energia e constância", balance: "um café ao ar livre ou um jantar mais arrumado" },
  "outdoor-coffee": { name: "Café ao ar livre", keyword: "café ao ar livre", interest: "o prazer de frequentar cafés", scene: "uma pausa no seu bairro", action: "chegando com um café, sentando e observando o movimento", clothing: "camadas casuais em cores naturais", problem: "um selfie fechado mostra o seu rosto, mas não a leveza de um momento compartilhado", payoff: "uma presença acessível e acolhedora", balance: "uma foto de corpo inteiro na cidade ou uma atividade específica" },
  dinner: { name: "Jantar", keyword: "jantar em restaurante", interest: "seu estilo para sair à noite", scene: "o começo de uma noite no restaurante", action: "se acomodando, trocando um olhar e aproveitando o momento", clothing: "uma camisa escura ou um visual smart casual", problem: "uma foto antiga de casamento não mostra o seu estilo atual", payoff: "um visual bem cuidado sem parecer encenado", balance: "fotos durante o dia, de atividade e ao ar livre" },
  "city-walk": { name: "Passeio pela cidade", keyword: "rua da cidade", interest: "a forma como você vive a cidade", scene: "uma caminhada por uma rua de pedestres", action: "caminhando, parando em uma esquina e reagindo a algo fora do quadro", clothing: "uma jaqueta ou malha que você usaria no dia a dia", problem: "a foto de corpo inteiro fica rígida ou transforma você em um detalhe da paisagem", payoff: "movimento, silhueta clara e estilo cotidiano", balance: "uma foto cozinhando ou treinando" },
  "coastal-travel": { name: "Viagem para o litoral", keyword: "viagem para o litoral", interest: "seu gosto por viajar e estar perto do mar", scene: "um caminho aberto na costa", action: "caminhando, parando diante da vista e reagindo ao vento", clothing: "camadas confortáveis de viagem adequadas ao lugar", problem: "a paisagem ocupa todo o quadro e o seu rosto desaparece", payoff: "curiosidade e ar livre sem virar um ponto no cenário", balance: "uma cena local mais comum, como um café ou a cozinha" },
  "home-cooking": { name: "Cozinhar em casa", keyword: "cozinha de casa", interest: "o prazer de cozinhar em casa", scene: "um preparo simples em uma cozinha vivida", action: "separando ingredientes, conferindo a panela e sorrindo entre uma etapa e outra", clothing: "uma roupa confortável para cozinhar em casa", problem: "uma cozinha perfeita demais e uma pose de chef fazem o interesse parecer inventado", payoff: "calor humano e um assunto concreto para conversar", balance: "um passeio pela cidade ou uma cena noturna" },
  rooftop: { name: "Rooftop", keyword: "rooftop urbano", interest: "seu jeito de aproveitar a cidade", scene: "um terraço acessível no fim da tarde", action: "caminhando pelo terraço, parando por um instante e olhando a paisagem", clothing: "uma jaqueta limpa ou uma sobrecamisa para sair", problem: "a vista da cidade vira uma demonstração de status", payoff: "confiança com uma atmosfera plausível", balance: "um café ao ar livre ou uma cena cozinhando" },
}

const voice: ShootCopyVoice = {
  seo: (t) => [`Fotos para namoro com IA: ${t.name} | UnrealShot`, `Crie fotos realistas para namoro com o tema ${t.name.toLowerCase()}. Receba 15 ensaios variados, 60 fotos e 15 refações individuais por $39.`],
  hero: (t) => [`Fotos para namoro com IA: ${t.name}`, `Mostre ${t.interest}`, `em uma cena que combine com você`, `Uma boa foto sobre ${t.name.toLowerCase()} dá contexto natural ao seu perfil. A UnrealShot transforma selfies atuais e as suas respostas em ideias coerentes, incluindo ${t.scene}: ${t.action}.`],
  pain: (t) => [`Quando ${t.problem}, o seu perfil perde o que deveria mostrar`, `O problema não é o cenário. Ele aparece quando o lugar, o acessório ou a pose precisam contar toda a história no seu lugar.`, [["O contexto parece montado", `Uma imagem útil deve explicar por que você está ali, com uma ação simples como ${t.action}, e não apenas exibir um fundo reconhecível.`], ["A pose toma conta", `Uma postura muito planejada esconde ${t.payoff}, justamente a qualidade que a foto deveria transmitir.`], ["Uma única faceta domina", `Até uma boa ideia perde força quando se repete. Complete-a com ${t.balance}.`]]],
  showcase: (t) => [`${t.name}: um contexto fácil de acreditar`, `Estes exemplos mostram como o tema ${t.name.toLowerCase()} pode dar personalidade ao perfil sem esconder o seu rosto. A UnrealShot pode variar locais, enquadramentos e ações conforme o que realmente combina com você.`],
  benefits: (t) => [`O que uma boa foto sobre ${t.name.toLowerCase()} acrescenta`, [["Um interesse que fica visível", `${t.interest[0].toUpperCase()}${t.interest.slice(1)} deixa de ser uma frase genérica e vira algo que as pessoas conseguem imaginar.`], ["Uma ação que deixa tudo mais natural", `${t.action[0].toUpperCase()}${t.action.slice(1)} dá um propósito espontâneo às mãos, ao olhar e à postura.`], ["Mais equilíbrio na seleção", `A cena acrescenta ${t.payoff}; ${t.balance} cria o contraste necessário no restante das fotos.`]]],
  selection: (t) => `Conte que ${t.interest} realmente faz parte da sua vida. Isso pode orientar algumas ideias para ${t.scene}, sem prender toda a sua entrega a um único cenário. Roupa, luz, enquadramento e ação podem variar e ainda manter o resultado natural.`,
  gallery: (t, index) => [`Foto para namoro gerada por IA: um homem em uma cena de ${t.name.toLowerCase()}, usando ${t.clothing}`, ["O enquadramento próximo mantém o rosto no centro e deixa o local apenas acompanhar.", `Um plano mais aberto torna a ação clara: ${t.action}.`, "A foto de corpo inteiro mostra a roupa e a relação natural com o ambiente.", "Uma expressão captada no momento acrescenta a pequena imperfeição que deixa a cena crível."][index] ?? "Uma variação natural dentro da mesma cena."],
  faqs: (t) => [{ question: `A direção de ${t.name.toLowerCase()} vai substituir todas as minhas outras fotos?`, answer: `Não. ${t.interest[0].toUpperCase()}${t.interest.slice(1)} pode orientar parte da entrega, enquanto as 15 ideias exploram também outros locais, roupas, atividades e climas.` }, { question: `Como evitar que uma foto sobre ${t.name.toLowerCase()} pareça encenada?`, answer: `O local deve fazer sentido para a sua vida e a ação precisa ser simples. A UnrealShot parte de ${t.scene} e das suas selfies atuais para manter aparência e cenário coerentes.` }],
}

const ptBr: ShootLocalePack = { locale: "pt-BR", ui: ptBrUi, topics, commonFaqs: [{ question: "As 15 sessões vêm de uma galeria pequena e fixa?", answer: "Não. A UnrealShot cria 15 ideias variadas a partir das suas selfies de referência e respostas. Os exemplos mostram apenas parte da possibilidade criativa, não um catálogo fechado." }, { question: "E se uma foto não ficar parecida o suficiente comigo?", answer: "A geração guiada por referências pode errar algum detalhe de semelhança ou composição. O pacote inclui 15 refações individuais para refazer as imagens que precisarem." }, { question: "Quando as minhas fotos para namoro serão entregues?", answer: "A entrega completa chega em até 30 minutos depois que você envia as referências e termina o questionário." }], buildCopy: (base, topic) => buildLocalizedShootCopy(base, topic, voice) }

registerShootLocalePack(ptBr)
