import { buildLocalizedShootCopy, registerShootLocalePack, type ShootCopyVoice, type ShootLocalePack, type ShootPageUiCopy, type ShootTopic } from "./dating-shoot-localized"

const deUi: ShootPageUiCopy = {
  heroBullets: ["15 originelle Shooting-Ideen", "Vier zusammenhängende Fotos pro Idee", "Lieferung innerhalb von 30 Minuten", "39 $ einmalig · kein Abo"],
  createPhotos: "Meine Dating-Fotos erstellen", seeExamples: "Beispiele ansehen", heroPanelLabel: "KI-Dating-Fotos von UnrealShot", heroPanelDescription: (name) => `${name} zeigt nur einen Teil dessen, was deine komplette Lieferung abdecken kann.`,
  profileProblem: "Das Problem im Profil", whatChanges: "Was UnrealShot verändert", changesHeading: "Deine Fotogalerie entscheidet nicht mehr allein, was dein Profil zeigen kann", changeBullets: ["4–6 aktuelle Selfies geben dein Aussehen vor", "Deine Angaben bringen echte Interessen und Vorlieben ein", "UnrealShot erstellt 15 abwechslungsreiche Shooting-Ideen", "Jede Idee enthält vier zusammenhängende Fotos"],
  examplesEyebrow: "Beispiele für KI-Dating-Fotos", createdLabel: "Mit UnrealShot erstellt", deliveryNoteTitle: "Deine Lieferung geht über die hier gezeigten Fotos hinaus.", deliveryNoteBody: "UnrealShot erstellt aus deinen aktuellen Selfies und Angaben 15 originelle Shooting-Ideen mit jeweils vier zusammenhängenden Fotos.",
  solvesEyebrow: "Was dadurch besser wird", solvesDescription: "Es geht nicht darum, deine Galerie mit beliebigen Bildern zu füllen. Eine schwache oder fehlende Facette soll durch ein Foto ersetzt werden, das etwas Echtes über dich zeigt.",
  storyEyebrow: "Eine Idee, vier zusammenhängende Fotos", storyHeading: "Das erste Foto setzt die Szene. Die nächsten drei führen sie weiter.", storyDescription: "Jede UnrealShot-Idee entwickelt eine gemeinsame Bildgeschichte: Abstand, Handlung und Ausdruck ändern sich, ohne wie vier unabhängige Generierungen zu wirken.", storyFacts: [["Ort", "Der Schauplatz bleibt innerhalb der Idee stimmig"], ["Kleidung", "Das Outfit bleibt visuell verbunden"], ["Licht", "Tageszeit und Licht wirken glaubwürdig"], ["Vielfalt", "Ausschnitt, Handlung und Ausdruck bieten Auswahl"]],
  detailsEyebrow: "Aus Details über dich entwickelt", detailsHeading: "Deine Interessen geben jeder Lieferung einen eigenen Ausgangspunkt", detailsDescription: "Sag UnrealShot, was wirklich zu deinem Leben gehört. Diese Angaben können die Ideen für deine Lieferung sinnvoll lenken.", detailsBullets: ["4–6 aktuelle Selfies geben dein Aussehen vor", "Echte Interessen prägen die kreative Richtung", "Deine Vorlieben liefern hilfreichen Kontext", "15 abwechslungsreiche Ideen schaffen Auswahl"], detailsLink: "Sehen, wie Interessen deine Fotos beeinflussen",
  processEyebrow: "Von Selfies zu fertigen Fotos", processHeading: "Kein Fotograf, kein Termin und kein Location-Setup nötig", processDescription: "Fülle von zu Hause aus einen kurzen Fragebogen aus. UnrealShot nutzt deine Referenzen und echten Interessen für eine abwechslungsreiche Lieferung.", processSteps: [["4–6 aktuelle Selfies hochladen", "Wähle klare Einzelaufnahmen aus verschiedenen Winkeln, auf denen Gesicht und Frisur gut zu sehen sind."], ["Erzähle, was zu deinem Leben passt", "Interessen und Vorlieben geben dem System Kontext für persönliche statt beliebiger Ideen."], ["Deine komplette Auswahl erhalten", "Du bekommst 15 Shootings, 60 Fotos und 15 einzelne Foto-Neuerstellungen innerhalb von 30 Minuten."]],
  packageBadge: "Komplettes Dating-Foto-Paket", packageHeading: "Eine Bestellung liefert eine vollständige Auswahl statt nur eines einzelnen Bildes", packageDescription: "UnrealShot schafft genug Vielfalt, um mehr als eine Seite deines Lebens zu zeigen: drinnen, draußen, aktiv, entspannt, gepflegt und spontan.", packageBullets: ["15 originelle Shooting-Ideen", "Vier verbundene Fotos pro Idee", "60 Fotos insgesamt", "15 einzelne Foto-Neuerstellungen", "Lieferung innerhalb von 30 Minuten", "Kein Abonnement"],
  paymentEyebrow: "Einmalige Zahlung", paymentSubtext: "Komplettpaket · keine wiederkehrenden Kosten", startCta: "Mein Shooting starten", secureText: "Sicherer Checkout · Lieferung innerhalb von 30 Minuten",
  moreEyebrow: "Weitere Lücken, die UnrealShot schließen kann", moreHeading: "Mehr Möglichkeiten für eine abwechslungsreiche Auswahl", moreDescription: "Jede Seite zeigt eine andere Lücke, die viele Männer in ihrer Fotogalerie haben. Zusammen zeigen sie nur einen Teil dessen, was 15 originelle Ideen abdecken können.", relatedLabel: "KI-Dating-Fotos von UnrealShot", exploreRelated: "Dieses Ergebnis ansehen", moreLink: "Weitere Dating-Foto-Beispiele ansehen →",
  faqEyebrow: "Fragen vor dem Start", faqTitle: (name) => `Fragen zu ${name}-Fotos`, finalEyebrow: "Schließe die Lücken in deiner Galerie", finalHeading: "Erstelle eine vollständige Auswahl für dein Dating-Profil", finalDescription: "15 verschiedene Shootings · 60 Fotos · 15 Foto-Neuerstellungen · innerhalb von 30 Minuten · 39 $ einmalig.", finalCta: "Meine Dating-Fotos erstellen",
}

const topics: Record<string, ShootTopic> = {
  "gym-training": { name: "Training im Fitnessstudio", keyword: "Fitnessstudio", interest: "das Training", scene: "einem Moment zwischen zwei Sätzen", action: "beim Luft holen und Einstellen eines Geräts", clothing: "schlichter Sportkleidung", problem: "das Spiegel-Selfie dein Gesicht verdeckt", payoff: "Energie und Beständigkeit", balance: "ein Kaffee draußen oder ein gepflegtes Dinner" },
  "outdoor-coffee": { name: "Kaffee im Freien", keyword: "Café im Freien", interest: "Cafés und kleine Alltagsrituale", scene: "einer Kaffeepause in deiner Nachbarschaft", action: "beim Ankommen mit einem Kaffee, Hinsetzen und Umschauen", clothing: "lässiger Kleidung in natürlichen Farben", problem: "ein enger Selfie-Ausschnitt dein Gesicht zeigt, aber keinen gemeinsamen Moment entstehen lässt", payoff: "Nähe und eine unkomplizierte Ausstrahlung", balance: "ein Ganzkörperfoto in der Stadt oder eine konkrete Aktivität" },
  dinner: { name: "Dinner", keyword: "Dinner im Restaurant", interest: "gute Restaurants und Abende außer Haus", scene: "dem Beginn eines Abends im Restaurant", action: "beim Platznehmen, Erwiedern eines Blicks und Genießen des Moments", clothing: "einem dunklen Overshirt oder einem gepflegten Smart-Casual-Outfit", problem: "ein altes Hochzeitsfoto deinen heutigen Stil nicht zeigt", payoff: "einen gepflegten Auftritt ohne Inszenierung", balance: "Tageslicht, Aktivität und Bilder draußen" },
  "city-walk": { name: "Spaziergang durch die Stadt", keyword: "Stadtstraße", interest: "Städte und Architektur", scene: "einem Spaziergang durch eine Fußgängerzone", action: "beim Gehen, kurzen Anhalten an einer Ecke und Reagieren auf etwas außerhalb des Bildes", clothing: "einer Jacke oder einem Pullover für den Alltag", problem: "das Ganzkörperfoto steif wirkt oder du in einer weiten Landschaft verschwindest", payoff: "Bewegung, eine erkennbare Silhouette und alltagstauglichen Stil", balance: "ein Foto beim Kochen oder Training" },
  "coastal-travel": { name: "Küstenreise", keyword: "Küstenreise", interest: "Reisen und Zeit am Wasser", scene: "einem offenen Küstenweg am Meer", action: "beim Gehen, kurzen Halt an der Aussicht und Reagieren auf den Wind", clothing: "bequemen Reiseschichten, die zum Ort passen", problem: "die Landschaft den ganzen Bildraum einnimmt und dein Gesicht verschwindet", payoff: "Neugier und Weite, ohne selbst zum Punkt in der Landschaft zu werden", balance: "eine gewöhnliche Szene vor Ort, etwa im Café oder in der Küche" },
  "home-cooking": { name: "Kochen zu Hause", keyword: "Küche zu Hause", interest: "Kochen und ruhige Momente daheim", scene: "einer einfachen Vorbereitung in einer bewohnten Küche", action: "beim Vorbereiten von Zutaten, Prüfen einer Pfanne und Lächeln zwischen den Schritten", clothing: "bequemer Kleidung, in der du zu Hause kochen würdest", problem: "eine zu perfekte Küche und eine Kochpose das Interesse künstlich wirken lassen", payoff: "Wärme und ein konkretes Gesprächsthema", balance: "ein Stadtspaziergang oder ein Abendfoto" },
  rooftop: { name: "Dachterrasse", keyword: "städtische Dachterrasse", interest: "die Stadt und ihre Ausblicke", scene: "einer zugänglichen Terrasse im Abendlicht", action: "beim Gang über die Terrasse, kurzen Anhalten und Blick über die Skyline", clothing: "einer sauberen Jacke oder einem Overshirt für den Abend", problem: "die Aussicht zur Statusdemonstration wird", payoff: "selbstbewusste, aber glaubwürdige Abendstimmung", balance: "ein Kaffee im Freien oder eine Szene beim Kochen" },
}

const voice: ShootCopyVoice = {
  seo: (t) => [`KI-Dating-Fotos zum Thema ${t.name} | UnrealShot`, `Erstelle realistische Dating-Fotos zum Thema ${t.name}. Du erhältst 15 abwechslungsreiche Shootings, 60 Fotos und 15 einzelne Neuerstellungen für 39 $.`],
  hero: (t) => [`KI-Dating-Fotos: ${t.name}`, `${t.interest[0].toUpperCase()}${t.interest.slice(1)} zeigen`, `mit einer Szene, die zu dir passt`, `Ein gutes Foto zum Thema ${t.name} gibt deinem Profil natürlichen Kontext. UnrealShot macht aus aktuellen Selfies und deinen Angaben zusammenhängende Ideen, etwa bei ${t.scene}, ${t.action}.`],
  pain: (t) => [`Wenn ${t.problem}, verliert dein Profil die wichtige Aussage`, `Nicht der Ort ist das Problem. Es wird schwierig, wenn Kulisse, Accessoire oder Pose die ganze Geschichte für dich erzählen sollen.`, [["Der Kontext wirkt vorbereitet", `Ein gutes Bild sollte zeigen, warum du dort bist – mit einer einfachen Handlung wie: ${t.action}.`], ["Die Pose wird wichtiger als du", `Eine zu stark geplante Haltung nimmt der Aufnahme ${t.payoff}, obwohl genau das sichtbar werden sollte.`], ["Eine Seite überwiegt", `Auch eine starke Idee verliert Wirkung, wenn sie sich wiederholt. Ergänze sie mit ${t.balance}.`]]],
  showcase: (t) => [`${t.name}: glaubwürdiger Kontext statt Kulisse`, `Diese Beispiele zeigen, wie das Thema ${t.name} Persönlichkeit in dein Profil bringt, ohne dein Gesicht zu verstecken. UnrealShot kann Ort, Ausschnitt und Handlung an das anpassen, was wirklich zu dir passt.`],
  benefits: (t) => [`Was ein Foto zum Thema ${t.name} deinem Profil gibt`, [["Ein sichtbares echtes Interesse", `${t.interest[0].toUpperCase()}${t.interest.slice(1)} wird konkret statt zu einer beliebigen Zeile in deiner Bio.`], ["Eine entspannte Handlung", `${t.action[0].toUpperCase()}${t.action.slice(1)} gibt Händen, Blick und Körperhaltung einen natürlichen Sinn.`], ["Mehr Ausgewogenheit", `Die Szene bringt ${t.payoff}; ${t.balance} schafft dazu den nötigen Kontrast in der restlichen Auswahl.`]]],
  selection: (t) => `Gib an, dass ${t.interest} wirklich zu deinem Leben gehört. Das kann einige Ideen in Richtung ${t.scene} lenken, ohne deine komplette Lieferung auf einen Ort festzulegen. Kleidung, Licht, Ausschnitt und Handlung dürfen sich verändern und trotzdem glaubwürdig bleiben.`,
  gallery: (t, index) => [`KI-Dating-Foto zum Thema ${t.name}, mit ${t.clothing}`, ["Der nahe Ausschnitt hält das Gesicht im Mittelpunkt und lässt den Ort unterstützend wirken.", `Der weitere Ausschnitt macht die Handlung lesbar: ${t.action}.`, "Das Ganzkörperbild zeigt Outfit und Umgebung in einem plausiblen Moment.", "Ein spontan wirkender Ausdruck gibt der Szene Wärme und Glaubwürdigkeit."][index] ?? "Eine natürliche Variation derselben Szene."],
  faqs: (t) => [{ question: `Ersetzt die Richtung ${t.name} alle anderen Fotos?`, answer: `Nein. ${t.interest[0].toUpperCase()}${t.interest.slice(1)} kann einen Teil der Lieferung prägen, während die 15 Ideen auch andere Orte, Outfits, Aktivitäten und Stimmungen abdecken.` }, { question: `Wie wirkt ein Foto zum Thema ${t.name} nicht gestellt?`, answer: `Der Ort sollte zu deinem Leben passen und die Handlung schlicht bleiben. UnrealShot nutzt ${t.scene} und aktuelle Selfies, damit Aussehen und Szene zusammenpassen.` }],
}

const de: ShootLocalePack = { locale: "de", ui: deUi, topics, commonFaqs: [{ question: "Stammen die 15 Shootings aus einer kleinen festen Galerie?", answer: "Nein. UnrealShot erstellt aus deinen Referenz-Selfies und Angaben 15 abwechslungsreiche Ideen. Die Beispiele zeigen nur einen Teil der kreativen Bandbreite, keinen festen Katalog." }, { question: "Was passiert, wenn ein Foto mir nicht genug ähnelt?", answer: "Eine referenzgesteuerte Generierung kann bei Ähnlichkeit oder Bildaufbau danebenliegen. Das Paket enthält 15 einzelne Foto-Neuerstellungen für gezielte neue Versuche." }, { question: "Wann werden meine Dating-Fotos geliefert?", answer: "Die komplette Lieferung kommt innerhalb von 30 Minuten, nachdem du deine Referenzen hochgeladen und den kurzen Fragebogen abgeschlossen hast." }], buildCopy: (base, topic) => buildLocalizedShootCopy(base, topic, voice) }

registerShootLocalePack(de)
