import { buildLocalizedShootCopy, registerShootLocalePack, type ShootCopyVoice, type ShootLocalePack, type ShootPageUiCopy, type ShootTopic } from "./dating-shoot-localized"

const frUi: ShootPageUiCopy = {
  heroBullets: ["15 idées de séances originales", "Quatre photos liées par idée", "Livraison sous 30 minutes", "39 $ une seule fois · sans abonnement"],
  createPhotos: "Créer mes photos de rencontre", seeExamples: "Voir les exemples", heroPanelLabel: "Photos de rencontre IA créées avec UnrealShot", heroPanelDescription: (name) => `${name} ne montre qu'une partie de ce que ta livraison complète peut couvrir.`,
  profileProblem: "Le problème du profil", whatChanges: "Ce que change UnrealShot", changesHeading: "Ton appareil photo ne décide plus à lui seul de ce que ton profil peut montrer", changeBullets: ["4 à 6 selfies récents guident ta ressemblance", "Tes réponses ajoutent tes vrais intérêts et préférences", "UnrealShot crée 15 idées de séances variées", "Chaque idée comprend quatre photos liées"],
  examplesEyebrow: "Exemples de photos de rencontre IA", createdLabel: "Créé avec UnrealShot", deliveryNoteTitle: "Ta livraison va plus loin que les photos présentées ici.", deliveryNoteBody: "UnrealShot crée 15 idées originales à partir de tes selfies récents et de tes réponses, avec quatre photos liées pour chaque idée.",
  solvesEyebrow: "Ce que cela résout", solvesDescription: "Le but n'est pas d'ajouter du remplissage. Il s'agit de remplacer une partie faible ou absente de ton appareil photo par une image qui révèle quelque chose d'utile sur toi.",
  storyEyebrow: "Une idée, quatre photos liées", storyHeading: "La première photo installe le moment. Les trois suivantes le prolongent.", storyDescription: "Chaque idée UnrealShot développe une même histoire visuelle : la distance, l'action et l'expression changent sans donner quatre générations sans rapport.", storyFacts: [["Décor", "Le lieu reste cohérent dans toute l'idée"], ["Tenue", "Les vêtements restent visuellement liés"], ["Lumière", "L'heure et la lumière restent crédibles"], ["Variété", "Le cadrage, l'action et l'expression offrent le choix"]],
  detailsEyebrow: "Créé à partir de détails qui te concernent", detailsHeading: "Tes intérêts donnent un point de départ différent à chaque livraison", detailsDescription: "Indique ce qui fait réellement partie de ta vie : cela peut orienter les idées créées pour toi.", detailsBullets: ["4 à 6 selfies récents guident ton apparence", "Tes vrais intérêts orientent la création", "Tes préférences ajoutent un contexte utile", "15 idées variées donnent de l'amplitude à la commande"], detailsLink: "Voir comment tes intérêts orientent les photos",
  processEyebrow: "Des selfies aux photos terminées", processHeading: "Pas de photographe, de rendez-vous ni de lieu à organiser", processDescription: "Réponds à un court questionnaire depuis chez toi. UnrealShot utilise tes références et tes vrais intérêts pour construire une livraison variée.", processSteps: [["Envoie 4 à 6 selfies récents", "Choisis des photos solo nettes, prises sous plusieurs angles, où ton visage et ta coiffure sont visibles."], ["Dis-nous ce qui te ressemble", "Tes intérêts et tes préférences donnent au système le contexte nécessaire pour créer des idées personnelles, pas génériques."], ["Reçois ta sélection complète", "Obtiens 15 séances, 60 photos et 15 reprises photo individuelles sous 30 minutes."]],
  packageBadge: "Pack complet de photos de rencontre", packageHeading: "Une commande te donne une vraie sélection, pas une image isolée", packageDescription: "UnrealShot crée assez de variété pour montrer plusieurs facettes de ta vie : intérieur, extérieur, activité, quotidien, tenue soignée et moments spontanés.", packageBullets: ["15 idées de séances originales", "Quatre photos liées par idée", "60 photos au total", "15 reprises photo individuelles", "Livraison sous 30 minutes", "Sans abonnement"],
  paymentEyebrow: "Paiement unique", paymentSubtext: "Pack complet · aucun prélèvement récurrent", startCta: "Commencer ma séance", secureText: "Paiement sécurisé · livraison sous 30 minutes",
  moreEyebrow: "D'autres manques de ton appareil photo à résoudre", moreHeading: "Découvre d'autres façons de créer de la variété", moreDescription: "Chaque page s'intéresse à un manque différent dans les photos de nombreux hommes. Ensemble, elles ne montrent qu'une partie des 15 idées possibles.", relatedLabel: "Photos de rencontre IA créées avec UnrealShot", exploreRelated: "Explorer ce résultat", moreLink: "Voir plus d'exemples de photos de rencontre →",
  faqEyebrow: "Questions avant de commencer", faqTitle: (name) => `Questions sur les photos ${name.toLowerCase()}`, finalEyebrow: "Comble les manques de ton appareil photo", finalHeading: "Crée une sélection complète pour ton profil", finalDescription: "15 séances différentes · 60 photos · 15 reprises photo · sous 30 minutes · 39 $ une seule fois.", finalCta: "Créer mes photos de rencontre",
}

const topics: Record<string, ShootTopic> = {
  "gym-training": { name: "Entraînement en salle", keyword: "salle de sport", interest: "l'entraînement", scene: "un moment entre deux séries", action: "en reprenant ton souffle et en ajustant une machine", clothing: "une tenue de sport simple", problem: "le selfie miroir masque ton visage", payoff: "énergie et régularité", balance: "un café en terrasse ou un dîner habillé" },
  "outdoor-coffee": { name: "Café en terrasse", keyword: "café en terrasse", interest: "les cafés et les petits rituels du quotidien", scene: "une pause dans ton quartier", action: "en arrivant avec un café, en t'installant puis en regardant autour de toi", clothing: "des vêtements décontractés aux couleurs naturelles", problem: "un selfie serré montre ton visage mais pas la facilité d'un moment partagé", payoff: "une présence accessible et chaleureuse", balance: "une photo en pied en ville ou une activité plus précise" },
  dinner: { name: "Dîner", keyword: "dîner au restaurant", interest: "les sorties et les bons repas", scene: "un début de soirée au restaurant", action: "en t'installant, en échangeant un regard et en profitant du moment", clothing: "une surchemise sombre ou une tenue chic décontractée", problem: "une vieille photo de mariage ne montre pas ton style actuel", payoff: "une allure soignée sans jouer un rôle", balance: "des photos de journée, d'activité et de plein air" },
  "city-walk": { name: "Balade en ville", keyword: "rue en ville", interest: "la ville et l'architecture", scene: "une promenade dans une rue piétonne", action: "en marchant, en t'arrêtant au coin d'une rue et en remarquant quelque chose", clothing: "une veste ou un pull facile à porter au quotidien", problem: "la photo en pied devient une pose raide ou un paysage où tu es minuscule", payoff: "du mouvement, une silhouette lisible et un style quotidien", balance: "une photo de cuisine ou de sport" },
  "coastal-travel": { name: "Voyage sur la côte", keyword: "voyage sur la côte", interest: "les voyages et les escapades au bord de l'eau", scene: "un chemin côtier ouvert sur la mer", action: "en marchant, en t'arrêtant devant le paysage et en réagissant au vent", clothing: "des couches de voyage décontractées adaptées au lieu", problem: "le paysage prend toute la place et ton visage disparaît", payoff: "de la curiosité et de l'espace sans devenir un point dans le décor", balance: "une scène locale plus ordinaire comme un café ou une cuisine" },
  "home-cooking": { name: "Cuisine à la maison", keyword: "cuisine à la maison", interest: "la cuisine et les moments tranquilles chez toi", scene: "une préparation simple dans une cuisine habitée", action: "en préparant des ingrédients, en vérifiant une poêle et en souriant entre deux étapes", clothing: "des vêtements confortables adaptés à la cuisine", problem: "une cuisine trop parfaite et une pose de chef rendent l'intérêt artificiel", payoff: "de la chaleur et un détail concret auquel répondre", balance: "une balade en ville ou une image de soirée" },
  rooftop: { name: "Toit-terrasse", keyword: "toit-terrasse en ville", interest: "la ville et les points de vue urbains", scene: "une terrasse accessible à l'heure dorée", action: "en traversant la terrasse, en t'arrêtant un instant puis en regardant la skyline", clothing: "une veste nette ou une surchemise pour sortir", problem: "la vue urbaine devient une démonstration de statut", payoff: "une allure assurée, mais crédible", balance: "un café en terrasse ou une scène de cuisine" },
}

const voice: ShootCopyVoice = {
  seo: (t) => [`Photos de rencontre IA : ${t.name} | UnrealShot`, `Crée des photos de rencontre IA réalistes sur le thème ${t.name.toLowerCase()}. Obtiens 15 séances variées, 60 photos et 15 reprises individuelles pour 39 $.`],
  hero: (t) => [`Photos de rencontre IA : ${t.name}`, `Montre ${t.interest}`, `dans une scène qui te ressemble`, `Une bonne photo qui montre ${t.interest} donne un contexte naturel à ton profil. UnrealShot transforme tes selfies récents et tes réponses en idées cohérentes, avec ${t.scene}, ${t.action}.`],
  pain: (t) => [`Quand ${t.problem}, ton profil perd ce qu'il devrait montrer`, `Le problème n'est pas le décor en lui-même. C'est ce qui arrive quand la photo demande au lieu, à l'accessoire ou à la pose de raconter toute l'histoire à ta place.`, [["Le contexte ne paraît pas naturel", `Une image utile doit expliquer pourquoi tu es là, avec ${t.action}, pas seulement présenter un arrière-plan reconnaissable.`], ["La pose prend le dessus", `Une posture trop préparée donne une impression de séance photo alors que le profil devrait laisser voir ${t.payoff}.`], ["Une seule facette finit par dominer", `Même une bonne idée perd de sa force si elle se répète. Il faut la compléter avec ${t.balance}.`]]],
  showcase: (t) => [`${t.name} : un contexte qui reste naturel`, `Ces exemples montrent comment le thème ${t.name.toLowerCase()} peut donner du relief à un profil sans cacher ton visage. UnrealShot peut explorer plusieurs lieux, cadrages et actions à partir de ce qui te correspond vraiment.`],
  benefits: (t) => [`Ce qu'une bonne photo sur le thème ${t.name.toLowerCase()} apporte à ton profil`, [["Un intérêt visible", `${t.interest[0].toUpperCase()}${t.interest.slice(1)} devient concret, au lieu de rester une ligne générique dans ta bio.`], ["Une action qui donne du naturel", `${t.action[0].toUpperCase()}${t.action.slice(1)} donne une raison aux mains, au regard et à la posture.`], ["Une variété mieux équilibrée", `La scène ajoute ${t.payoff}, puis ${t.balance} apporte le contraste nécessaire au reste de la sélection.`]]],
  selection: (t) => `Indique que ${t.interest} fait réellement partie de ta vie. Cela peut orienter les idées vers ${t.scene}, sans enfermer toute ta livraison dans un seul décor. L'exécution finale peut varier la tenue, la lumière, le cadrage et l'action pour rester crédible.`,
  gallery: (t, index) => {
    const captions = ["Un cadrage rapproché garde le visage au centre et laisse le décor jouer son rôle.", `Une vue plus large rend l'action lisible : ${t.action}.`, `Le cadre en pied montre la tenue et la façon dont le lieu accompagne le moment.`, "Une expression prise sur le vif apporte la petite imperfection qui rend la scène crédible."]
    return [`Photo de rencontre générée par IA : un homme dans une scène sur le thème « ${t.name} », avec ${t.clothing}`, captions[index] ?? "Une variation naturelle dans la même scène."]
  },
  faqs: (t) => [{ question: `Cette direction (${t.name.toLowerCase()}) va-t-elle remplacer toutes mes autres photos ?`, answer: `Non. ${t.interest[0].toUpperCase()}${t.interest.slice(1)} peut orienter une partie de la livraison, tandis que les 15 idées explorent aussi d'autres tenues, lieux, activités et ambiances.` }, { question: `Comment éviter qu'une photo sur le thème ${t.name.toLowerCase()} paraisse mise en scène ?`, answer: `Le lieu doit correspondre à ta vie et l'action doit rester simple. UnrealShot s'appuie sur ${t.scene} et sur tes selfies récents pour garder une apparence actuelle et une scène cohérente.` }],
}

const fr: ShootLocalePack = { locale: "fr", ui: frUi, topics, commonFaqs: [{ question: "Les 15 séances viennent-elles d'une petite galerie fixe ?", answer: "Non. UnrealShot crée 15 idées variées à partir de tes selfies de référence et de tes réponses. Les exemples montrent une partie de la gamme créative, pas un catalogue fermé." }, { question: "Que faire si une photo ne me ressemble pas assez ?", answer: "La génération guidée par références peut parfois rater une ressemblance ou une composition. Le pack comprend 15 reprises photo individuelles pour refaire les images qui le méritent." }, { question: "Quand recevrai-je mes photos de rencontre ?", answer: "La livraison complète arrive sous 30 minutes après l'envoi de tes références et la fin du questionnaire." }], buildCopy: (base, topic) => buildLocalizedShootCopy(base, topic, voice) }

registerShootLocalePack(fr)
