import { buildLocalizedShootCopy, registerShootLocalePack, type ShootCopyVoice, type ShootLocalePack, type ShootPageUiCopy, type ShootTopic } from "./dating-shoot-localized"

const esUi: ShootPageUiCopy = {
  heroBullets: ["15 ideas de sesiones originales", "Cuatro fotos conectadas por idea", "Entrega en menos de 30 minutos", "39 $ una sola vez · sin suscripción"],
  createPhotos: "Crear mis fotos para citas", seeExamples: "Ver ejemplos", heroPanelLabel: "Fotos para citas creadas con UnrealShot", heroPanelDescription: (name) => `${name} muestra solo una parte de todo lo que puede cubrir tu entrega.`,
  profileProblem: "El problema del perfil", whatChanges: "Lo que cambia UnrealShot", changesHeading: "Tu carrete ya no decide por sí solo lo que puede mostrar tu perfil", changeBullets: ["Entre 4 y 6 selfies actuales guían tu parecido", "Tus respuestas añaden tus intereses y preferencias reales", "UnrealShot crea 15 ideas de sesiones variadas", "Cada idea incluye cuatro fotos conectadas"],
  examplesEyebrow: "Ejemplos de fotos para citas con IA", createdLabel: "Creado con UnrealShot", deliveryNoteTitle: "Tu entrega va mucho más allá de las fotos que ves aquí.", deliveryNoteBody: "UnrealShot crea 15 ideas originales a partir de tus selfies actuales y tus respuestas, con cuatro fotos conectadas para cada idea.",
  solvesEyebrow: "Qué resuelve", solvesDescription: "La idea no es añadir relleno. Es cubrir una parte débil o ausente de tu carrete con una foto que revele algo útil sobre ti.",
  storyEyebrow: "Una idea, cuatro fotos conectadas", storyHeading: "La primera foto presenta el momento. Las otras tres lo desarrollan.", storyDescription: "Cada idea de UnrealShot cuenta una misma historia visual: cambia la distancia, la acción y la expresión, pero no parece que sean cuatro generaciones sin relación.", storyFacts: [["Escenario", "El lugar se mantiene coherente en toda la idea"], ["Ropa", "El conjunto sigue conectado visualmente"], ["Luz", "La hora y la iluminación resultan creíbles"], ["Variedad", "Encuadre, acción y expresión te dan opciones"]],
  detailsEyebrow: "Creado a partir de detalles sobre ti", detailsHeading: "Tus intereses dan a cada entrega un punto de partida distinto", detailsDescription: "Cuéntale a UnrealShot qué forma parte de tu vida de verdad y eso puede orientar las ideas que cree para ti.", detailsBullets: ["Entre 4 y 6 selfies actuales guían tu apariencia", "Tus intereses reales orientan la dirección creativa", "Tus preferencias aportan contexto útil", "15 ideas variadas crean amplitud en tu pedido"], detailsLink: "Mira cómo tus intereses dan forma a tus fotos",
  processEyebrow: "De los selfies a las fotos terminadas", processHeading: "Sin fotógrafo, citas ni preparativos de localización", processDescription: "Completa un breve cuestionario desde casa. UnrealShot usa tus referencias y tus intereses reales para crear una entrega variada.", processSteps: [["Sube entre 4 y 6 selfies actuales", "Elige fotos individuales nítidas, tomadas desde varios ángulos, donde se vean bien tu rostro y tu pelo."], ["Cuéntanos qué encaja contigo", "Tus intereses y preferencias dan al sistema el contexto para crear ideas personales en lugar de escenas genéricas."], ["Recibe tu selección completa", "Obtén 15 sesiones, 60 fotos y 15 repeticiones individuales en menos de 30 minutos."]],
  packageBadge: "Paquete completo de fotos para citas", packageHeading: "Un pedido te da una selección completa, no una imagen aislada", packageDescription: "UnrealShot crea suficiente variedad para mostrar más de un lado de tu vida: interiores, exteriores, actividades, momentos casuales, looks cuidados y escenas espontáneas.", packageBullets: ["15 ideas de sesiones originales", "Cuatro fotos conectadas por idea", "60 fotos en total", "15 repeticiones individuales", "Entrega en menos de 30 minutos", "Sin suscripción"],
  paymentEyebrow: "Pago único", paymentPrice: "39 $", paymentSubtext: "Paquete completo · sin cargos recurrentes", startCta: "Empezar mi sesión", secureText: "Pago seguro · entrega en menos de 30 minutos",
  moreEyebrow: "Más problemas del carrete que UnrealShot puede resolver", moreHeading: "Descubre otras formas de crear variedad", moreDescription: "Cada página se centra en una carencia distinta que muchos hombres tienen en sus fotos. Juntas muestran solo una parte de lo que pueden cubrir 15 ideas originales.", relatedLabel: "Fotos para citas creadas con UnrealShot", exploreRelated: "Explorar este resultado", moreLink: "Ver más ejemplos de fotos para citas →",
  faqEyebrow: "Preguntas antes de empezar", faqTitle: (name) => `Preguntas sobre las fotos de ${name.toLowerCase()}`, finalEyebrow: "Cubre los huecos de tu carrete", finalHeading: "Crea una selección completa para tu perfil", finalDescription: "15 sesiones distintas · 60 fotos · 15 repeticiones · en menos de 30 minutos · 39 $ una sola vez.", finalCta: "Crear mis fotos para citas",
}

const topics: Record<string, ShootTopic> = {
  "gym-training": { name: "Entrenamiento en el gimnasio", keyword: "gimnasio", interest: "tu rutina de entrenamiento", scene: "un momento entre series", action: "recuperando el aliento y ajustando una máquina", clothing: "ropa deportiva sencilla", problem: "el selfie frente al espejo tapa tu cara", payoff: "energía y constancia", balance: "un café al aire libre o una cena arreglada" },
  "outdoor-coffee": { name: "Café al aire libre", keyword: "café al aire libre", interest: "los cafés y los pequeños rituales del día a día", scene: "una pausa en tu barrio", action: "llegando con un café, sentándote y mirando alrededor", clothing: "capas casuales en colores naturales", problem: "un selfie demasiado cerrado muestra tu cara pero no cómo sería compartir un momento contigo", payoff: "una presencia cercana y fácil de imaginar", balance: "una foto de cuerpo entero en la ciudad o una actividad concreta" },
  dinner: { name: "Cena", keyword: "cena en un restaurante", interest: "salir a cenar y descubrir buenos sitios", scene: "el comienzo de una noche en un restaurante", action: "acomodándote, cruzando una mirada y disfrutando del momento", clothing: "una sobrecamisa oscura o un conjunto smart casual", problem: "una foto antigua de boda no muestra tu estilo actual", payoff: "un aspecto cuidado sin parecer que interpretas un papel", balance: "fotos de día, de actividad y al aire libre" },
  "city-walk": { name: "Paseo por la ciudad", keyword: "calle de ciudad", interest: "la ciudad y la arquitectura", scene: "un paseo por una calle peatonal", action: "caminando, deteniéndote en una esquina y reaccionando a algo fuera de cámara", clothing: "una chaqueta o un jersey que llevarías cualquier día", problem: "la foto de cuerpo entero se convierte en una pose rígida o en un paisaje donde apenas se te ve", payoff: "movimiento, silueta clara y estilo cotidiano", balance: "una foto cocinando o entrenando" },
  "coastal-travel": { name: "Viaje por la costa", keyword: "viaje por la costa", interest: "viajar y pasar tiempo junto al mar", scene: "un sendero costero abierto al agua", action: "caminando, deteniéndote ante el paisaje y reaccionando al viento", clothing: "capas cómodas de viaje adecuadas al lugar", problem: "el paisaje ocupa todo el encuadre y tu cara desaparece", payoff: "curiosidad y aire libre sin convertirte en un punto del paisaje", balance: "una escena local más cotidiana, como un café o la cocina" },
  "home-cooking": { name: "Cocinar en casa", keyword: "cocina en casa", interest: "cocinar y disfrutar de momentos tranquilos en casa", scene: "una preparación sencilla en una cocina vivida", action: "preparando ingredientes, comprobando una sartén y sonriendo entre pasos", clothing: "ropa cómoda para estar en casa y cocinar", problem: "una cocina demasiado perfecta y una pose de chef hacen que el interés parezca inventado", payoff: "calidez y un detalle concreto del que se puede hablar", balance: "un paseo por la ciudad o una escena de noche" },
  rooftop: { name: "Azotea", keyword: "azotea urbana", interest: "la ciudad y sus vistas", scene: "una terraza accesible durante la hora dorada", action: "recorriendo la terraza, deteniéndote un momento y mirando el horizonte", clothing: "una chaqueta limpia o una sobrecamisa para salir", problem: "la vista de la ciudad se convierte en una demostración de estatus", payoff: "seguridad con los pies en la tierra", balance: "un café al aire libre o una escena cocinando" },
}

const voice: ShootCopyVoice = {
  seo: (t) => [`Fotos para citas con IA: ${t.name} | UnrealShot`, `Crea fotos realistas para citas con el tema ${t.name.toLowerCase()}. Recibe 15 sesiones variadas, 60 fotos y 15 repeticiones individuales por 39 $.`],
  hero: (t) => [`Fotos para citas con IA: ${t.name}`, `Haz visible ${t.interest}`, `con una escena que encaje contigo`, `Una buena foto sobre ${t.name.toLowerCase()} aporta contexto natural a tu perfil. UnrealShot convierte tus selfies actuales y tus respuestas en ideas coherentes, con ${t.scene}, ${t.action}.`],
  pain: (t) => [`Cuando ${t.problem}, tu perfil pierde lo importante`, `El problema no es el lugar. Aparece cuando el escenario, el accesorio o la pose tienen que contar toda la historia en tu lugar.`, [["El contexto parece preparado", `Una imagen útil debe explicar por qué estás allí, con una acción sencilla como ${t.action}, no solo enseñar un fondo reconocible.`], ["La pose se convierte en el protagonista", `Una postura demasiado estudiada oculta ${t.payoff}, que es justo lo que la foto debería transmitir.`], ["Una sola faceta ocupa todo el perfil", `Incluso una buena idea pierde fuerza si se repite. Complétala con ${t.balance}.`]]],
  showcase: (t) => [`${t.name}: un contexto fácil de creer`, `Estos ejemplos muestran cómo el tema ${t.name.toLowerCase()} puede dar personalidad al perfil sin esconder tu rostro. UnrealShot puede variar lugares, encuadres y acciones según lo que realmente encaje contigo.`],
  benefits: (t) => [`Qué aporta una buena foto sobre ${t.name.toLowerCase()}`, [["Un interés que se entiende", `${t.interest[0].toUpperCase()}${t.interest.slice(1)} deja de ser una frase genérica y se convierte en algo visible.`], ["Una acción que relaja la imagen", `${t.action[0].toUpperCase()}${t.action.slice(1)} da un propósito natural a las manos, la mirada y la postura.`], ["Más equilibrio en la selección", `La escena suma ${t.payoff}; después, ${t.balance} aporta contraste al resto de tus fotos.`]]],
  selection: (t) => `Indica que ${t.interest} forma parte de tu vida de verdad. Puede orientar algunas ideas hacia ${t.scene}, pero no encierra toda tu entrega en un solo lugar. La ropa, la luz, el encuadre y la acción pueden cambiar para que el resultado siga siendo creíble.`,
  gallery: (t, index) => [`Foto para citas generada por IA: un hombre en una escena de ${t.name.toLowerCase()}, con ${t.clothing}`, ["El encuadre cercano mantiene el rostro en el centro y deja que el lugar acompañe.", `Una vista más amplia hace que la acción sea clara: ${t.action}.`, "La vista de cuerpo entero muestra la ropa y la relación natural con el entorno.", "Una expresión captada en el momento añade la pequeña imperfección que vuelve creíble la escena."][index] ?? "Una variación natural dentro de la misma escena."],
  faqs: (t) => [{ question: `¿Esta dirección (${t.name.toLowerCase()}) sustituirá todas mis demás fotos?`, answer: `No. ${t.interest[0].toUpperCase()}${t.interest.slice(1)} puede orientar una parte de la entrega, mientras las 15 ideas exploran también otros lugares, prendas, actividades y ambientes.` }, { question: `¿Cómo evito que una foto sobre ${t.name.toLowerCase()} parezca preparada?`, answer: `El lugar debe tener sentido para tu vida y la acción debe ser sencilla. UnrealShot parte de ${t.scene} y de tus selfies actuales para mantener una apariencia reconocible y una escena coherente.` }],
}

const es: ShootLocalePack = { locale: "es", ui: esUi, topics, commonFaqs: [{ question: "¿Las 15 sesiones salen de una galería pequeña y fija?", answer: "No. UnrealShot crea 15 ideas variadas a partir de tus selfies de referencia y tus respuestas. Los ejemplos muestran solo una parte de las posibilidades, no un catálogo cerrado." }, { question: "¿Qué pasa si una foto no se parece lo suficiente a mí?", answer: "La generación guiada por referencias puede fallar en algún detalle del parecido o la composición. El paquete incluye 15 repeticiones individuales para rehacer las imágenes que lo necesiten." }, { question: "¿Cuándo recibiré mis fotos para citas?", answer: "La entrega completa llega en menos de 30 minutos después de subir tus referencias y terminar el cuestionario." }], buildCopy: (base, topic) => buildLocalizedShootCopy(base, topic, voice) }

registerShootLocalePack(es)
