export const permanentRedirects = new Map<string, string>([
  ["/use-case/dating-photos", "/dating-photos"],
  ["/ai-dating-photoshoot", "/"],
  ["/blog/how-to-get-ai-photoshoots-that-look-like-you", "/realistic-ai-dating-photos"],
  ["/contact-us", "/contact"],
  ["/faqs", "/how-it-works"],
])

export const gonePaths = new Set([
  "/ai-bat-mitzvah-photoshoot",
  "/ai-botanic-illustrations",
  "/ai-botanic-photoshoot",
  "/ai-chef-headshots",
  "/ai-christmas-photoshoot",
  "/ai-couple-photo-generator",
  "/ai-diwali-photoshoot",
  "/ai-doctor-headshots",
  "/doctor-headshots",
  "/ai-fantasy-photoshoot",
  "/ai-glamour-photoshoot",
  "/ai-halloween-photoshoot",
  "/ai-influencer-generator",
  "/ai-instagram-photoshoot",
  "/ai-lawyer-headshots",
  "/lawyer-headshots",
  "/ai-maternity-photoshoot",
  "/ai-multiperson-photo-generator",
  "/ai-real-estate-headshots",
  "/ai-speaker-photoshoot",
  "/ai-yearbook",
  "/black-swan-photoshoot",
  "/corporate-headshots",
  "/denim-wear-photoshoot",
  "/founder-headshots",
  "/linkedin-headshots",
  "/natural-looks-photoshoot",
  "/neutral-muse-photoshoot",
  "/office-outfit-photoshoot",
  "/personal-branding-photoshoot",
  "/professional-headshot-ai",
  "/professional-headshots",
  "/profile-photo-maker",
  "/resume-headshots",
  "/street-style-photoshoot",
  "/stylish-ai-portraits",
  "/vintage-photoshoot",
  "/use-case/couple-photos",
  "/use-case/creative-headshots",
  "/email-signature-generator",
  "/instagram-bio-generator",
  "/instagram-caption-generator",
  "/linkedin-bio-generator",
  "/linkedin-headline-generator",
  "/linkedin-post-generator",
  "/blog/ai-headshots-vs-professional-photographer-pros-and-cons",
  "/blog/how-to-use-ai-headshots-to-level-up-your-resume",
  "/blog/the-best-ai-headshot-generators-of-2026",
  "/blog/best-ai-headshot-generators-in-2026",
  "/blog/best-aragon-ai-alternatives-in-2025",
  "/blog/how-to-create-a-professional-ai-headshot-in-2025",
  "/blog/create-professional-ai-headshots-with-unrealshot-ai",
  "/blog/the-best-15-ai-headshot-generators-in-2025-for-stunning-profiles",
  "/blog/creative-christmas-photo-ideas-to-create-with-ai",
  "/blog/creative-christmas-photo-ideas-with-ai",
  "/blog/remaker-ai-face-swap-uses-features",
  "/blog/how-to-use-saze-ai-text-to-speech",
  "/blog/26-january-ai-photo-editing-republic-day-image-prompts",
])
