import type { PublishedPublicLocale } from "@/i18n/config"
import { activityPageData } from "@/lib/dating-activity-content"

export type ActivityPageUi = {
  createPhotos: string
  exploreStyles: string
  deliveryNote: string
  cameraRollEyebrow: string
  cameraRollHeading: string
  cameraRollDescription: string
  whatWorksEyebrow: string
  categoriesHeading: string
  categoriesDescription: string
  fullGallery: string
  categoryLabel: string
  shootSuffix: string
  framingTip: string
  promptPairing: string
  viewFrames: string
  blueprintEyebrow: string
  rulesHeading: string
  rulesDescription: string
  doLabel: string
  doNotLabel: string
  placementEyebrow: string
  placementHeading: string
  placementDescription: string
  promptTip: string
  tinderGuide: string
  hingeGuide: string
  bumbleGuide: string
  datingPhotosPillar: string
  consistentEyebrow: string
  consistentHeading: string
  consistentDescription: string
  exploreExamples: string
  relatedFrames: string
  viewShoot: string
  faqEyebrow: string
  faqHeading: string
  faqDescription: string
  priceEyebrow: string
  finalHeading: string
  finalDescription: string
  mistakeLabel: string
  fixLabel: string
  ruleLabel: string
}

const enUi: ActivityPageUi = {
  createPhotos: "Create my activity photos",
  exploreStyles: "Explore top 5 hobby styles ↓",
  deliveryNote: "Generated with reference-guided likeness · 15 shoots · 60 photos delivered in 30 minutes.",
  cameraRollEyebrow: "The camera roll trap",
  cameraRollHeading: "Why most men’s hobby photos fail on dating apps",
  cameraRollDescription: "When women swipe through a profile, they look for clues about your real-world lifestyle and personality. Weak activity photos either obscure your appearance or send the wrong social signals.",
  whatWorksEyebrow: "What actually works",
  categoriesHeading: "The 5 best hobby photo styles for men",
  categoriesDescription: "These categories consistently generate the highest message response rates because they balance natural attractiveness, approachable warmth, and effortless conversation hooks.",
  fullGallery: "See full photo gallery →",
  categoryLabel: "CATEGORY",
  shootSuffix: "shoot",
  framingTip: "Framing & Photo Tip:",
  promptPairing: "Best Prompt Pairing:",
  viewFrames: "View all 4 frames of this",
  blueprintEyebrow: "Photography blueprint",
  rulesHeading: "4 rules for capturing believable lifestyle photos",
  rulesDescription: "Whether you take these photos yourself or generate them with UnrealShot, adhere to these photographic principles to ensure your lineup looks natural, friend-taken, and authentic.",
  doLabel: "DO:",
  doNotLabel: "DON’T:",
  placementEyebrow: "App placement guide",
  placementHeading: "Where to place activity photos on Hinge, Tinder & Bumble",
  placementDescription: "Each app has a unique user psychology. Here is how to structure your activity photos for maximum engagement on each major dating app.",
  promptTip: "Prompt Tip:",
  tinderGuide: "Tinder photo guide",
  hingeGuide: "Hinge photo guide",
  bumbleGuide: "Bumble photo guide",
  datingPhotosPillar: "Dating photos pillar",
  consistentEyebrow: "Consistent 4-frame shoots",
  consistentHeading: "See how UnrealShot builds complete lifestyle scenes",
  consistentDescription: "Each generated shoot delivers 4 coordinated frames: opener, half-body, full-length, and candid. Explore these real lifestyle examples to see how the lighting, wardrobe, and environment remain cohesive.",
  exploreExamples: "Explore all examples →",
  relatedFrames: "4 related frames",
  viewShoot: "View shoot details →",
  faqEyebrow: "Frequently asked questions",
  faqHeading: "Activity & lifestyle photo FAQ",
  faqDescription: "Expert advice on selecting, positioning, and generating natural activity photos for modern dating apps.",
  priceEyebrow: "$39 once · No subscription · 30-min delivery",
  finalHeading: "Build your complete dating photo lineup today",
  finalDescription: "Turn 4–6 reference selfies into 15 varied lifestyle shoots and 60 high-resolution photos, complete with 15 individual Photo Retakes.",
  mistakeLabel: "The Mistake:",
  fixLabel: "The Fix:",
  ruleLabel: "RULE",
}

const frUi: ActivityPageUi = {
  createPhotos: "Créer mes photos d’activité",
  exploreStyles: "Découvrir 5 styles de loisirs ↓",
  deliveryNote: "Ressemblance guidée par références · 15 séances · 60 photos livrées sous 30 minutes.",
  cameraRollEyebrow: "Le piège de la galerie photo",
  cameraRollHeading: "Pourquoi les photos de loisirs de nombreux hommes échouent sur les applications",
  cameraRollDescription: "En parcourant un profil, les personnes cherchent des indices sur votre mode de vie et votre personnalité. De mauvaises photos d’activité cachent votre apparence ou envoient de mauvais signaux sociaux.",
  whatWorksEyebrow: "Ce qui fonctionne vraiment",
  categoriesHeading: "Les 5 meilleurs styles de photos de loisirs pour hommes",
  categoriesDescription: "Ces catégories favorisent régulièrement les réponses car elles équilibrent attractivité naturelle, chaleur et sujets de conversation faciles.",
  fullGallery: "Voir toute la galerie photo →",
  categoryLabel: "CATÉGORIE",
  shootSuffix: "séance",
  framingTip: "Conseil de cadrage et de photo :",
  promptPairing: "Meilleur lien avec un prompt :",
  viewFrames: "Voir les 4 images de cette séance",
  blueprintEyebrow: "Guide photo",
  rulesHeading: "4 règles pour des photos de vie crédibles",
  rulesDescription: "Que vous preniez ces photos vous-même ou les génériez avec UnrealShot, suivez ces principes pour que votre sélection reste naturelle, comme prise par un proche et authentique.",
  doLabel: "À FAIRE :",
  doNotLabel: "À ÉVITER :",
  placementEyebrow: "Guide de placement dans les applications",
  placementHeading: "Où placer les photos d’activité sur Hinge, Tinder et Bumble",
  placementDescription: "Chaque application a ses propres usages. Voici comment structurer vos photos d’activité pour favoriser les échanges sur les principales applications de rencontre.",
  promptTip: "Conseil de prompt :",
  tinderGuide: "Guide des photos Tinder",
  hingeGuide: "Guide des photos Hinge",
  bumbleGuide: "Guide des photos Bumble",
  datingPhotosPillar: "Page de référence des photos de rencontre",
  consistentEyebrow: "Séances cohérentes en 4 images",
  consistentHeading: "Découvrez comment UnrealShot construit des scènes de vie complètes",
  consistentDescription: "Chaque séance générée fournit 4 images coordonnées : ouverture, buste, pied et spontanéité. Ces exemples montrent comment la lumière, la tenue et l’environnement restent cohérents.",
  exploreExamples: "Explorer tous les exemples →",
  relatedFrames: "4 images liées",
  viewShoot: "Voir les détails de la séance →",
  faqEyebrow: "Questions fréquentes",
  faqHeading: "FAQ sur les photos d’activité et de style de vie",
  faqDescription: "Conseils d’experts pour choisir, placer et générer des photos d’activité naturelles pour les applications de rencontre actuelles.",
  priceEyebrow: "39 $ une fois · Sans abonnement · livraison sous 30 min",
  finalHeading: "Construisez aujourd’hui une sélection complète de photos de rencontre",
  finalDescription: "Transformez 4 à 6 selfies de référence en 15 séances de vie variées et 60 photos haute résolution, avec 15 reprises photo individuelles.",
  mistakeLabel: "Erreur :",
  fixLabel: "Solution :",
  ruleLabel: "RÈGLE",
}

const esUi: ActivityPageUi = {
  createPhotos: "Crear mis fotos de actividad",
  exploreStyles: "Explorar los 5 estilos de hobby principales ↓",
  deliveryNote: "Parecido guiado por referencias · 15 sesiones · 60 fotos entregadas en 30 minutos.",
  cameraRollEyebrow: "La trampa del carrete",
  cameraRollHeading: "Por qué las fotos de hobbies de muchos hombres fallan en las aplicaciones de citas",
  cameraRollDescription: "Al recorrer un perfil, las personas buscan pistas sobre tu estilo de vida y personalidad reales. Las fotos de actividad débiles ocultan tu aspecto o transmiten señales sociales equivocadas.",
  whatWorksEyebrow: "Lo que funciona de verdad",
  categoriesHeading: "Los 5 mejores estilos de fotos de hobbies para hombres",
  categoriesDescription: "Estas categorías suelen generar más respuestas porque equilibran atractivo natural, cercanía y temas de conversación fáciles.",
  fullGallery: "Ver la galería completa →",
  categoryLabel: "CATEGORÍA",
  shootSuffix: "sesión",
  framingTip: "Consejo de encuadre y foto:",
  promptPairing: "Mejor combinación con un prompt:",
  viewFrames: "Ver los 4 encuadres de esta sesión",
  blueprintEyebrow: "Guía fotográfica",
  rulesHeading: "4 reglas para conseguir fotos de estilo de vida creíbles",
  rulesDescription: "Tanto si tomas estas fotos tú mismo como si las generas con UnrealShot, sigue estos principios para que tu selección se vea natural, como tomada por un amigo y auténtica.",
  doLabel: "SÍ:",
  doNotLabel: "NO:",
  placementEyebrow: "Guía de colocación en aplicaciones",
  placementHeading: "Dónde colocar fotos de actividad en Hinge, Tinder y Bumble",
  placementDescription: "Cada aplicación tiene una psicología distinta. Así puedes organizar tus fotos de actividad para favorecer la conversación en las principales aplicaciones de citas.",
  promptTip: "Consejo para el prompt:",
  tinderGuide: "Guía de fotos para Tinder",
  hingeGuide: "Guía de fotos para Hinge",
  bumbleGuide: "Guía de fotos para Bumble",
  datingPhotosPillar: "Página principal de fotos para citas",
  consistentEyebrow: "Sesiones coherentes de 4 encuadres",
  consistentHeading: "Mira cómo UnrealShot construye escenas de estilo de vida completas",
  consistentDescription: "Cada sesión generada ofrece 4 encuadres coordinados: apertura, medio cuerpo, cuerpo entero y espontáneo. Explora estos ejemplos para ver cómo se mantienen la luz, la ropa y el entorno.",
  exploreExamples: "Explorar todos los ejemplos →",
  relatedFrames: "4 encuadres relacionados",
  viewShoot: "Ver los detalles de la sesión →",
  faqEyebrow: "Preguntas frecuentes",
  faqHeading: "Preguntas frecuentes sobre fotos de actividad y estilo de vida",
  faqDescription: "Consejos de expertos para elegir, colocar y generar fotos de actividad naturales para las aplicaciones de citas actuales.",
  priceEyebrow: "39 $ una sola vez · Sin suscripción · entrega en 30 min",
  finalHeading: "Crea hoy una selección completa de fotos para citas",
  finalDescription: "Convierte 4–6 selfies de referencia en 15 sesiones variadas de estilo de vida y 60 fotos de alta resolución, con 15 repeticiones individuales.",
  mistakeLabel: "El error:",
  fixLabel: "La solución:",
  ruleLabel: "REGLA",
}

const deUi: ActivityPageUi = {
  createPhotos: "Meine Aktivitätsfotos erstellen",
  exploreStyles: "Die 5 wichtigsten Hobby-Stile entdecken ↓",
  deliveryNote: "Referenzgesteuerte Ähnlichkeit · 15 Shootings · 60 Fotos in 30 Minuten geliefert.",
  cameraRollEyebrow: "Die Kamera-Falle",
  cameraRollHeading: "Warum Hobbyfotos vieler Männer auf Dating-Apps nicht funktionieren",
  cameraRollDescription: "Beim Durchsehen eines Profils suchen Menschen Hinweise auf deinen echten Alltag und deine Persönlichkeit. Schwache Aktivitätsfotos verdecken dein Aussehen oder senden falsche soziale Signale.",
  whatWorksEyebrow: "Was wirklich funktioniert",
  categoriesHeading: "Die 5 besten Hobby-Fotostile für Männer",
  categoriesDescription: "Diese Kategorien führen regelmäßig zu mehr Antworten, weil sie natürliche Attraktivität, Zugänglichkeit und einfache Gesprächsthemen verbinden.",
  fullGallery: "Die vollständige Fotogalerie ansehen →",
  categoryLabel: "KATEGORIE",
  shootSuffix: "Shooting",
  framingTip: "Tipp für Bildausschnitt und Foto:",
  promptPairing: "Beste Prompt-Kombination:",
  viewFrames: "Alle 4 Aufnahmen dieses Shootings ansehen",
  blueprintEyebrow: "Fotografie-Leitfaden",
  rulesHeading: "4 Regeln für glaubwürdige Lifestyle-Fotos",
  rulesDescription: "Egal, ob du diese Fotos selbst aufnimmst oder mit UnrealShot erstellst: Befolge diese Grundsätze, damit deine Auswahl natürlich, wie von einem Freund aufgenommen und authentisch wirkt.",
  doLabel: "RICHTIG:",
  doNotLabel: "FALSCH:",
  placementEyebrow: "Leitfaden für die Platzierung in Apps",
  placementHeading: "Wo du Aktivitätsfotos auf Hinge, Tinder und Bumble platzierst",
  placementDescription: "Jede App hat eine eigene Nutzerpsychologie. So strukturierst du deine Aktivitätsfotos für möglichst gute Gespräche auf den wichtigsten Dating-Apps.",
  promptTip: "Prompt-Tipp:",
  tinderGuide: "Tinder-Fotoleitfaden",
  hingeGuide: "Hinge-Fotoleitfaden",
  bumbleGuide: "Bumble-Fotoleitfaden",
  datingPhotosPillar: "Übersicht Dating-Fotos",
  consistentEyebrow: "Zusammenhängende 4er-Shootings",
  consistentHeading: "So erstellt UnrealShot vollständige Lifestyle-Szenen",
  consistentDescription: "Jedes generierte Shooting liefert 4 koordinierte Aufnahmen: Opener, Halbfigur, Ganzkörper und spontan. An diesen echten Lifestyle-Beispielen siehst du, wie Licht, Kleidung und Umgebung zusammenpassen.",
  exploreExamples: "Alle Beispiele entdecken →",
  relatedFrames: "4 verbundene Aufnahmen",
  viewShoot: "Shooting-Details ansehen →",
  faqEyebrow: "Häufige Fragen",
  faqHeading: "FAQ zu Aktivitäts- und Lifestyle-Fotos",
  faqDescription: "Expertenrat zur Auswahl, Platzierung und Erstellung natürlicher Aktivitätsfotos für moderne Dating-Apps.",
  priceEyebrow: "39 $ einmalig · Kein Abo · Lieferung in 30 Minuten",
  finalHeading: "Stelle heute deine vollständige Dating-Fotoauswahl zusammen",
  finalDescription: "Verwandle 4–6 Referenz-Selfies in 15 abwechslungsreiche Lifestyle-Shootings und 60 hochauflösende Fotos inklusive 15 einzelner Foto-Neuerstellungen.",
  mistakeLabel: "Der Fehler:",
  fixLabel: "Die Lösung:",
  ruleLabel: "REGEL",
}

const ptBRUi: ActivityPageUi = {
  createPhotos: "Criar minhas fotos de atividade",
  exploreStyles: "Explorar os 5 principais estilos de hobby ↓",
  deliveryNote: "Semelhança guiada por referências · 15 ensaios · 60 fotos entregues em 30 minutos.",
  cameraRollEyebrow: "A armadilha da galeria",
  cameraRollHeading: "Por que as fotos de hobbies de muitos homens falham nos aplicativos de namoro",
  cameraRollDescription: "Ao passar por um perfil, as pessoas procuram pistas sobre seu estilo de vida e sua personalidade reais. Fotos de atividade fracas escondem sua aparência ou enviam sinais sociais errados.",
  whatWorksEyebrow: "O que realmente funciona",
  categoriesHeading: "Os 5 melhores estilos de fotos de hobbies para homens",
  categoriesDescription: "Estas categorias costumam gerar mais respostas porque equilibram atratividade natural, proximidade e assuntos fáceis para conversar.",
  fullGallery: "Ver a galeria completa →",
  categoryLabel: "CATEGORIA",
  shootSuffix: "ensaio",
  framingTip: "Dica de enquadramento e foto:",
  promptPairing: "Melhor combinação com um prompt:",
  viewFrames: "Ver os 4 enquadramentos deste ensaio",
  blueprintEyebrow: "Guia de fotografia",
  rulesHeading: "4 regras para fotos de estilo de vida convincentes",
  rulesDescription: "Se você tirar essas fotos ou gerá-las com a UnrealShot, siga estes princípios para que sua seleção pareça natural, feita por um amigo e autêntica.",
  doLabel: "FAÇA:",
  doNotLabel: "EVITE:",
  placementEyebrow: "Guia de posicionamento nos aplicativos",
  placementHeading: "Onde colocar fotos de atividade no Hinge, Tinder e Bumble",
  placementDescription: "Cada aplicativo tem uma psicologia própria. Veja como organizar suas fotos de atividade para favorecer conversas nos principais aplicativos de namoro.",
  promptTip: "Dica de prompt:",
  tinderGuide: "Guia de fotos do Tinder",
  hingeGuide: "Guia de fotos do Hinge",
  bumbleGuide: "Guia de fotos do Bumble",
  datingPhotosPillar: "Página principal de fotos para namoro",
  consistentEyebrow: "Ensaios consistentes de 4 imagens",
  consistentHeading: "Veja como a UnrealShot constrói cenas completas de estilo de vida",
  consistentDescription: "Cada ensaio gerado entrega 4 imagens coordenadas: abertura, meio corpo, corpo inteiro e espontânea. Explore estes exemplos para ver como luz, roupa e ambiente permanecem coerentes.",
  exploreExamples: "Explorar todos os exemplos →",
  relatedFrames: "4 imagens relacionadas",
  viewShoot: "Ver detalhes do ensaio →",
  faqEyebrow: "Perguntas frequentes",
  faqHeading: "FAQ sobre fotos de atividade e estilo de vida",
  faqDescription: "Conselhos de especialistas para escolher, posicionar e gerar fotos de atividade naturais para os aplicativos de namoro atuais.",
  priceEyebrow: "US$ 39 uma vez · Sem assinatura · entrega em 30 min",
  finalHeading: "Monte hoje seu conjunto completo de fotos para namoro",
  finalDescription: "Transforme 4–6 selfies de referência em 15 ensaios variados de estilo de vida e 60 fotos em alta resolução, com 15 refações individuais.",
  mistakeLabel: "O erro:",
  fixLabel: "A solução:",
  ruleLabel: "REGRA",
}

type TranslationMap = Record<string, string>

const frText: TranslationMap = {
  "Dating Profile Lifestyle & Activity Guide": "Guide du style de vie et des activités pour les profils de rencontre",
  "Activity & Hobby Dating Photos for Men That Actually Spark Conversations": "Photos d’activité et de loisirs pour hommes qui suscitent vraiment des conversations",
  "Learn how to choose and shoot believable activity photos for Tinder, Hinge, and Bumble. Discover the 5 best hobby categories, framing rules, and common mistakes to avoid.": "Apprenez à choisir et à créer des photos d’activité crédibles pour Tinder, Hinge et Bumble. Découvrez les 5 meilleures catégories de loisirs, les règles de cadrage et les erreurs courantes à éviter.",
  "An activity photo gives potential matches an instant visual conversation starter and proves you have a vibrant, rounded life. The best activity photos show genuine interests—like cooking, fitness, coffee, or city exploration—captured in natural lighting with an unobstructed face, avoiding staged mirror selfies or obscured action shots.": "Une photo d’activité donne immédiatement un sujet de conversation visuel et montre que votre vie est riche et variée. Les meilleures photos présentent des intérêts réels — cuisine, sport, café ou découverte de la ville — dans une lumière naturelle, avec le visage dégagé, sans selfie miroir mis en scène ni action qui le cache.",
  "5 high-converting hobby categories for men": "5 catégories de loisirs qui favorisent les échanges",
  "How to showcase fitness without cringey gym selfies": "Montrer sa forme sans selfie gênant à la salle",
  "Pairing lifestyle photos with Hinge & Bumble prompts": "Associer des photos de vie à des prompts Hinge et Bumble",
  "15 coherent AI lifestyle shoots generated in 30 minutes": "15 séances de vie cohérentes générées par IA en 30 minutes",
  "Conversation Starters": "Sujets de conversation",
  "4x more openers on Hinge": "4 fois plus d’ouvertures sur Hinge",
  "Optimal Lineup Balance": "Équilibre idéal de la sélection",
  "1–2 activity shots in 6 photos": "1 à 2 photos d’activité sur 6",
  "Face Visibility": "Visibilité du visage",
  "Eyes & smile must stay clear": "Les yeux et le sourire doivent rester visibles",
  "Delivery Turnaround": "Délai de livraison",
  "60 photos in 30 minutes": "60 photos en 30 minutes",
  "The Obscured Face Trap": "Le piège du visage caché",
  "Skiing with goggles, motorcycle helmets, or distant mountain climbing shots where you are just a 10-pixel silhouette.": "Le ski avec lunettes, les casques de moto ou les photos d’escalade prises de loin où vous n’êtes qu’une silhouette minuscule.",
  "The activity should provide setting and context, but your facial features and expression must remain recognizable.": "L’activité doit apporter un décor et un contexte, mais vos traits et votre expression doivent rester reconnaissables.",
  "The Aggressive Mirror Flex": "Le selfie miroir trop démonstratif",
  "Overly posed bathroom or locker-room gym selfies with harsh fluorescent overhead light and intense grimacing.": "Les selfies très posés dans une salle de bain ou un vestiaire, sous un néon dur, avec une grimace concentrée.",
  "Capture natural, mid-workout moments in a daylight-filled space—resting between sets or adjusting gear—looking relaxed rather than performative.": "Capturez un moment naturel au milieu de l’entraînement dans un espace lumineux : repos entre deux séries ou réglage du matériel, avec un air détendu plutôt que théâtral.",
  "The Manufactured Persona": "La personnalité fabriquée",
  "Posing with rented supercars, champagne bottles, or hobbies you don't actually do just to project status.": "Poser avec une voiture de luxe louée, une bouteille de champagne ou un loisir que vous ne pratiquez pas pour afficher un statut.",
  "Stick strictly to things you actually enjoy and could comfortably discuss for 30 minutes on a first date.": "Restez strictement sur des choses que vous aimez réellement et dont vous pourriez parler naturellement pendant 30 minutes lors d’un premier rendez-vous.",
  "Home Cooking & Culinary Craft": "Cuisine maison et savoir-faire culinaire",
  "Warm, capable, domestic competence": "Chaleureux, habile, à l’aise au quotidien",
  "Cooking is universally attractive and conveys warmth, creativity, and self-sufficiency. It gives your match an effortless opening line about favorite recipes or date-night meals.": "La cuisine est largement appréciée et suggère chaleur, créativité et autonomie. Elle donne naturellement à votre match un sujet sur vos recettes préférées ou un dîner à deux.",
  "Capture a casual mid-prep moment at a kitchen counter with natural window lighting rather than posing stiffly holding a completed plate.": "Capturez un moment décontracté pendant la préparation, au comptoir et près d’une fenêtre, plutôt que de tenir raide une assiette terminée.",
  "Pairs perfectly with Hinge's 'The secret to getting along with me' or 'My specialty dish'.": "S’accorde parfaitement avec les prompts Hinge « Le secret pour bien s’entendre avec moi » ou « Ma spécialité ».",
  "Active Lifestyle & Fitness": "Mode de vie actif et sport",
  "Discipline, energy, healthy routine": "Discipline, énergie, routine saine",
  "Demonstrates physical vitality and commitment to wellbeing without needing an aggressive shirtless mirror picture. Shows you take care of yourself.": "Montre votre vitalité et votre attention au bien-être sans nécessiter un selfie torse nu agressif. Cela montre que vous prenez soin de vous.",
  "Use daylight gyms, outdoor running paths, or bouldering walls. Keep expressions natural or smiling rather than straining under heavy weight.": "Choisissez une salle lumineuse, un chemin de course extérieur ou un mur d’escalade. Gardez une expression naturelle ou souriante plutôt que crispée sous un poids lourd.",
  "Great for Bumble's 'Active' badge or Hinge's 'Sunday routine' prompt.": "Très adapté au badge « Actif » de Bumble ou au prompt Hinge « Ma routine du dimanche ».",
  "Café Culture & Reading": "Culture des cafés et lecture",
  "Approachable, conversational, relaxed": "Accessible, bavard, détendu",
  "A neighborhood café terrace or cozy bookstore corner signals intellectual curiosity, calmness, and low-pressure date potential.": "La terrasse d’un café de quartier ou le coin chaleureux d’une librairie suggère curiosité intellectuelle, calme et possibilité d’un rendez-vous sans pression.",
  "Sit at a table in open shade, holding a warm cup or glancing away from a book with a slight, natural reaction.": "Asseyez-vous à une table à l’ombre, tenez une boisson chaude ou détournez légèrement le regard d’un livre avec une réaction naturelle.",
  "Pairs seamlessly with 'Best spot in town' or 'Together we could find the best coffee'.": "S’accorde naturellement avec « Le meilleur endroit de la ville » ou « On pourrait trouver le meilleur café ».",
  "Urban Exploration & Street Life": "Exploration urbaine et vie de rue",
  "Curiosity, style, modern vitality": "Curiosité, style, énergie moderne",
  "Shows you enjoy exploring your city, visiting markets, architecture, or galleries. Naturally displays full-length posture, height, and street style.": "Montre que vous aimez explorer votre ville, ses marchés, son architecture ou ses galeries. Le cadrage en pied présente naturellement votre posture, votre taille et votre style urbain.",
  "Walk down a textured pedestrian street with natural movement and casual layering (overshirt, knit, or clean jacket).": "Marchez dans une rue piétonne texturée avec un mouvement naturel et des couches décontractées : surchemise, maille ou veste nette.",
  "Ideal for 'A quick rant about' or 'Let's debate: best neighborhood'.": "Idéal pour « Un sujet sur lequel je peux râler » ou « Débattons : le meilleur quartier ».",
  "Coastal & Nature Walks": "Promenades côtières et dans la nature",
  "Adventurous, open, grounded": "Aventureux, ouvert, ancré",
  "Brings fresh air and scenery into your lineup. Signals you enjoy the outdoors and weekend getaways without requiring extreme mountaineering gear.": "Apporte de l’air frais et du paysage à votre sélection. Montre que vous aimez le plein air et les escapades sans nécessiter de matériel d’alpinisme extrême.",
  "Shoot during golden hour or bright overcast daylight along a scenic coastal path or trail, with wind-blown natural movement.": "Photographiez à l’heure dorée ou sous une lumière couverte mais claire, sur un chemin côtier ou un sentier, avec un mouvement naturel dans le vent.",
  "Pairs well with 'All I ask is that you' or 'My simple pleasures'.": "S’accorde bien avec « Tout ce que je demande, c’est que tu » ou « Mes petits plaisirs ».",
  "The Subject is Always You, Not the Activity": "Le sujet, c’est toujours vous, pas l’activité",
  "The hobby is the backdrop that provides flavor and conversation material; you are still the focus. Avoid photos where the equipment, scenic vista, or sports car takes up 90% of the frame while you are an afterthought.": "Le loisir sert de décor et fournit un sujet de conversation ; vous restez le point focal. Évitez que le matériel, le paysage ou la voiture de sport occupe 90 % de l’image pendant que vous devenez secondaire.",
  "A half-body shot of you prepping ingredients at a counter with a visible, relaxed smile.": "Une photo buste où vous préparez des ingrédients au comptoir avec un sourire détendu et visible.",
  "A wide-angle shot of a pizza oven where your back is turned and your face cannot be seen.": "Un grand-angle sur un four à pizza où vous êtes de dos et où votre visage est invisible.",
  "Action Over Posing (The 70/30 Candid Rule)": "L’action plutôt que la pose (la règle spontanée 70/30)",
  "Great activity photos capture you in motion or in a moment of pause during an activity. Staring dead-center into the lens with two hands on a prop often feels like a stock photo.": "Les bonnes photos d’activité vous montrent en mouvement ou dans une pause de l’action. Fixer l’objectif avec les deux mains sur un accessoire donne souvent l’impression d’une banque d’images.",
  "Looking slightly off-camera while laughing, adjusting headphones, or tying running shoes.": "Regarder légèrement hors champ en riant, ajuster un casque audio ou nouer ses chaussures de course.",
  "Holding a guitar like a prop while staring unblinkingly at the lens.": "Tenir une guitare comme un accessoire en fixant l’objectif sans cligner des yeux.",
  "Match Your Photos to Your Stated Interests": "Faites correspondre vos photos à vos intérêts déclarés",
  "Dating apps algorithmically reward consistency between your photo tags, prompt answers, and actual visual evidence. When your photos confirm your written bio, trust levels surge.": "Les applications valorisent la cohérence entre vos tags photo, vos réponses aux prompts et les preuves visuelles. Quand les photos confirment votre bio, la confiance augmente.",
  "Mentioning you love trying new brunch spots and having an outdoor coffee terrace photo.": "Dire que vous aimez tester de nouveaux brunchs et montrer une photo en terrasse autour d’un café.",
  "Saying you love nature while all six photos are taken in dark nightclubs or indoor bedrooms.": "Dire que vous aimez la nature alors que les six photos sont prises dans des boîtes de nuit sombres ou des chambres.",
  "Lighting Dictates Realism": "La lumière détermine le réalisme",
  "Avoid harsh flash or dim yellow indoor light. Natural open shade, soft morning daylight, or warm ambient restaurant lighting keeps photos looking professional yet friend-taken.": "Évitez le flash dur ou la lumière intérieure jaune et faible. Une ombre ouverte naturelle, une lumière douce du matin ou l’ambiance chaude d’un restaurant gardent un rendu soigné mais pris par un proche.",
  "Diffused window light casting soft shadows across your face.": "Une lumière de fenêtre diffuse qui projette des ombres douces sur votre visage.",
  "Direct flash in a dark room casting harsh glare and greasy skin reflections.": "Un flash direct dans une pièce sombre qui crée des reflets durs et brillants sur la peau.",
  "Photo #2, #3, or #5": "Photo n° 2, 3 ou 5",
  "On Hinge, every photo can be paired with a caption or audio snippet. Position your activity photo immediately above or below a prompt that references your lifestyle (e.g., cooking or weekend routines) to give matches an effortless way to leave a comment.": "Sur Hinge, chaque photo peut être associée à une légende ou un extrait audio. Placez votre photo d’activité près d’un prompt lié à votre mode de vie, comme la cuisine ou vos week-ends, pour faciliter les commentaires.",
  "Use the 'My happy place is...' or 'Together we could...' prompts right next to your hobby photo.": "Placez votre photo près des prompts « Mon endroit préféré est… » ou « Ensemble, nous pourrions… ».",
  "Photo #3 or #4": "Photo n° 3 ou 4",
  "Tinder is fast-paced. Your opener must be a crystal-clear portrait, followed by a full-length photo. Place your activity shot in the middle slots to prove active lifestyle, build, and conversational depth before the profile closes.": "Tinder est rapide. Votre ouverture doit être un portrait très clair, suivi d’une photo en pied. Placez l’activité au milieu pour montrer votre mode de vie, votre silhouette et votre profondeur avant la fin du profil.",
  "Ensure your Spotify top artists and lifestyle tags align with the mood of your activity photo.": "Vérifiez que vos artistes préférés Spotify et vos tags de mode de vie correspondent à l’ambiance de la photo.",
  "Photo #2 or #4": "Photo n° 2 ou 4",
  "Because women message first on Bumble, providing easy 'message hooks' is critical. An intriguing hobby photo (like pour-over coffee, cooking, or trail walking) gives her something specific and comfortable to write about in her opening message.": "Puisque les femmes écrivent en premier sur Bumble, il est essentiel d’offrir des « accroches » faciles. Une photo de loisir intéressante, comme le café filtre, la cuisine ou la marche, lui donne un sujet précis pour son premier message.",
  "Link your Bumble lifestyle badges (e.g., Cooking, Fitness, Travel) to visual evidence in your photos.": "Faites correspondre vos badges Bumble, comme Cuisine, Sport ou Voyage, avec des preuves visuelles dans vos photos.",
  "What are the best hobby photos for men on dating apps?": "Quelles sont les meilleures photos de loisirs pour les hommes sur les applications de rencontre ?",
  "The top-performing hobby photos are accessible, social, and warm: home cooking, café/coffee culture, natural fitness (running, training floor), city exploration/arts, and scenic travel. Avoid hobbies with negative associations or low face visibility, such as gaming screens, hunting/fishing trophies, or car engine bays.": "Les meilleures photos de loisirs sont accessibles, sociales et chaleureuses : cuisine maison, cafés, sport naturel, découverte de la ville et voyages panoramiques. Évitez les sujets associés négativement ou qui cachent le visage, comme les écrans de jeux, les trophées de chasse ou les moteurs de voiture.",
  "Are gym photos bad to use on Tinder, Hinge, or Bumble?": "Les photos de salle sont-elles mauvaises sur Tinder, Hinge ou Bumble ?",
  "Bathroom and locker-room mirror selfies are universally disliked because they look posed and self-absorbed. However, a naturally lit training photo—such as resting between sets on a gym floor or running outdoors—works very well if fitness is a genuine part of your routine. Keep it to one photo maximum in your lineup.": "Les selfies miroir dans la salle de bain ou les vestiaires sont mal perçus car ils paraissent posés et égocentrés. Une photo d’entraînement en lumière naturelle, par exemple entre deux séries ou en courant dehors, fonctionne si le sport fait vraiment partie de votre routine. Limitez-vous à une seule photo.",
  "How do I get natural activity photos if I don't have someone to take them?": "Comment obtenir des photos d’activité naturelles si personne ne peut les prendre ?",
  "You have three options: 1) Set a phone tripod with a 10-second timer or burst mode in natural light. 2) Ask a friend during an actual outing (e.g. coffee or a walk). 3) Use UnrealShot AI to turn 4–6 reference selfies into 15 varied lifestyle shoots (like home cooking, outdoor coffee, gym training, and city walks) within 30 minutes.": "Vous avez trois options : 1) utiliser un trépied de téléphone avec retardateur de 10 secondes ou mode rafale en lumière naturelle ; 2) demander à un ami pendant une vraie sortie, comme un café ou une promenade ; 3) utiliser UnrealShot pour transformer 4 à 6 selfies de référence en 15 séances variées, comme cuisine maison, café, sport et promenade, sous 30 minutes.",
  "How many activity photos should be in a 6-photo dating lineup?": "Combien de photos d’activité faut-il dans une sélection de six photos ?",
  "One to two activity photos is the sweet spot. Your profile needs a clear solo portrait opener, a full-length body shot, 1–2 genuine activity photos, a dressed-up or social context shot, and an everyday candid. Having more than two activity shots can make the profile feel cluttered or one-dimensional.": "Une à deux photos d’activité est un bon équilibre. Votre profil a besoin d’un portrait solo clair, d’une photo en pied, d’une à deux activités réelles, d’un contexte habillé ou social et d’une photo spontanée du quotidien. Au-delà de deux, le profil peut sembler chargé ou monotone.",
  "Should I include group sports or solo hobbies?": "Faut-il montrer un sport collectif ou un loisir individuel ?",
  "Solo or small-context hobbies work best. Group sports often make it difficult for potential matches to identify which person you are. If you participate in team sports, use a solo photo of you on the sidelines or in gear rather than a crowded team huddle.": "Les loisirs individuels ou en petit contexte fonctionnent mieux. Les sports collectifs rendent souvent votre identification difficile. Si vous pratiquez un sport d’équipe, utilisez une photo solo sur le côté du terrain ou en tenue plutôt qu’une mêlée de groupe.",
  "How does UnrealShot generate authentic activity shoots without looking fake?": "Comment UnrealShot génère-t-elle des séances d’activité naturelles ?",
  "UnrealShot uses reference-guided likeness to maintain your facial features while generating 15 distinct shoots with 4 related frames each (close, half-body, full-length, candid). The lighting, clothing, and environment are designed around believable everyday settings (like home kitchens, modern gyms, and outdoor cafes) with friend-taken camera angles.": "UnrealShot utilise une ressemblance guidée par références pour préserver vos traits et générer 15 séances distinctes de 4 images liées chacune : rapprochée, buste, pied et spontanée. La lumière, la tenue et le décor s’appuient sur des cadres quotidiens crédibles, comme une cuisine, une salle moderne ou un café extérieur, avec des angles comme pris par un proche.",
  "What hobbies should men avoid on dating profiles?": "Quels loisirs les hommes devraient-ils éviter sur un profil de rencontre ?",
  "Avoid photos holding dead fish or game, photos where your face is completely concealed by helmets/goggles, pictures of your car without you in it, nightclub partying with red-eye flash, and messy room backgrounds.": "Évitez les photos avec des poissons ou du gibier morts, celles où le visage est caché par un casque ou des lunettes, les voitures photographiées sans vous, les soirées en boîte au flash rouge et les arrière-plans de chambre désordonnés.",
  "How do activity photos improve dating app match rates?": "Comment les photos d’activité améliorent-elles un profil de rencontre ?",
  "Activity photos increase match quality and conversation rates because they provide context for your personality. On apps like Hinge, photos showing a specific activity receive over 4x more incoming comments than generic selfies because they make starting a conversation frictionless.": "Les photos d’activité donnent du contexte à votre personnalité et peuvent améliorer la qualité des échanges. Sur des applications comme Hinge, une activité précise offre un sujet de conversation plus simple qu’un selfie générique.",
}

const esText: TranslationMap = {
  "Dating Profile Lifestyle & Activity Guide": "Guía de estilo de vida y actividades para perfiles de citas",
  "Activity & Hobby Dating Photos for Men That Actually Spark Conversations": "Fotos de actividades y hobbies para hombres que sí generan conversaciones",
  "Learn how to choose and shoot believable activity photos for Tinder, Hinge, and Bumble. Discover the 5 best hobby categories, framing rules, and common mistakes to avoid.": "Aprende a elegir y crear fotos de actividades creíbles para Tinder, Hinge y Bumble. Descubre las 5 mejores categorías de hobbies, las reglas de encuadre y los errores habituales que debes evitar.",
  "An activity photo gives potential matches an instant visual conversation starter and proves you have a vibrant, rounded life. The best activity photos show genuine interests—like cooking, fitness, coffee, or city exploration—captured in natural lighting with an unobstructed face, avoiding staged mirror selfies or obscured action shots.": "Una foto de actividad ofrece a tus posibles matches un tema de conversación visual inmediato y demuestra que tienes una vida variada. Las mejores fotos muestran intereses reales —cocina, fitness, café o explorar la ciudad— con luz natural y la cara visible, evitando selfies de espejo preparados o acciones que la oculten.",
  "5 high-converting hobby categories for men": "5 categorías de hobbies que generan conversaciones",
  "How to showcase fitness without cringey gym selfies": "Cómo mostrar fitness sin selfies incómodos del gimnasio",
  "Pairing lifestyle photos with Hinge & Bumble prompts": "Combinar fotos de estilo de vida con prompts de Hinge y Bumble",
  "15 coherent AI lifestyle shoots generated in 30 minutes": "15 sesiones de estilo de vida coherentes generadas con IA en 30 minutos",
  "Conversation Starters": "Temas de conversación",
  "4x more openers on Hinge": "4 veces más comentarios iniciales en Hinge",
  "Optimal Lineup Balance": "Equilibrio ideal del perfil",
  "1–2 activity shots in 6 photos": "1–2 fotos de actividad entre 6",
  "Face Visibility": "Visibilidad de la cara",
  "Eyes & smile must stay clear": "Los ojos y la sonrisa deben verse bien",
  "Delivery Turnaround": "Tiempo de entrega",
  "60 photos in 30 minutes": "60 fotos en 30 minutos",
  "The Obscured Face Trap": "La trampa de la cara oculta",
  "Skiing with goggles, motorcycle helmets, or distant mountain climbing shots where you are just a 10-pixel silhouette.": "Esquiar con gafas, llevar casco de moto o aparecer a lo lejos escalando una montaña hasta parecer una silueta de 10 píxeles.",
  "The activity should provide setting and context, but your facial features and expression must remain recognizable.": "La actividad debe aportar escenario y contexto, pero tus rasgos y tu expresión tienen que seguir siendo reconocibles.",
  "The Aggressive Mirror Flex": "El alarde agresivo frente al espejo",
  "Overly posed bathroom or locker-room gym selfies with harsh fluorescent overhead light and intense grimacing.": "Selfies demasiado posados en el baño o vestuario del gimnasio, con luz fluorescente dura desde arriba y una mueca intensa.",
  "Capture natural, mid-workout moments in a daylight-filled space—resting between sets or adjusting gear—looking relaxed rather than performative.": "Captura momentos naturales durante el entrenamiento en un espacio con luz de día: descansando entre series o ajustando el equipo, con aspecto relajado y no teatral.",
  "The Manufactured Persona": "La personalidad fabricada",
  "Posing with rented supercars, champagne bottles, or hobbies you don't actually do just to project status.": "Posar con supercoches alquilados, botellas de champán o hobbies que no practicas para proyectar estatus.",
  "Stick strictly to things you actually enjoy and could comfortably discuss for 30 minutes on a first date.": "Limítate a cosas que realmente disfrutas y de las que podrías hablar cómodamente durante 30 minutos en una primera cita.",
  "Home Cooking & Culinary Craft": "Cocina casera y creatividad culinaria",
  "Warm, capable, domestic competence": "Cercanía, habilidad y autonomía cotidiana",
  "Cooking is universally attractive and conveys warmth, creativity, and self-sufficiency. It gives your match an effortless opening line about favorite recipes or date-night meals.": "Cocinar resulta atractivo y transmite cercanía, creatividad y autonomía. Da a tu match un tema fácil sobre recetas favoritas o cenas para dos.",
  "Capture a casual mid-prep moment at a kitchen counter with natural window lighting rather than posing stiffly holding a completed plate.": "Captura un momento informal mientras preparas algo en la encimera, con luz natural de ventana, en vez de posar rígido sosteniendo un plato terminado.",
  "Pairs perfectly with Hinge's 'The secret to getting along with me' or 'My specialty dish'.": "Combina muy bien con los prompts de Hinge «El secreto para llevarte bien conmigo» o «Mi plato estrella».",
  "Active Lifestyle & Fitness": "Estilo de vida activo y fitness",
  "Discipline, energy, healthy routine": "Disciplina, energía y rutina saludable",
  "Demonstrates physical vitality and commitment to wellbeing without needing an aggressive shirtless mirror picture. Shows you take care of yourself.": "Demuestra vitalidad física y compromiso con tu bienestar sin necesitar una foto agresiva sin camiseta frente al espejo. Muestra que te cuidas.",
  "Use daylight gyms, outdoor running paths, or bouldering walls. Keep expressions natural or smiling rather than straining under heavy weight.": "Usa gimnasios con luz natural, caminos para correr o paredes de escalada. Mantén una expresión natural o sonriente, no de esfuerzo exagerado bajo mucho peso.",
  "Great for Bumble's 'Active' badge or Hinge's 'Sunday routine' prompt.": "Perfecto para la insignia «Activo» de Bumble o el prompt «Rutina del domingo» de Hinge.",
  "Café Culture & Reading": "Cultura del café y lectura",
  "Approachable, conversational, relaxed": "Cercano, conversador y relajado",
  "A neighborhood café terrace or cozy bookstore corner signals intellectual curiosity, calmness, and low-pressure date potential.": "La terraza de un café de barrio o un rincón acogedor de una librería transmiten curiosidad intelectual, calma y una posible cita sin presión.",
  "Sit at a table in open shade, holding a warm cup or glancing away from a book with a slight, natural reaction.": "Siéntate a una mesa en sombra abierta, sostén una taza caliente o aparta la mirada del libro con una reacción leve y natural.",
  "Pairs seamlessly with 'Best spot in town' or 'Together we could find the best coffee'.": "Combina muy bien con «El mejor sitio de la ciudad» o «Juntos podríamos encontrar el mejor café».",
  "Urban Exploration & Street Life": "Exploración urbana y vida de calle",
  "Curiosity, style, modern vitality": "Curiosidad, estilo y energía moderna",
  "Shows you enjoy exploring your city, visiting markets, architecture, or galleries. Naturally displays full-length posture, height, and street style.": "Muestra que disfrutas explorando tu ciudad, sus mercados, arquitectura o galerías. Enseña de forma natural tu postura, altura y estilo urbano.",
  "Walk down a textured pedestrian street with natural movement and casual layering (overshirt, knit, or clean jacket).": "Camina por una calle peatonal con textura y movimiento natural, con capas informales como sobrecamisa, punto o una chaqueta sencilla.",
  "Ideal for 'A quick rant about' or 'Let's debate: best neighborhood'.": "Ideal para «Una pequeña queja sobre» o «Debatamos: el mejor barrio».",
  "Coastal & Nature Walks": "Paseos por la costa y la naturaleza",
  "Adventurous, open, grounded": "Aventurero, abierto y conectado con la realidad",
  "Brings fresh air and scenery into your lineup. Signals you enjoy the outdoors and weekend getaways without requiring extreme mountaineering gear.": "Añade aire libre y paisaje a tu selección. Señala que disfrutas de la naturaleza y las escapadas sin necesitar equipo de alpinismo extremo.",
  "Shoot during golden hour or bright overcast daylight along a scenic coastal path or trail, with wind-blown natural movement.": "Haz las fotos durante la hora dorada o con luz nublada clara junto a un camino costero o sendero, con movimiento natural del viento.",
  "Pairs well with 'All I ask is that you' or 'My simple pleasures'.": "Combina bien con «Solo pido que» o «Mis pequeños placeres».",
  "The Subject is Always You, Not the Activity": "El protagonista siempre eres tú, no la actividad",
  "The hobby is the backdrop that provides flavor and conversation material; you are still the focus. Avoid photos where the equipment, scenic vista, or sports car takes up 90% of the frame while you are an afterthought.": "El hobby aporta ambiente y conversación, pero tú sigues siendo el centro. Evita fotos donde el equipo, el paisaje o el coche deportivo ocupen el 90 % del encuadre y tú seas secundario.",
  "A half-body shot of you prepping ingredients at a counter with a visible, relaxed smile.": "Una foto de medio cuerpo preparando ingredientes en la encimera con una sonrisa relajada y visible.",
  "A wide-angle shot of a pizza oven where your back is turned and your face cannot be seen.": "Un gran angular de un horno de pizza en el que estás de espaldas y no se ve tu cara.",
  "Action Over Posing (The 70/30 Candid Rule)": "Acción antes que pose (la regla espontánea 70/30)",
  "Great activity photos capture you in motion or in a moment of pause during an activity. Staring dead-center into the lens with two hands on a prop often feels like a stock photo.": "Las buenas fotos de actividad te capturan en movimiento o en una pausa. Mirar fijamente al objetivo con las dos manos sobre un objeto suele parecer una foto de catálogo.",
  "Looking slightly off-camera while laughing, adjusting headphones, or tying running shoes.": "Mirar un poco fuera de cámara mientras ríes, ajustas unos auriculares o atas tus zapatillas.",
  "Holding a guitar like a prop while staring unblinkingly at the lens.": "Sostener una guitarra como atrezzo mientras miras fijamente al objetivo sin parpadear.",
  "Match Your Photos to Your Stated Interests": "Haz que tus fotos coincidan con tus intereses declarados",
  "Dating apps algorithmically reward consistency between your photo tags, prompt answers, and actual visual evidence. When your photos confirm your written bio, trust levels surge.": "Las aplicaciones valoran la coherencia entre tus etiquetas, tus respuestas y la evidencia visual. Cuando tus fotos confirman tu biografía, aumenta la confianza.",
  "Mentioning you love trying new brunch spots and having an outdoor coffee terrace photo.": "Decir que te encanta probar sitios nuevos de brunch y mostrar una foto en una terraza tomando café.",
  "Saying you love nature while all six photos are taken in dark nightclubs or indoor bedrooms.": "Decir que amas la naturaleza mientras las seis fotos están tomadas en discotecas oscuras o dormitorios.",
  "Lighting Dictates Realism": "La luz determina el realismo",
  "Avoid harsh flash or dim yellow indoor light. Natural open shade, soft morning daylight, or warm ambient restaurant lighting keeps photos looking professional yet friend-taken.": "Evita el flash duro o la luz interior amarilla y tenue. La sombra abierta, la luz suave de la mañana o la luz cálida de un restaurante mantienen un aspecto cuidado pero tomado por un amigo.",
  "Diffused window light casting soft shadows across your face.": "Luz difusa de una ventana que proyecta sombras suaves sobre tu cara.",
  "Direct flash in a dark room casting harsh glare and greasy skin reflections.": "Flash directo en una habitación oscura que crea brillos fuertes y reflejos grasos en la piel.",
  "Photo #2, #3, or #5": "Foto n.º 2, 3 o 5",
  "On Hinge, every photo can be paired with a caption or audio snippet. Position your activity photo immediately above or below a prompt that references your lifestyle (e.g., cooking or weekend routines) to give matches an effortless way to leave a comment.": "En Hinge, cada foto puede acompañarse de un texto o audio. Coloca tu foto de actividad junto a un prompt sobre tu estilo de vida, como cocinar o tus rutinas del fin de semana, para facilitar los comentarios.",
  "Use the 'My happy place is...' or 'Together we could...' prompts right next to your hobby photo.": "Coloca junto a tu foto los prompts «Mi lugar feliz es…» o «Juntos podríamos…».",
  "Photo #3 or #4": "Foto n.º 3 o 4",
  "Tinder is fast-paced. Your opener must be a crystal-clear portrait, followed by a full-length photo. Place your activity shot in the middle slots to prove active lifestyle, build, and conversational depth before the profile closes.": "Tinder es rápido. Tu apertura debe ser un retrato muy claro, seguido de una foto de cuerpo entero. Coloca la actividad en las posiciones centrales para mostrar estilo de vida, complexión y profundidad.",
  "Ensure your Spotify top artists and lifestyle tags align with the mood of your activity photo.": "Asegúrate de que tus artistas principales de Spotify y tus etiquetas coincidan con el ambiente de la foto.",
  "Photo #2 or #4": "Foto n.º 2 o 4",
  "Because women message first on Bumble, providing easy 'message hooks' is critical. An intriguing hobby photo (like pour-over coffee, cooking, or trail walking) gives her something specific and comfortable to write about in her opening message.": "Como las mujeres escriben primero en Bumble, es importante ofrecer temas fáciles para iniciar un mensaje. Una foto interesante de café filtrado, cocina o paseo le da algo concreto y cómodo sobre lo que escribir.",
  "Link your Bumble lifestyle badges (e.g., Cooking, Fitness, Travel) to visual evidence in your photos.": "Relaciona tus insignias de Bumble, como Cocina, Fitness o Viajes, con evidencias visuales en tus fotos.",
  "What are the best hobby photos for men on dating apps?": "¿Cuáles son las mejores fotos de hobbies para hombres en aplicaciones de citas?",
  "The top-performing hobby photos are accessible, social, and warm: home cooking, café/coffee culture, natural fitness (running, training floor), city exploration/arts, and scenic travel. Avoid hobbies with negative associations or low face visibility, such as gaming screens, hunting/fishing trophies, or car engine bays.": "Las fotos de hobbies que mejor funcionan son accesibles, sociales y cálidas: cocinar en casa, cafés, fitness natural, explorar la ciudad y viajes con paisaje. Evita temas con asociaciones negativas o poca visibilidad de la cara, como pantallas de videojuegos, trofeos de caza o motores de coches.",
  "Are gym photos bad to use on Tinder, Hinge, or Bumble?": "¿Es mala idea usar fotos del gimnasio en Tinder, Hinge o Bumble?",
  "Bathroom and locker-room mirror selfies are universally disliked because they look posed and self-absorbed. However, a naturally lit training photo—such as resting between sets on a gym floor or running outdoors—works very well if fitness is a genuine part of your routine. Keep it to one photo maximum in your lineup.": "Los selfies de espejo en baños y vestuarios suelen gustar poco porque parecen posados y egocéntricos. Una foto de entrenamiento con luz natural, descansando entre series o corriendo al aire libre, funciona si el fitness forma parte real de tu rutina. Usa como máximo una.",
  "How do I get natural activity photos if I don't have someone to take them?": "¿Cómo consigo fotos naturales de actividad si no tengo a quién pedírselas?",
  "You have three options: 1) Set a phone tripod with a 10-second timer or burst mode in natural light. 2) Ask a friend during an actual outing (e.g. coffee or a walk). 3) Use UnrealShot AI to turn 4–6 reference selfies into 15 varied lifestyle shoots (like home cooking, outdoor coffee, gym training, and city walks) within 30 minutes.": "Tienes tres opciones: 1) usar un trípode con temporizador de 10 segundos o ráfaga con luz natural; 2) pedir ayuda a un amigo durante una salida real, como un café o paseo; 3) usar UnrealShot para convertir 4–6 selfies de referencia en 15 sesiones variadas, como cocina, café, gimnasio y ciudad, en 30 minutos.",
  "How many activity photos should be in a 6-photo dating lineup?": "¿Cuántas fotos de actividad debe tener una selección de seis fotos?",
  "One to two activity photos is the sweet spot. Your profile needs a clear solo portrait opener, a full-length body shot, 1–2 genuine activity photos, a dressed-up or social context shot, and an everyday candid. Having more than two activity shots can make the profile feel cluttered or one-dimensional.": "Una o dos fotos de actividad es el punto ideal. Tu perfil necesita un retrato solo claro, una foto de cuerpo entero, 1–2 actividades reales, un contexto arreglado o social y una foto espontánea cotidiana. Más de dos puede hacerlo parecer saturado o unidimensional.",
  "Should I include group sports or solo hobbies?": "¿Debo incluir deportes de equipo o hobbies individuales?",
  "Solo or small-context hobbies work best. Group sports often make it difficult for potential matches to identify which person you are. If you participate in team sports, use a solo photo of you on the sidelines or in gear rather than a crowded team huddle.": "Los hobbies individuales o de grupos pequeños funcionan mejor. Los deportes de equipo pueden dificultar que te identifiquen. Si practicas uno, usa una foto tuya solo en la banda o con el equipo, no una melé de grupo.",
  "How does UnrealShot generate authentic activity shoots without looking fake?": "¿Cómo genera UnrealShot sesiones de actividad naturales sin que parezcan falsas?",
  "UnrealShot uses reference-guided likeness to maintain your facial features while generating 15 distinct shoots with 4 related frames each (close, half-body, full-length, candid). The lighting, clothing, and environment are designed around believable everyday settings (like home kitchens, modern gyms, and outdoor cafes) with friend-taken camera angles.": "UnrealShot usa el parecido guiado por referencias para mantener tus rasgos mientras genera 15 sesiones distintas con 4 encuadres relacionados cada una: cercano, medio cuerpo, cuerpo entero y espontáneo. La luz, la ropa y el entorno parten de escenarios cotidianos creíbles, como cocinas, gimnasios modernos y cafés al aire libre, con ángulos de cámara naturales.",
  "What hobbies should men avoid on dating profiles?": "¿Qué hobbies deberían evitar los hombres en sus perfiles?",
  "Avoid photos holding dead fish or game, photos where your face is completely concealed by helmets/goggles, pictures of your car without you in it, nightclub partying with red-eye flash, and messy room backgrounds.": "Evita fotos con peces o animales muertos, imágenes donde el casco o las gafas oculten por completo tu cara, fotos de tu coche sin ti, fiestas nocturnas con flash de ojos rojos y habitaciones desordenadas.",
  "How do activity photos improve dating app match rates?": "¿Cómo mejoran las fotos de actividad los resultados en aplicaciones de citas?",
  "Activity photos increase match quality and conversation rates because they provide context for your personality. On apps like Hinge, photos showing a specific activity receive over 4x more incoming comments than generic selfies because they make starting a conversation frictionless.": "Las fotos de actividad aportan contexto sobre tu personalidad y favorecen conversaciones de mayor calidad. En aplicaciones como Hinge, mostrar una actividad concreta ofrece un inicio de conversación más fácil que un selfie genérico.",
}

const deText: TranslationMap = {
  "Dating Profile Lifestyle & Activity Guide": "Leitfaden für Lifestyle- und Aktivitätsfotos im Dating-Profil",
  "Activity & Hobby Dating Photos for Men That Actually Spark Conversations": "Aktivitäts- und Hobbyfotos für Männer, die wirklich Gespräche anstoßen",
  "Learn how to choose and shoot believable activity photos for Tinder, Hinge, and Bumble. Discover the 5 best hobby categories, framing rules, and common mistakes to avoid.": "Erfahre, wie du glaubwürdige Aktivitätsfotos für Tinder, Hinge und Bumble auswählst und aufnimmst. Entdecke die fünf besten Hobby-Kategorien, Regeln für den Bildausschnitt und typische Fehler.",
  "An activity photo gives potential matches an instant visual conversation starter and proves you have a vibrant, rounded life. The best activity photos show genuine interests—like cooking, fitness, coffee, or city exploration—captured in natural lighting with an unobstructed face, avoiding staged mirror selfies or obscured action shots.": "Ein Aktivitätsfoto bietet Matches sofort einen visuellen Gesprächseinstieg und zeigt ein abwechslungsreiches Leben. Gute Aktivitätsfotos zeigen echte Interessen wie Kochen, Fitness, Kaffee oder Stadterkundung bei natürlichem Licht und mit sichtbarem Gesicht – ohne gestellte Spiegel-Selfies oder verdeckte Action.",
  "5 high-converting hobby categories for men": "5 Hobby-Kategorien, die Gespräche fördern",
  "How to showcase fitness without cringey gym selfies": "Fitness zeigen, ohne peinliche Gym-Selfies",
  "Pairing lifestyle photos with Hinge & Bumble prompts": "Lifestyle-Fotos mit Hinge- und Bumble-Prompts verbinden",
  "15 coherent AI lifestyle shoots generated in 30 minutes": "15 zusammenhängende KI-Lifestyle-Shootings in 30 Minuten",
  "Conversation Starters": "Gesprächseinstiege",
  "4x more openers on Hinge": "4-mal mehr erste Kommentare auf Hinge",
  "Optimal Lineup Balance": "Ideale Profilauswahl",
  "1–2 activity shots in 6 photos": "1–2 Aktivitätsfotos bei 6 Bildern",
  "Face Visibility": "Sichtbarkeit des Gesichts",
  "Eyes & smile must stay clear": "Augen und Lächeln müssen klar sichtbar sein",
  "Delivery Turnaround": "Lieferzeit",
  "60 photos in 30 minutes": "60 Fotos in 30 Minuten",
  "The Obscured Face Trap": "Die Falle des verdeckten Gesichts",
  "Skiing with goggles, motorcycle helmets, or distant mountain climbing shots where you are just a 10-pixel silhouette.": "Skifahren mit Brille, Motorradhelme oder weit entfernte Kletterfotos, auf denen du nur eine winzige Silhouette bist.",
  "The activity should provide setting and context, but your facial features and expression must remain recognizable.": "Die Aktivität soll Umgebung und Kontext liefern, aber deine Gesichtszüge und dein Ausdruck müssen erkennbar bleiben.",
  "The Aggressive Mirror Flex": "Das aggressive Spiegel-Selfie",
  "Overly posed bathroom or locker-room gym selfies with harsh fluorescent overhead light and intense grimacing.": "Übermäßig gestellte Bad- oder Umkleide-Selfies unter hartem Neonlicht und mit angestrengter Grimasse.",
  "Capture natural, mid-workout moments in a daylight-filled space—resting between sets or adjusting gear—looking relaxed rather than performative.": "Halte natürliche Momente während des Trainings in einem hellen Raum fest – beim Pausieren zwischen Sätzen oder Einstellen des Equipments – entspannt statt theatralisch.",
  "The Manufactured Persona": "Die erfundene Persönlichkeit",
  "Posing with rented supercars, champagne bottles, or hobbies you don't actually do just to project status.": "Mit gemieteten Supersportwagen, Champagner oder Hobbys posieren, die du gar nicht ausübst, nur um Status zu zeigen.",
  "Stick strictly to things you actually enjoy and could comfortably discuss for 30 minutes on a first date.": "Bleib bei Dingen, die du wirklich magst und über die du beim ersten Date 30 Minuten entspannt sprechen könntest.",
  "Home Cooking & Culinary Craft": "Kochen zu Hause und kulinarisches Können",
  "Warm, capable, domestic competence": "Herzlich, kompetent, alltagstauglich",
  "Cooking is universally attractive and conveys warmth, creativity, and self-sufficiency. It gives your match an effortless opening line about favorite recipes or date-night meals.": "Kochen wirkt vielseitig attraktiv und vermittelt Wärme, Kreativität und Selbstständigkeit. Es bietet einen leichten Gesprächseinstieg über Lieblingsrezepte oder ein Dinner-Date.",
  "Capture a casual mid-prep moment at a kitchen counter with natural window lighting rather than posing stiffly holding a completed plate.": "Halte einen lockeren Moment bei der Zubereitung an der Küchenzeile in natürlichem Fensterlicht fest, statt steif einen fertigen Teller zu präsentieren.",
  "Pairs perfectly with Hinge's 'The secret to getting along with me' or 'My specialty dish'.": "Passt perfekt zu Hinge-Prompts wie „Das Geheimnis, mit mir klarzukommen“ oder „Mein Spezialgericht“.",
  "Active Lifestyle & Fitness": "Aktiver Lebensstil und Fitness",
  "Discipline, energy, healthy routine": "Disziplin, Energie, gesunde Routine",
  "Demonstrates physical vitality and commitment to wellbeing without needing an aggressive shirtless mirror picture. Shows you take care of yourself.": "Zeigt körperliche Vitalität und dein Engagement für dein Wohlbefinden, ohne ein aggressives Shirtlos-Spiegelbild zu benötigen. Du zeigst, dass du auf dich achtest.",
  "Use daylight gyms, outdoor running paths, or bouldering walls. Keep expressions natural or smiling rather than straining under heavy weight.": "Nutze helle Fitnessstudios, Laufstrecken im Freien oder Boulderwände. Der Ausdruck sollte natürlich oder lächelnd sein, nicht angestrengt unter schwerem Gewicht.",
  "Great for Bumble's 'Active' badge or Hinge's 'Sunday routine' prompt.": "Passt gut zum Bumble-Badge „Aktiv“ oder zum Hinge-Prompt „Sonntagsroutine“.",
  "Café Culture & Reading": "Café-Kultur und Lesen",
  "Approachable, conversational, relaxed": "Zugänglich, gesprächig, entspannt",
  "A neighborhood café terrace or cozy bookstore corner signals intellectual curiosity, calmness, and low-pressure date potential.": "Eine Caféterrasse im Viertel oder eine gemütliche Ecke in einer Buchhandlung signalisiert geistige Neugier, Ruhe und ein entspanntes Date-Potenzial.",
  "Sit at a table in open shade, holding a warm cup or glancing away from a book with a slight, natural reaction.": "Sitz an einem Tisch im offenen Schatten, halte eine warme Tasse oder blicke mit einer kleinen natürlichen Reaktion von einem Buch auf.",
  "Pairs seamlessly with 'Best spot in town' or 'Together we could find the best coffee'.": "Passt gut zu „Bester Ort der Stadt“ oder „Zusammen könnten wir den besten Kaffee finden“.",
  "Urban Exploration & Street Life": "Stadterkundung und Straßenleben",
  "Curiosity, style, modern vitality": "Neugier, Stil, moderne Energie",
  "Shows you enjoy exploring your city, visiting markets, architecture, or galleries. Naturally displays full-length posture, height, and street style.": "Zeigt, dass du deine Stadt, Märkte, Architektur oder Galerien gern erkundest. Dabei werden Haltung, Größe und Streetstyle ganz natürlich sichtbar.",
  "Walk down a textured pedestrian street with natural movement and casual layering (overshirt, knit, or clean jacket).": "Geh mit natürlicher Bewegung durch eine strukturierte Fußgängerstraße und trage lässige Schichten wie Overshirt, Strick oder eine schlichte Jacke.",
  "Ideal for 'A quick rant about' or 'Let's debate: best neighborhood'.": "Ideal für „Ein kurzer Rant über“ oder „Diskutieren wir: der beste Stadtteil“.",
  "Coastal & Nature Walks": "Küsten- und Naturspaziergänge",
  "Adventurous, open, grounded": "Abenteuerlustig, offen, bodenständig",
  "Brings fresh air and scenery into your lineup. Signals you enjoy the outdoors and weekend getaways without requiring extreme mountaineering gear.": "Bringt frische Luft und Landschaft in deine Auswahl. Zeigt Freude an Natur und Wochenendausflügen, ohne extreme Bergsteigerausrüstung zu brauchen.",
  "Shoot during golden hour or bright overcast daylight along a scenic coastal path or trail, with wind-blown natural movement.": "Fotografiere zur goldenen Stunde oder bei hellem, bedecktem Tageslicht an einem Küstenweg oder Pfad mit natürlicher Bewegung im Wind.",
  "Pairs well with 'All I ask is that you' or 'My simple pleasures'.": "Passt gut zu „Alles, was ich verlange, ist, dass du“ oder „Meine kleinen Freuden“.",
  "The Subject is Always You, Not the Activity": "Das Motiv bist immer du, nicht die Aktivität",
  "The hobby is the backdrop that provides flavor and conversation material; you are still the focus. Avoid photos where the equipment, scenic vista, or sports car takes up 90% of the frame while you are an afterthought.": "Das Hobby liefert Hintergrund und Gesprächsstoff, aber du bleibst der Mittelpunkt. Vermeide Fotos, in denen Ausrüstung, Landschaft oder Sportwagen 90 % des Bildes einnehmen und du nur eine Nebenrolle spielst.",
  "A half-body shot of you prepping ingredients at a counter with a visible, relaxed smile.": "Eine Halbfigur beim Vorbereiten von Zutaten an der Küchenzeile mit sichtbarem, entspanntem Lächeln.",
  "A wide-angle shot of a pizza oven where your back is turned and your face cannot be seen.": "Eine Weitwinkelaufnahme eines Pizzaofens, bei der du mit dem Rücken zur Kamera stehst und dein Gesicht nicht zu sehen ist.",
  "Action Over Posing (The 70/30 Candid Rule)": "Action vor Pose (die 70/30-Spontanregel)",
  "Great activity photos capture you in motion or in a moment of pause during an activity. Staring dead-center into the lens with two hands on a prop often feels like a stock photo.": "Gute Aktivitätsfotos zeigen dich in Bewegung oder in einer Pause. Mit beiden Händen an einem Requisit starr in die Linse zu schauen wirkt oft wie ein Stockfoto.",
  "Looking slightly off-camera while laughing, adjusting headphones, or tying running shoes.": "Beim Lachen leicht an der Kamera vorbeischauen, Kopfhörer richten oder Laufschuhe binden.",
  "Holding a guitar like a prop while staring unblinkingly at the lens.": "Eine Gitarre wie ein Requisit halten und ohne zu blinzeln in die Linse starren.",
  "Match Your Photos to Your Stated Interests": "Stimme deine Fotos auf deine genannten Interessen ab",
  "Dating apps algorithmically reward consistency between your photo tags, prompt answers, and actual visual evidence. When your photos confirm your written bio, trust levels surge.": "Dating-Apps belohnen algorithmisch die Übereinstimmung von Fototags, Prompt-Antworten und sichtbaren Belegen. Wenn Fotos deine Bio bestätigen, steigt das Vertrauen.",
  "Mentioning you love trying new brunch spots and having an outdoor coffee terrace photo.": "Sagen, dass du gern neue Brunch-Orte ausprobierst, und ein Foto auf einer Caféterrasse zeigen.",
  "Saying you love nature while all six photos are taken in dark nightclubs or indoor bedrooms.": "Sagen, dass du die Natur liebst, während alle sechs Fotos in dunklen Clubs oder Schlafzimmern entstanden sind.",
  "Lighting Dictates Realism": "Licht bestimmt den Realismus",
  "Avoid harsh flash or dim yellow indoor light. Natural open shade, soft morning daylight, or warm ambient restaurant lighting keeps photos looking professional yet friend-taken.": "Vermeide harten Blitz oder schwaches gelbes Innenlicht. Offener Naturschatten, weiches Morgenlicht oder warmes Restaurantlicht wirken professionell und trotzdem wie von einem Freund aufgenommen.",
  "Diffused window light casting soft shadows across your face.": "Diffuses Fensterlicht mit weichen Schatten auf deinem Gesicht.",
  "Direct flash in a dark room casting harsh glare and greasy skin reflections.": "Direkter Blitz in einem dunklen Raum mit harten Lichtreflexen und glänzender Haut.",
  "Photo #2, #3, or #5": "Foto Nr. 2, 3 oder 5",
  "On Hinge, every photo can be paired with a caption or audio snippet. Position your activity photo immediately above or below a prompt that references your lifestyle (e.g., cooking or weekend routines) to give matches an effortless way to leave a comment.": "Auf Hinge kann jedes Foto mit Text oder Audio verbunden werden. Platziere dein Aktivitätsfoto direkt bei einem Prompt zu deinem Alltag, etwa Kochen oder Wochenendroutine, damit ein Kommentar leichtfällt.",
  "Use the 'My happy place is...' or 'Together we could...' prompts right next to your hobby photo.": "Setze die Prompts „Mein Wohlfühlort ist …“ oder „Zusammen könnten wir …“ direkt neben dein Hobbyfoto.",
  "Photo #3 or #4": "Foto Nr. 3 oder 4",
  "Tinder is fast-paced. Your opener must be a crystal-clear portrait, followed by a full-length photo. Place your activity shot in the middle slots to prove active lifestyle, build, and conversational depth before the profile closes.": "Tinder ist schnell. Der Opener muss ein glasklares Portrait sein, gefolgt von einer Ganzkörperaufnahme. Platziere die Aktivität in der Mitte, um aktiven Alltag, Statur und Gesprächstiefe zu zeigen.",
  "Ensure your Spotify top artists and lifestyle tags align with the mood of your activity photo.": "Achte darauf, dass deine Spotify-Lieblingskünstler und Lifestyle-Tags zur Stimmung des Aktivitätsfotos passen.",
  "Photo #2 or #4": "Foto Nr. 2 oder 4",
  "Because women message first on Bumble, providing easy 'message hooks' is critical. An intriguing hobby photo (like pour-over coffee, cooking, or trail walking) gives her something specific and comfortable to write about in her opening message.": "Da Frauen auf Bumble zuerst schreiben, sind einfache Gesprächsanstöße wichtig. Ein interessantes Hobbyfoto, etwa von Pour-over-Kaffee, Kochen oder einem Spaziergang, bietet einen konkreten Einstieg für die erste Nachricht.",
  "Link your Bumble lifestyle badges (e.g., Cooking, Fitness, Travel) to visual evidence in your photos.": "Verknüpfe deine Bumble-Lifestyle-Badges wie Kochen, Fitness oder Reisen mit sichtbaren Belegen in deinen Fotos.",
  "What are the best hobby photos for men on dating apps?": "Welche Hobbyfotos sind für Männer auf Dating-Apps am besten?",
  "The top-performing hobby photos are accessible, social, and warm: home cooking, café/coffee culture, natural fitness (running, training floor), city exploration/arts, and scenic travel. Avoid hobbies with negative associations or low face visibility, such as gaming screens, hunting/fishing trophies, or car engine bays.": "Die besten Hobbyfotos sind zugänglich, sozial und warm: Kochen zu Hause, Cafés, natürlicher Sport, Stadterkundung und Landschaftsreisen. Vermeide Themen mit negativen Assoziationen oder wenig Gesichtssichtbarkeit, etwa Gaming-Bildschirme, Jagd- und Angeltrophäen oder Motorhauben.",
  "Are gym photos bad to use on Tinder, Hinge, or Bumble?": "Sind Gym-Fotos auf Tinder, Hinge oder Bumble schlecht?",
  "Bathroom and locker-room mirror selfies are universally disliked because they look posed and self-absorbed. However, a naturally lit training photo—such as resting between sets on a gym floor or running outdoors—works very well if fitness is a genuine part of your routine. Keep it to one photo maximum in your lineup.": "Spiegel-Selfies im Bad oder Umkleideraum wirken gestellt und selbstbezogen. Ein natürlich beleuchtetes Trainingsfoto, etwa beim Pausieren zwischen Sätzen oder beim Laufen draußen, funktioniert gut, wenn Fitness wirklich zu deinem Alltag gehört. Verwende höchstens eines.",
  "How do I get natural activity photos if I don't have someone to take them?": "Wie bekomme ich natürliche Aktivitätsfotos, wenn niemand sie aufnehmen kann?",
  "You have three options: 1) Set a phone tripod with a 10-second timer or burst mode in natural light. 2) Ask a friend during an actual outing (e.g. coffee or a walk). 3) Use UnrealShot AI to turn 4–6 reference selfies into 15 varied lifestyle shoots (like home cooking, outdoor coffee, gym training, and city walks) within 30 minutes.": "Du hast drei Möglichkeiten: 1) Nutze ein Handy-Stativ mit 10-Sekunden-Timer oder Serienaufnahme bei natürlichem Licht. 2) Bitte einen Freund bei einem echten Ausflug um ein Foto. 3) Verwende UnrealShot, um aus 4–6 Referenz-Selfies in 30 Minuten 15 abwechslungsreiche Lifestyle-Shootings zu erstellen.",
  "How many activity photos should be in a 6-photo dating lineup?": "Wie viele Aktivitätsfotos gehören in eine Dating-Auswahl mit sechs Bildern?",
  "One to two activity photos is the sweet spot. Your profile needs a clear solo portrait opener, a full-length body shot, 1–2 genuine activity photos, a dressed-up or social context shot, and an everyday candid. Having more than two activity shots can make the profile feel cluttered or one-dimensional.": "Ein bis zwei Aktivitätsfotos sind ideal. Dein Profil braucht einen klaren Solo-Opener, ein Ganzkörperbild, 1–2 echte Aktivitätsfotos, einen gepflegten oder sozialen Kontext und ein spontanes Alltagsbild. Mehr als zwei können überladen oder eindimensional wirken.",
  "Should I include group sports or solo hobbies?": "Soll ich Teamsport oder individuelle Hobbys zeigen?",
  "Solo or small-context hobbies work best. Group sports often make it difficult for potential matches to identify which person you are. If you participate in team sports, use a solo photo of you on the sidelines or in gear rather than a crowded team huddle.": "Individuelle Hobbys oder kleine Kontexte funktionieren besser. Bei Teamsport ist oft schwer zu erkennen, wer du bist. Zeige dich lieber allein am Spielfeldrand oder in Ausrüstung statt in einer dichten Gruppe.",
  "How does UnrealShot generate authentic activity shoots without looking fake?": "Wie erstellt UnrealShot natürliche Aktivitäts-Shootings ohne künstlichen Look?",
  "UnrealShot uses reference-guided likeness to maintain your facial features while generating 15 distinct shoots with 4 related frames each (close, half-body, full-length, candid). The lighting, clothing, and environment are designed around believable everyday settings (like home kitchens, modern gyms, and outdoor cafes) with friend-taken camera angles.": "UnrealShot nutzt referenzgesteuerte Ähnlichkeit, um deine Gesichtszüge zu bewahren und 15 verschiedene Shootings mit jeweils 4 verbundenen Aufnahmen zu erstellen: nah, Halbfigur, Ganzkörper und spontan. Licht, Kleidung und Umgebung orientieren sich an glaubwürdigen Alltagsszenen mit natürlichen Kamerawinkeln.",
  "What hobbies should men avoid on dating profiles?": "Welche Hobbys sollten Männer in Dating-Profilen vermeiden?",
  "Avoid photos holding dead fish or game, photos where your face is completely concealed by helmets/goggles, pictures of your car without you in it, nightclub partying with red-eye flash, and messy room backgrounds.": "Vermeide Fotos mit toten Fischen oder Wild, Bilder mit vollständig verdecktem Gesicht durch Helm oder Brille, dein Auto ohne dich, Clubfotos mit Rotaugenblitz und unordentliche Zimmerhintergründe.",
  "How do activity photos improve dating app match rates?": "Wie verbessern Aktivitätsfotos Dating-App-Ergebnisse?",
  "Activity photos increase match quality and conversation rates because they provide context for your personality. On apps like Hinge, photos showing a specific activity receive over 4x more incoming comments than generic selfies because they make starting a conversation frictionless.": "Aktivitätsfotos geben deiner Persönlichkeit Kontext und erleichtern bessere Gespräche. Auf Apps wie Hinge bietet ein konkretes Aktivitätsbild einen deutlich leichteren Gesprächseinstieg als ein allgemeines Selfie.",
}

const ptBRText: TranslationMap = {
  "Dating Profile Lifestyle & Activity Guide": "Guia de estilo de vida e atividades para perfis de namoro",
  "Activity & Hobby Dating Photos for Men That Actually Spark Conversations": "Fotos de atividades e hobbies para homens que realmente geram conversas",
  "Learn how to choose and shoot believable activity photos for Tinder, Hinge, and Bumble. Discover the 5 best hobby categories, framing rules, and common mistakes to avoid.": "Aprenda a escolher e criar fotos de atividades convincentes para Tinder, Hinge e Bumble. Descubra as 5 melhores categorias de hobbies, regras de enquadramento e erros comuns a evitar.",
  "An activity photo gives potential matches an instant visual conversation starter and proves you have a vibrant, rounded life. The best activity photos show genuine interests—like cooking, fitness, coffee, or city exploration—captured in natural lighting with an unobstructed face, avoiding staged mirror selfies or obscured action shots.": "Uma foto de atividade oferece um assunto visual imediato para conversar e mostra que você tem uma vida variada. As melhores fotos mostram interesses reais — como cozinhar, fitness, café ou explorar a cidade — com luz natural e o rosto visível, evitando selfies no espelho encenadas ou ações que o escondam.",
  "5 high-converting hobby categories for men": "5 categorias de hobbies que geram conversas",
  "How to showcase fitness without cringey gym selfies": "Como mostrar fitness sem selfies constrangedoras na academia",
  "Pairing lifestyle photos with Hinge & Bumble prompts": "Combinando fotos de estilo de vida com prompts do Hinge e Bumble",
  "15 coherent AI lifestyle shoots generated in 30 minutes": "15 ensaios coerentes de estilo de vida gerados por IA em 30 minutos",
  "Conversation Starters": "Assuntos para começar conversas",
  "4x more openers on Hinge": "4 vezes mais comentários iniciais no Hinge",
  "Optimal Lineup Balance": "Equilíbrio ideal do conjunto",
  "1–2 activity shots in 6 photos": "1–2 fotos de atividade em 6",
  "Face Visibility": "Visibilidade do rosto",
  "Eyes & smile must stay clear": "Olhos e sorriso precisam ficar claros",
  "Delivery Turnaround": "Prazo de entrega",
  "60 photos in 30 minutes": "60 fotos em 30 minutos",
  "The Obscured Face Trap": "A armadilha do rosto escondido",
  "Skiing with goggles, motorcycle helmets, or distant mountain climbing shots where you are just a 10-pixel silhouette.": "Esquiar com óculos, usar capacete de moto ou aparecer distante escalando uma montanha, como uma silhueta de 10 pixels.",
  "The activity should provide setting and context, but your facial features and expression must remain recognizable.": "A atividade deve trazer cenário e contexto, mas seus traços e sua expressão precisam continuar reconhecíveis.",
  "The Aggressive Mirror Flex": "A ostentação agressiva no espelho",
  "Overly posed bathroom or locker-room gym selfies with harsh fluorescent overhead light and intense grimacing.": "Selfies muito posadas no banheiro ou vestiário da academia, com luz fluorescente dura e uma careta intensa.",
  "Capture natural, mid-workout moments in a daylight-filled space—resting between sets or adjusting gear—looking relaxed rather than performative.": "Capture momentos naturais durante o treino em um espaço iluminado: descansando entre séries ou ajustando o equipamento, com aparência relaxada em vez de performática.",
  "The Manufactured Persona": "A persona fabricada",
  "Posing with rented supercars, champagne bottles, or hobbies you don't actually do just to project status.": "Posar com supercarros alugados, garrafas de champanhe ou hobbies que você não pratica para transmitir status.",
  "Stick strictly to things you actually enjoy and could comfortably discuss for 30 minutes on a first date.": "Fique apenas com coisas de que você realmente gosta e sobre as quais poderia conversar confortavelmente por 30 minutos em um primeiro encontro.",
  "Home Cooking & Culinary Craft": "Cozinha em casa e criatividade culinária",
  "Warm, capable, domestic competence": "Acolhimento, habilidade e autonomia",
  "Cooking is universally attractive and conveys warmth, creativity, and self-sufficiency. It gives your match an effortless opening line about favorite recipes or date-night meals.": "Cozinhar transmite acolhimento, criatividade e autonomia. Também oferece um assunto fácil sobre receitas favoritas ou um jantar a dois.",
  "Capture a casual mid-prep moment at a kitchen counter with natural window lighting rather than posing stiffly holding a completed plate.": "Capture um momento casual durante o preparo na bancada, com luz natural da janela, em vez de posar segurando um prato pronto.",
  "Pairs perfectly with Hinge's 'The secret to getting along with me' or 'My specialty dish'.": "Combina perfeitamente com os prompts do Hinge “O segredo para se dar bem comigo” ou “Meu prato especial”.",
  "Active Lifestyle & Fitness": "Estilo de vida ativo e fitness",
  "Discipline, energy, healthy routine": "Disciplina, energia e rotina saudável",
  "Demonstrates physical vitality and commitment to wellbeing without needing an aggressive shirtless mirror picture. Shows you take care of yourself.": "Demonstra vitalidade física e cuidado com o bem-estar sem precisar de uma foto agressiva sem camisa no espelho. Mostra que você se cuida.",
  "Use daylight gyms, outdoor running paths, or bouldering walls. Keep expressions natural or smiling rather than straining under heavy weight.": "Use academias com luz natural, pistas de corrida ao ar livre ou paredes de escalada. Prefira expressões naturais ou sorridentes, não esforço exagerado sob muito peso.",
  "Great for Bumble's 'Active' badge or Hinge's 'Sunday routine' prompt.": "Ótimo para o selo “Ativo” do Bumble ou o prompt “Rotina de domingo” do Hinge.",
  "Café Culture & Reading": "Cultura do café e leitura",
  "Approachable, conversational, relaxed": "Acessível, conversador e relaxado",
  "A neighborhood café terrace or cozy bookstore corner signals intellectual curiosity, calmness, and low-pressure date potential.": "Uma varanda de café do bairro ou um canto aconchegante de livraria transmite curiosidade intelectual, calma e potencial para um encontro sem pressão.",
  "Sit at a table in open shade, holding a warm cup or glancing away from a book with a slight, natural reaction.": "Sente-se em uma mesa na sombra aberta, segure uma bebida quente ou olhe para longe do livro com uma reação leve e natural.",
  "Pairs seamlessly with 'Best spot in town' or 'Together we could find the best coffee'.": "Combina bem com “Melhor lugar da cidade” ou “Juntos podemos encontrar o melhor café”.",
  "Urban Exploration & Street Life": "Exploração urbana e vida na rua",
  "Curiosity, style, modern vitality": "Curiosidade, estilo e energia moderna",
  "Shows you enjoy exploring your city, visiting markets, architecture, or galleries. Naturally displays full-length posture, height, and street style.": "Mostra que você gosta de explorar sua cidade, mercados, arquitetura ou galerias. Também apresenta naturalmente postura, altura e estilo urbano.",
  "Walk down a textured pedestrian street with natural movement and casual layering (overshirt, knit, or clean jacket).": "Caminhe por uma rua de pedestres com textura e movimento natural, usando camadas casuais como camisa sobreposta, tricô ou uma jaqueta simples.",
  "Ideal for 'A quick rant about' or 'Let's debate: best neighborhood'.": "Ideal para “Uma reclamação rápida sobre” ou “Vamos debater: melhor bairro”.",
  "Coastal & Nature Walks": "Caminhadas na costa e na natureza",
  "Adventurous, open, grounded": "Aventureiro, aberto e pé no chão",
  "Brings fresh air and scenery into your lineup. Signals you enjoy the outdoors and weekend getaways without requiring extreme mountaineering gear.": "Traz ar livre e paisagem para o conjunto. Mostra que você gosta da natureza e de escapadas de fim de semana sem exigir equipamento extremo de montanhismo.",
  "Shoot during golden hour or bright overcast daylight along a scenic coastal path or trail, with wind-blown natural movement.": "Fotografe na hora dourada ou sob luz nublada clara em um caminho costeiro ou trilha, com movimento natural do vento.",
  "Pairs well with 'All I ask is that you' or 'My simple pleasures'.": "Combina bem com “Tudo o que peço é que você” ou “Meus prazeres simples”.",
  "The Subject is Always You, Not the Activity": "O assunto é sempre você, não a atividade",
  "The hobby is the backdrop that provides flavor and conversation material; you are still the focus. Avoid photos where the equipment, scenic vista, or sports car takes up 90% of the frame while you are an afterthought.": "O hobby é o pano de fundo e fornece assunto para conversar, mas você continua sendo o foco. Evite fotos em que o equipamento, a paisagem ou o carro esportivo ocupem 90% da imagem e você fique em segundo plano.",
  "A half-body shot of you prepping ingredients at a counter with a visible, relaxed smile.": "Uma foto de meio corpo preparando ingredientes na bancada com um sorriso relaxado e visível.",
  "A wide-angle shot of a pizza oven where your back is turned and your face cannot be seen.": "Uma foto grande-angular de um forno de pizza em que você está de costas e seu rosto não aparece.",
  "Action Over Posing (The 70/30 Candid Rule)": "Ação em vez de pose (a regra espontânea 70/30)",
  "Great activity photos capture you in motion or in a moment of pause during an activity. Staring dead-center into the lens with two hands on a prop often feels like a stock photo.": "Boas fotos de atividade mostram você em movimento ou em uma pausa. Encarar a lente com as duas mãos em um objeto muitas vezes parece foto de banco de imagens.",
  "Looking slightly off-camera while laughing, adjusting headphones, or tying running shoes.": "Olhar um pouco para fora da câmera enquanto ri, ajusta fones ou amarra o tênis de corrida.",
  "Holding a guitar like a prop while staring unblinkingly at the lens.": "Segurar um violão como adereço enquanto encara a lente sem piscar.",
  "Match Your Photos to Your Stated Interests": "Combine suas fotos com os interesses que você declarou",
  "Dating apps algorithmically reward consistency between your photo tags, prompt answers, and actual visual evidence. When your photos confirm your written bio, trust levels surge.": "Os aplicativos valorizam a consistência entre tags das fotos, respostas aos prompts e evidências visuais. Quando as fotos confirmam sua bio, a confiança aumenta.",
  "Mentioning you love trying new brunch spots and having an outdoor coffee terrace photo.": "Dizer que você adora conhecer lugares novos para brunch e mostrar uma foto em uma varanda de café.",
  "Saying you love nature while all six photos are taken in dark nightclubs or indoor bedrooms.": "Dizer que ama a natureza enquanto as seis fotos foram tiradas em boates escuras ou quartos.",
  "Lighting Dictates Realism": "A iluminação define o realismo",
  "Avoid harsh flash or dim yellow indoor light. Natural open shade, soft morning daylight, or warm ambient restaurant lighting keeps photos looking professional yet friend-taken.": "Evite flash duro ou luz interna amarela e fraca. Sombra aberta natural, luz suave da manhã ou iluminação quente de restaurante deixam a foto profissional, mas com aparência feita por um amigo.",
  "Diffused window light casting soft shadows across your face.": "Luz difusa da janela criando sombras suaves no rosto.",
  "Direct flash in a dark room casting harsh glare and greasy skin reflections.": "Flash direto em um cômodo escuro criando brilho duro e reflexos oleosos na pele.",
  "Photo #2, #3, or #5": "Foto nº 2, 3 ou 5",
  "On Hinge, every photo can be paired with a caption or audio snippet. Position your activity photo immediately above or below a prompt that references your lifestyle (e.g., cooking or weekend routines) to give matches an effortless way to leave a comment.": "No Hinge, cada foto pode receber legenda ou áudio. Posicione sua foto de atividade perto de um prompt sobre seu estilo de vida, como cozinhar ou a rotina de fim de semana, para facilitar comentários.",
  "Use the 'My happy place is...' or 'Together we could...' prompts right next to your hobby photo.": "Use os prompts “Meu lugar feliz é…” ou “Juntos podemos…” ao lado da foto do hobby.",
  "Photo #3 or #4": "Foto nº 3 ou 4",
  "Tinder is fast-paced. Your opener must be a crystal-clear portrait, followed by a full-length photo. Place your activity shot in the middle slots to prove active lifestyle, build, and conversational depth before the profile closes.": "O Tinder é rápido. A abertura deve ser um retrato muito claro, seguido de uma foto de corpo inteiro. Coloque a atividade no meio para mostrar estilo de vida ativo, porte e profundidade.",
  "Ensure your Spotify top artists and lifestyle tags align with the mood of your activity photo.": "Garanta que seus principais artistas do Spotify e tags de estilo de vida combinem com o clima da foto.",
  "Photo #2 or #4": "Foto nº 2 ou 4",
  "Because women message first on Bumble, providing easy 'message hooks' is critical. An intriguing hobby photo (like pour-over coffee, cooking, or trail walking) gives her something specific and comfortable to write about in her opening message.": "Como as mulheres mandam a primeira mensagem no Bumble, é importante oferecer assuntos fáceis. Uma foto interessante de café coado, cozinha ou caminhada dá algo específico e confortável para ela comentar.",
  "Link your Bumble lifestyle badges (e.g., Cooking, Fitness, Travel) to visual evidence in your photos.": "Relacione seus selos de estilo de vida do Bumble, como Cozinha, Fitness ou Viagem, a evidências visuais nas fotos.",
  "What are the best hobby photos for men on dating apps?": "Quais são as melhores fotos de hobbies para homens em aplicativos de namoro?",
  "The top-performing hobby photos are accessible, social, and warm: home cooking, café/coffee culture, natural fitness (running, training floor), city exploration/arts, and scenic travel. Avoid hobbies with negative associations or low face visibility, such as gaming screens, hunting/fishing trophies, or car engine bays.": "As melhores fotos de hobbies são acessíveis, sociais e acolhedoras: cozinhar em casa, cafés, fitness natural, explorar a cidade e viagens. Evite temas com associações negativas ou pouca visibilidade do rosto, como telas de jogos, troféus de caça/pesca ou motores de carros.",
  "Are gym photos bad to use on Tinder, Hinge, or Bumble?": "Fotos de academia são ruins no Tinder, Hinge ou Bumble?",
  "Bathroom and locker-room mirror selfies are universally disliked because they look posed and self-absorbed. However, a naturally lit training photo—such as resting between sets on a gym floor or running outdoors—works very well if fitness is a genuine part of your routine. Keep it to one photo maximum in your lineup.": "Selfies no espelho do banheiro ou vestiário costumam ser mal recebidas por parecerem posadas e autocentradas. Uma foto de treino com luz natural, descansando entre séries ou correndo ao ar livre, funciona se fitness fizer parte da rotina. Use no máximo uma.",
  "How do I get natural activity photos if I don't have someone to take them?": "Como conseguir fotos naturais de atividade se não tenho quem as tire?",
  "You have three options: 1) Set a phone tripod with a 10-second timer or burst mode in natural light. 2) Ask a friend during an actual outing (e.g. coffee or a walk). 3) Use UnrealShot AI to turn 4–6 reference selfies into 15 varied lifestyle shoots (like home cooking, outdoor coffee, gym training, and city walks) within 30 minutes.": "Você tem três opções: 1) usar um tripé com temporizador de 10 segundos ou modo contínuo na luz natural; 2) pedir a um amigo durante um passeio real; 3) usar a UnrealShot para transformar 4–6 selfies de referência em 15 ensaios variados, como cozinha, café, academia e cidade, em 30 minutos.",
  "How many activity photos should be in a 6-photo dating lineup?": "Quantas fotos de atividade devem estar em um conjunto de seis fotos?",
  "One to two activity photos is the sweet spot. Your profile needs a clear solo portrait opener, a full-length body shot, 1–2 genuine activity photos, a dressed-up or social context shot, and an everyday candid. Having more than two activity shots can make the profile feel cluttered or one-dimensional.": "Uma ou duas fotos de atividade é o ponto ideal. Seu perfil precisa de um retrato solo claro, uma foto de corpo inteiro, 1–2 atividades reais, um contexto arrumado ou social e uma espontânea do cotidiano. Mais de duas podem deixar o perfil carregado ou limitado.",
  "Should I include group sports or solo hobbies?": "Devo incluir esportes coletivos ou hobbies individuais?",
  "Solo or small-context hobbies work best. Group sports often make it difficult for potential matches to identify which person you are. If you participate in team sports, use a solo photo of you on the sidelines or in gear rather than a crowded team huddle.": "Hobbies individuais ou em pequenos contextos funcionam melhor. Esportes coletivos dificultam identificar você. Se pratica esporte de equipe, use uma foto sozinho na lateral ou com o equipamento, não em um grupo lotado.",
  "How does UnrealShot generate authentic activity shoots without looking fake?": "Como a UnrealShot gera ensaios de atividade autênticos sem parecer falso?",
  "UnrealShot uses reference-guided likeness to maintain your facial features while generating 15 distinct shoots with 4 related frames each (close, half-body, full-length, candid). The lighting, clothing, and environment are designed around believable everyday settings (like home kitchens, modern gyms, and outdoor cafes) with friend-taken camera angles.": "A UnrealShot usa semelhança guiada por referências para preservar seus traços ao gerar 15 ensaios diferentes com 4 imagens relacionadas cada: próxima, meio corpo, corpo inteiro e espontânea. Luz, roupa e ambiente são pensados para cenários cotidianos convincentes, com ângulos naturais.",
  "What hobbies should men avoid on dating profiles?": "Quais hobbies os homens devem evitar nos perfis de namoro?",
  "Avoid photos holding dead fish or game, photos where your face is completely concealed by helmets/goggles, pictures of your car without you in it, nightclub partying with red-eye flash, and messy room backgrounds.": "Evite fotos segurando peixes ou animais mortos, imagens em que capacetes ou óculos escondem completamente o rosto, fotos do carro sem você, festas em boates com olhos vermelhos e fundos de quarto bagunçados.",
  "How do activity photos improve dating app match rates?": "Como fotos de atividade melhoram os resultados em aplicativos de namoro?",
  "Activity photos increase match quality and conversation rates because they provide context for your personality. On apps like Hinge, photos showing a specific activity receive over 4x more incoming comments than generic selfies because they make starting a conversation frictionless.": "Fotos de atividade dão contexto à sua personalidade e favorecem conversas melhores. Em aplicativos como o Hinge, uma atividade específica facilita muito mais o início de uma conversa do que um selfie genérico.",
}

function translateValue(value: unknown, translations: TranslationMap): unknown {
  if (typeof value === "string") return translations[value] ?? value
  if (Array.isArray(value)) return value.map((item) => translateValue(item, translations))
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, translateValue(child, translations)]))
  return value
}

const translations: Record<Exclude<PublishedPublicLocale, "en">, TranslationMap> = { fr: frText, es: esText, de: deText, "pt-BR": ptBRText }

export const activityPageUi: Record<PublishedPublicLocale, ActivityPageUi> = { en: enUi, fr: frUi, es: esUi, de: deUi, "pt-BR": ptBRUi }

export function getLocalizedActivityPageData(locale: PublishedPublicLocale) {
  if (locale === "en") return activityPageData
  return translateValue(activityPageData, translations[locale]) as typeof activityPageData
}
