-- ==============================================================================
-- UNREALSHOT AI — DATING PHOTOSHOOT PIVOT (CLEAN MASTER MIGRATION)
-- Run this single script in your fresh Supabase project SQL Editor.
-- ==============================================================================

-- Enable UUID extension
create extension if not exists "pgcrypto";

-- ==============================================================================
-- 1. PROFILES TABLE (Linked to auth.users)
-- ==============================================================================
create table if not exists public.profiles (
  id uuid not null primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  has_completed_onboarding boolean not null default false,
  constraint profiles_user_id_unique unique (user_id)
);

create index if not exists profiles_user_id_idx on public.profiles (user_id);
alter table public.profiles enable row level security;

create policy "Users can view own profile" 
  on public.profiles for select 
  to authenticated 
  using (auth.uid() = user_id);

create policy "Users can update own profile" 
  on public.profiles for update 
  to authenticated 
  using (auth.uid() = user_id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, user_id)
  values (new.id, new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ==============================================================================
-- 2. MODELS TABLE (User's subject models)
-- ==============================================================================
create table if not exists public.models (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text null,
  type text not null default 'Male',
  mode text not null default 'single' check (mode in ('single', 'couple')),
  status text not null default 'ready',
  is_custom boolean default false,
  created_at timestamp with time zone not null default now()
);

create index if not exists models_user_id_idx on public.models(user_id);
alter table public.models enable row level security;

create policy "Users can view own models"
  on public.models for select
  using (auth.uid() = user_id);

create policy "Users can create own models"
  on public.models for insert
  with check (auth.uid() = user_id);

create policy "Users can update own models"
  on public.models for update
  using (auth.uid() = user_id);

create policy "Users can delete own models"
  on public.models for delete
  using (auth.uid() = user_id);


-- ==============================================================================
-- 3. SAMPLES TABLE (Reference face photos)
-- ==============================================================================
create table if not exists public.samples (
  id bigint generated by default as identity primary key,
  "modelId" bigint not null references public.models(id) on delete cascade,
  uri text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists samples_modelId_idx on public.samples("modelId");
alter table public.samples enable row level security;

create policy "Users can view samples for own models"
  on public.samples for select
  using (
    exists (
      select 1 from public.models
      where models.id = samples."modelId"
      and models.user_id = auth.uid()
    )
  );

create policy "Users can insert samples for own models"
  on public.samples for insert
  with check (
    exists (
      select 1 from public.models
      where models.id = samples."modelId"
      and models.user_id = auth.uid()
    )
  );

create policy "Users can delete samples for own models"
  on public.samples for delete
  using (
    exists (
      select 1 from public.models
      where models.id = samples."modelId"
      and models.user_id = auth.uid()
    )
  );


-- ==============================================================================
-- 4. IMAGES TABLE (General gallery outputs)
-- ==============================================================================
create table if not exists public.images (
  id bigint generated by default as identity primary key,
  "modelId" bigint not null references public.models(id) on delete cascade,
  uri text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists images_modelId_idx on public.images("modelId");
alter table public.images enable row level security;

create policy "Users can view own images"
  on public.images for select
  using (
    exists (
      select 1 from public.models
      where models.id = images."modelId"
      and models.user_id = auth.uid()
    )
  );

create policy "Users can insert own images"
  on public.images for insert
  with check (
    exists (
      select 1 from public.models
      where models.id = images."modelId"
      and models.user_id = auth.uid()
    )
  );


-- ==============================================================================
-- 5. USER PREFERENCES (3-Question Dating Intake)
-- ==============================================================================
create table if not exists public.user_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  vibe text not null check (vibe in ('urban', 'outdoorsy', 'homebody')),
  style text not null check (style in ('casual', 'sharp', 'street')),
  hobby_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists idx_user_preferences_user_id on public.user_preferences(user_id);
alter table public.user_preferences enable row level security;

create policy "Users can view own preferences"
  on public.user_preferences for select
  using (auth.uid() = user_id);

create policy "Users can insert own preferences"
  on public.user_preferences for insert
  with check (auth.uid() = user_id);

create policy "Users can update own preferences"
  on public.user_preferences for update
  using (auth.uid() = user_id);


-- ==============================================================================
-- 6. USER SHOOT ORDERS (100-Photo Shoot Orders)
-- ==============================================================================
create table if not exists public.user_shoot_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  model_id bigint not null references public.models(id) on delete cascade,
  preferences_id uuid references public.user_preferences(id) on delete set null,
  status text not null default 'queued' check (status in (
    'queued',
    'developing',
    'ready',
    'partial_failed',
    'failed',
    'failed_components_present'
  )),
  trigger_run_id text,
  custom_credits_remaining int not null default 30,
  photos_target int not null default 100,
  fal_cost_cents int not null default 0,
  refund_state text not null default 'none' check (refund_state in ('none', 'requested', 'refunded')),
  created_at timestamptz not null default now(),
  ready_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_shoot_orders_user_id on public.user_shoot_orders(user_id);
create index if not exists idx_user_shoot_orders_status on public.user_shoot_orders(status);
create index if not exists idx_user_shoot_orders_model_id on public.user_shoot_orders(model_id);
alter table public.user_shoot_orders enable row level security;

create policy "Users can view own orders"
  on public.user_shoot_orders for select
  using (auth.uid() = user_id);

create policy "Users can insert own orders"
  on public.user_shoot_orders for insert
  with check (auth.uid() = user_id);


-- ==============================================================================
-- 7. ORDER PHOTOS (100 Pre-Allocated Photo Slots with Resilient IDs)
-- ==============================================================================
create table if not exists public.order_photos (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.user_shoot_orders(id) on delete cascade,
  deterministic_id text unique,
  bucket text not null check (bucket in ('anchor', 'social', 'travel', 'active', 'street')),
  slot int not null check (slot >= 1 and slot <= 20),
  prompt_template text not null,
  -- Authored output size for this shot. Null on rows allocated before v4
  -- sizing shipped; those fall back to the ratio parsed from prompt_template.
  image_width int,
  image_height int,
  status text not null default 'pending' check (status in (
    'pending',
    'in_progress',
    'pending_verification',
    'completed',
    'failed'
  )),
  aesthetic_score real,
  fal_request_id text,
  image_url text,
  attempt_count int not null default 0,
  failed_reason text,
  fal_cost_cents int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, bucket, slot)
);

create index if not exists idx_order_photos_order_id on public.order_photos(order_id);
create index if not exists idx_order_photos_status on public.order_photos(status);
create index if not exists idx_order_photos_order_status on public.order_photos(order_id, status);
create index if not exists idx_order_photos_deterministic_id on public.order_photos(deterministic_id);
alter table public.order_photos enable row level security;

create policy "Users can view own order photos"
  on public.order_photos for select
  using (
    exists (
      select 1 from public.user_shoot_orders o
      where o.id = order_photos.order_id and o.user_id = auth.uid()
    )
  );


-- ==============================================================================
-- 8. PROMPT LIBRARY (Optional reference table)
-- ==============================================================================
create table if not exists public.prompt_library (
  id uuid primary key default gen_random_uuid(),
  bucket text not null check (bucket in ('anchor', 'social', 'travel', 'active', 'street')),
  slot int not null check (slot >= 1 and slot <= 20),
  prompt_template text not null,
  style_modifiers jsonb not null default '{}'::jsonb,
  posing_cues jsonb not null default '{}'::jsonb,
  params jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  version int not null default 1,
  created_at timestamptz not null default now(),
  unique (bucket, slot, version)
);

alter table public.prompt_library enable row level security;
create policy "Anyone can read active prompts"
  on public.prompt_library for select
  using (is_active = true);


-- ==============================================================================
-- 9. OPTIONAL: CREDITS & PAYMENTS (For credit balance and payment tracking)
-- ==============================================================================
create table if not exists public.credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  credits int not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.credits enable row level security;
create policy "Users can view own credits"
  on public.credits for select
  using (auth.uid() = user_id);

create table if not exists public.dodo_payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  dodo_payment_id text,
  dodo_checkout_session_id text,
  pricing_plan_id text,
  amount numeric not null,
  currency text not null default 'USD',
  status text not null default 'pending',
  credits int default 0,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dodo_payments enable row level security;
create policy "Users can view own payments"
  on public.dodo_payments for select
  using (auth.uid() = user_id);
