-- ==============================================================================
-- Migration: 019_add_dodo_payments_system.sql
-- Standalone incremental migration for DodoPayments integration
-- Safe & Idempotent (uses IF NOT EXISTS and DROP POLICY IF EXISTS)
-- ==============================================================================

-- 1. Pricing Plans Table
create table if not exists public.dodo_pricing_plans (
  id uuid not null primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text not null,
  description text,
  price numeric(10, 2) not null,
  credits integer not null default 30,
  currency text not null default 'USD',
  dodo_product_id text,
  is_active boolean not null default true,
  metadata jsonb default '{}'::jsonb
);

create index if not exists dodo_pricing_plans_active_idx on public.dodo_pricing_plans (is_active);
create index if not exists dodo_pricing_plans_dodo_product_id_idx on public.dodo_pricing_plans (dodo_product_id);
alter table public.dodo_pricing_plans enable row level security;

drop policy if exists "Anyone can read active pricing plans" on public.dodo_pricing_plans;
create policy "Anyone can read active pricing plans"
  on public.dodo_pricing_plans for select
  using (is_active = true);

-- Seed default $59 Dating Photoshoot Plan
insert into public.dodo_pricing_plans (
  name,
  description,
  price,
  credits,
  currency,
  dodo_product_id,
  is_active,
  metadata
) values (
  'Complete Dating Photoshoot',
  '100 dating photos across 5 high-converting styles with 30 custom regeneration credits included.',
  59.00,
  30,
  'USD',
  'p_dating_59',
  true,
  '{"features": ["100 Dating Photos", "5 Styles", "30 Custom Credits", "~90-Min Delivery", "ZIP Download"]}'::jsonb
) on conflict do nothing;

-- 2. Payments Table
create table if not exists public.dodo_payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  dodo_payment_id text,
  dodo_checkout_session_id text,
  pricing_plan_id text,
  amount numeric not null,
  currency text not null default 'USD',
  status text not null default 'pending',
  credits int default 0,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dodo_payments_user_id_idx on public.dodo_payments(user_id);
create index if not exists dodo_payments_checkout_session_idx on public.dodo_payments(dodo_checkout_session_id);
alter table public.dodo_payments enable row level security;

drop policy if exists "Users can view own payments" on public.dodo_payments;
create policy "Users can view own payments"
  on public.dodo_payments for select
  using (auth.uid() = user_id);

-- 3. Subscriptions / Access Passes
create table if not exists public.dodo_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  dodo_subscription_id text,
  dodo_checkout_session_id text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dodo_subscriptions_user_id_idx on public.dodo_subscriptions(user_id);
alter table public.dodo_subscriptions enable row level security;

drop policy if exists "Users can view own subscriptions" on public.dodo_subscriptions;
create policy "Users can view own subscriptions"
  on public.dodo_subscriptions for select
  using (auth.uid() = user_id);

-- 4. Webhook Events Table (Idempotent webhook tracking)
create table if not exists public.dodo_webhook_events (
  id uuid primary key default gen_random_uuid(),
  dodo_event_id text unique not null,
  event_type text not null,
  processed boolean not null default false,
  processed_at timestamptz,
  data jsonb not null,
  error_message text,
  retry_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists dodo_webhook_events_dodo_event_id_idx on public.dodo_webhook_events (dodo_event_id);
create index if not exists dodo_webhook_events_event_type_idx on public.dodo_webhook_events (event_type);
create index if not exists dodo_webhook_events_processed_idx on public.dodo_webhook_events (processed);

-- 5. Credits Table
create table if not exists public.credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  credits int not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.credits enable row level security;

drop policy if exists "Users can view own credits" on public.credits;
create policy "Users can view own credits"
  on public.credits for select
  using (auth.uid() = user_id);
